### ISSUE TITLE
If app is already authenticated doesn't redirect past the auth screen 

### ISSUE THREAD

**Issue by ckshei** [near/near-wallet#100]
with an app that has already been authorized, you can still hit the 'Authenticate this app' page. 
Pressing allow will look broken, but will show this error message in the console: 

Error message: 
```
Error: Transaction CmiSWqLeoFATJoFVYA1iBKzaCe5yzDpTsSsTLVHjaAEv failed. Runtime error: Cannot add a public key that already exists on the account
    at p.signAndSendTransaction
```

**Comment by jimmy3dita** [comment]
Duplicate of #960
