### ISSUE TITLE
Looks like not enough balance error is not handled properly when staking

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#1006]
**Problem**

> the reason for my transaction failure is an actual scenario when the balance is not enough. So the transaction failure response is throwing it properly ("The balance that can be deposited to the staking pool is lower than the extra amount."). But its not throwing to the staking UI, which might need a fix, and user keeps trying to send the 2fa in loop without knowing the actual error. JS console error: "Error: Transaction failed with return value: undefined"

**Expected Behavior**

UI shows error and doesn't let user just do the same thing in a loop without understanding that it is failing.

**Steps to reproduce**

TODO: Not reproduced yet, this is user report

**Comment by kcole16** [comment]
**Steps to reproduce**
1. Select a validator
2. Attempt to stake your entire available balance
3. Encounter error
4. Attempt to stake 1 NEAR less than available balance
