### ISSUE TITLE
Two-Factor Authentication not success

### ISSUE THREAD

**Issue by icerove** [near/near-wallet#1010]
**Problem**
After Enter 6-digit verification code received from email, and click verify code & enable, it will show `Sorry an error has occurred. You may want to try again.` But after click the button, nothing happens and get error on console: 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/33007476/95925229-1f711380-0d6e-11eb-953a-a7595b0027a4.png">

After several time, I see it needs to refresh the page to get the latest status for 2FA, but it show this: 
<img width="407" alt="image" src="https://user-images.githubusercontent.com/33007476/95925367-7840ac00-0d6e-11eb-93b4-4ef4f5ec912d.png">
I think Date is not shown here? 

**Expected Behavior**
2FA successfully enabled?

**Steps to reproduce**

1. create new account on testnet wallet with seed phase
2. enable 2FA on profile.

**Comment by Patrick1904** [comment]
@icerove I'm not able to reproduce this. Please let me know if you continue to encounter this issue. Good catch on the date not showing, it seems that it's not reaching the front-end, so fixing this w/ @mattlockyer.

**Comment by icerove** [comment]
this time is like this:
After enable 2FA page, it goes back to profile page with success banner.
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/33007476/96167075-b60b1500-0ed3-11eb-83ca-30ceeb90adbf.png">

but 2FA column is like this:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/33007476/96167188-e18dff80-0ed3-11eb-8b90-6b3ad29f2ea5.png">

after refresh page, the 2FA column is like this: 
<img width="474" alt="image" src="https://user-images.githubusercontent.com/33007476/96167255-fb2f4700-0ed3-11eb-8599-82c7f2b63032.png">
without date

**Comment by Patrick1904** [comment]
@icerove thanks for clarifying. I fixed the date issue here: https://github.com/near/near-wallet/pull/1034

Will fix the bug where you have to refresh the page for 2FA to show as active
