### ISSUE TITLE
Improve visibility of Unstake button

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1021]
Unstake button is hard to find.
It's both unclear from the "Stake" screen and on the specific pool it's not very visible.

**Comment by Patrick1904** [comment]
@corwinharrell any thoughts on this?

**Comment by corwinharrell** [comment]
@Patrick1904 since we're adding it to the main staking dashboard in #755, that should help some with discoverability. Otherwise the next thing to do would be to just use a primary button (same as `WITHDRAW`) vs the secondary variant it's using now.

**Comment by corwinharrell** [comment]
Addressed in https://github.com/near/near-wallet/issues/1538
