### ISSUE TITLE
No default translation when unstaking

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1024]
## Steps to reproduce

1. Stake
2. Unstake
3. Confirmed on Ledger 
4. Came back with this screenshot

<img width="687" alt="Screen Shot 2020-10-14 at 3 00 51 AM" src="https://user-images.githubusercontent.com/175486/96026464-5f3a0880-0e0b-11eb-94e9-476f2f2745a0.png">

**Comment by Patrick1904** [comment]
Haven't been able to repro yet. @kcole16 can you please test to see if you can repro this?

**Comment by kcole16** [comment]
Also can't repro. Is this still an issue @ilblackdragon?
