### ISSUE TITLE
Increase Minimum Balance by 1 NEAR

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1026]
### Overview
Users are occasionally getting stuck by transferring out their entire liquid balance, to the point where they cannot add keys (e.g. login), transfer funds, stake, or really do anything until they receive more NEAR. We should increase the `Minimum Balance` (and decrease `Available Balance`) to account for this.

Additionally, we should add the "reserved balance" (currently hidden) to the `Minimum Balance`, so the balances in Profile add up to `Total Balance`.

### Acceptance Criteria
- [ ] Users cannot transfer their entire liquid balance 
- [ ] `Available Balance` subtracts at least 1 NEAR over the actual `Minimum Balance`
- [ ] `Minimum Balance` reflects all "reserved balances" (state stake, etc)
- [ ] `Total Balance` reflects all NEAR controlled by the user

- [ ] `Minimum Balance` reflects all non-transferrable balances together

**Comment by mattlockyer** [comment]
Just want to keep track of this:

![image](https://user-images.githubusercontent.com/321340/96497545-b4a55980-11ff-11eb-9b06-9759b0c5db11.png)
![image](https://user-images.githubusercontent.com/321340/96497568-bc64fe00-11ff-11eb-8217-557b9b602379.png)
![image](https://user-images.githubusercontent.com/321340/96497578-c1c24880-11ff-11eb-9774-a9c8a6d60060.png)
