### ISSUE TITLE
Show RPC error text in error notification

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1028]
### Overview
We haven't sufficiently covered the potential errors with human readable ones. In the meantime, we should show the actual error message in the banner to better help us debug user issues.

### Acceptance Criteria
- [ ] When encountering an RPC-delivered error, the user sees both our title and error message, and the RPC-returned error message in the notification

**Comment by marcinbodnar** [comment]
@corwinharrell It looks like this with #1029 changes
![image](https://user-images.githubusercontent.com/36210360/96154887-942f8380-0f0f-11eb-953a-ab4883e07141.png)

**Comment by corwinharrell** [comment]
Here are the designs for the changes to the alert component:

![alert](https://user-images.githubusercontent.com/5934188/96176888-fcc03580-0efa-11eb-9e0c-a276aeaf5080.jpg)

And here are the svg icons @marcinbodnar (they should be constrained to 24px):

[alert-icons.zip](https://github.com/near/near-wallet/files/5387319/alert-icons.zip)
