### ISSUE TITLE
Unable to recover 2FA account using seed phrase

### ISSUE THREAD

**Issue by mattlockyer** [near/near-wallet#1055]
**Problem**

I've diagnosed a couple of rare cases where users created account with seed phrase and then set up 2FA and for some reason this is causing issues with recovery.
In the 2FA enabling, only 1 key is converted to a LAK with permissions to add_request_and_confirm This is fine, because the full access key for seed phrase is and will always be a full access key.
See example here: https://explorer.near.org/accounts/shitcoinsenpai.near 

I have verified that all publicKeys on the account return the correct AccountId via the helper URL, so I'm not sure what the specific issue is?

**Expected Behavior**

User can recover account with seed phrase.

**Steps to reproduce**

N/A still asking users for steps and errors. Will update.

1. 
2.

**Comment by kcole16** [comment]
@mattlockyer Do we think this is still an issue?

**Comment by mattlockyer** [comment]
Users never responded and could not repro.

Haven't had a **seed recovery** issue since.
