### ISSUE TITLE
User can create, fund and sign in to implicit account

### ISSUE THREAD

**Issue by mattlockyer** [near/near-wallet#1056]
## Story

As a USER who wants to get off exchange / other wallet and into NEAR Wallet, I want to create an account in the NEAR wallet, fund it and then transfer my funds to that account, so I can move my assets into the NEAR Wallet.

## Acceptance Criteria

- [ ] User can create implicit account via seed phrase
- [ ] Seed phrase is verified
- [ ] User sees funding accountId and can fund account
- [ ] Once funded user can continue with recovery link to sign in

## Unhappy Path

User creates account, funds it, clears browser cache and loses seed phrase.
User clears browser cache and loses option to continue, they need to manually enter seed phrase in recovery options of Wallet.

## Testing

https://wallet.testnet.near.org/create-implicit
Then fund it from another account on testnet (You just need 1N).
Then click continue and recover into account.

## Assets

- N/A

## NOTES

- Sprinted last friday: https://github.com/near/near-wallet/pull/1052#issuecomment-712191127

**Comment by corwinharrell** [comment]
Alright so I walked through this in its current state to provide some feedback through the UX lens. Here is my [video recording](https://streamable.com/z5qyiy) with moment-to-moment commentary if you'd rather watch than read (or both).


## UX Audit
1. `/create-implicit`
    - Starting at seed phrase setup is jarring, there is no introduction to the user to indicate that they are creating a new account.
    - What if they want to use a method other than seed phrase?

2. `/create-implicit/fund` 
    - Instructing the user to perform these actions is odd
    - It assumes that the user has another account which they can use to fund the new account.
        - What if they don't have another account?
    - User: _"Why do I have to send 1 NEAR?"_
    - User: _"Why is it such a small amount?"_
    - No way to guarantee that the user would return to this window/tab without closing it first.

3. `/send-money`
    - What's the likelihood that the user would have recorded their implicit account ID?
    - UI: `Always double-check your accountID`
        - No reason to put this in the UI. We can't just give disclaimers for every important action in our UI. That doesn't solve anything and doesn't **_truly_** communicate the level of severity.
    - When the user inputs an implicit account ID, the "valid" state of the input just says `Always double check the account ID`. It doesn't let the user know that they've entered a valid Account ID.

4. Account Dashboard
    - User: _"OK so I've now funded the new account, but I'm on the dashboard of a different account. How do I get to the account I've created?"_
        - We don't provide a link or a way for them to navigate to that account, we simply assume that they still have that window open and that they'll return to it.

5. `/create-implicit/fund` 
    - All the same instruction to fund the account is repeated. If the account has been funded, we don't need to show any of this. Should this be a different route?

6. `/recover-with-link`
    - The fact that we use the word restore in this instance is strange.
    - User: _"I haven't received access to this account yet, why do I need to restore it?"_
    - Bug: Success message flashed briefly and disappears without any time to read it.

7. Implicit Account `/profile`
    - Bug: Seed phrase is not enabled
    - User: _"I thought I setup a seed phrase when I first started creating this account. Why aren't any security options enabled?"_

---

My impressions of the current state are that there are quite a few opportunities to refine the UX. While it technically "works", I think it's far from an optimal experience and I'd urge us to spend time working out the kinks outlined above. @mattlockyer @kcole16 I know we've said we want to push this out ASAP. This is 1 full day of UX work for me, then I'm assuming a day to implement those refinements, followed by a final round of testing. This puts this at a Wednesday AM release _at the earliest_. Curious to hear your thoughts.

**Comment by kcole16** [comment]
@corwinharrell I should've been more clear on this! This is very much a temporary solution, as we need something ASAP to enable users to withdraw from exchanges, which is currently nearly impossible for the average user.

We should discuss separately how we want to rework the main account creation flow to incorporate implicit accounts, as all newly created accounts (if the user doesn't have an existing account), should include this step.

**Comment by corwinharrell** [comment]
@kcole16 gotcha, alright so given that context, what out of the above do we think is important enough to address for the first cut?

**Comment by kcole16** [comment]
Key assumptions of this user persona:
- They do not have an existing NEAR account
- They have bought NEAR on an exchange, or plan to do so immediately

This user should not encounter steps `3` and `4`. For users with an existing account, we should target https://github.com/near/near-wallet/issues/823. 

I think step `6` is the most confusing. We designed this workaround with a specific goal of minimizing changes to existing Wallet features, as it was put together essentially on Friday alone, and we wanted to reduce the possibility of any regressions. Hence, reusing the `/recover-with-link` step, which is certainly suboptimal.

Step `7` is also rather confusing. We need to discuss how we want to handle the "inherent" seed phrase that every implicit account has. Technically, the user can delete this after the implicit account is fully created (e.g. it has received a transfer of at least 1 NEAR). It it slightly confusing though, as this same concept is impossible on other blockchains (as the account address is derived from the seed phrase/private key).

**Comment by corwinharrell** [comment]
Cool thanks for the additional context. So with the caveat that we don't want to be adding a ton of new stuff to the wallet to accomplish this, my biggest question is:

Is there any way for us to present messaging to the user to help set context? Example: for #1, when we ask the user to setup the "inherent" seed phrase, can we preface this with a temporary view or message of any kind? It still feels like starting at the seed phrase route is jarring and any amount of context we can afford to give is good.

As for other design work, I'll focus my effort on cleaning up `/create-implicit/fund` as I think some small improvements to the UI there would go a long way for this initial release. cc @mattlockyer

**Comment by corwinharrell** [comment]
@kcole16 @mattlockyer At minimum, let's make the following changes to `fund` to make it more clear that there has been a state change before and after funding:

![fund implicit account](https://user-images.githubusercontent.com/5934188/96495918-8d0dbb80-1216-11eb-9265-084a4f19240b.jpg)

**Comment by mattlockyer** [comment]
https://github.com/near/near-wallet/pull/1059
