### ISSUE TITLE
"Unknown App" when log in with near-cli

### ISSUE THREAD

**Issue by frol** [near/near-wallet#1082]
**Problem**

![image](https://user-images.githubusercontent.com/304265/96975746-49a29e00-14f1-11eb-9f1b-3474a90a6f82.png)

**Expected Behavior**

It should display "NEAR CLI" as passed in the URL (the URL has `?title=NEAR+CLI`

**Steps to reproduce**

1. `env NEAR_ENV=mainnet near login`

**Comment by kcole16** [comment]
@frol We intentionally do not display the title, as that can easily mislead users.

@marcinbodnar We should display something like `NEAR CLI` when the `referrer` is `localhost`, as this is a special case
