### ISSUE TITLE
Disable 2FA

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1086]
### Overview
Many users have setup 2FA, only to realize they later want to: 
-  Use Ledger instead
-  Continue without 2FA
-  Create a new account and withdraw their funds

We should allow users to disable (and re-enable) 2FA after setting it up.

### Acceptance Criteria
- [ ] Users can disable 2FA
  - [ ] User can sign TXs with localStorage key
  - [ ] Recovery keys still work
  - [ ] State stake is reduced to < 5 NEAR
- [ ] Users can re-enable 2FA
  - [ ] Able to choose new verification method

**Comment by mattlockyer** [comment]
Requires logic in near-api-js to support:
https://github.com/near/near-api-js/pull/445

Here is PR for wallet including instructions on how to test with above PR of near-api-js:
https://github.com/near/near-wallet/pull/1107

**Comment by corwinharrell** [comment]
@Patrick1904 we're using the same pattern here as we are for disabling other methods right? Just want to make sure nothing additional is needed since it's marked as needing design.

**Comment by vgrichina** [comment]
> Here is PR for wallet including instructions on how to test with above PR of near-api-js:
> #1107

any reason not to point to specific branch temporarily in `package.json` while still in draft?

**Comment by mattlockyer** [comment]
Issues outstanding:

- potential "bad keys" scenario, blocked on indexer (which probably won't work) and a fix
- rust sdk and contract runtime addition for safer key rotations
