### ISSUE TITLE
Profile page for lockup contract should probably have the information about the locked balance

### ISSUE THREAD

**Issue by frol** [near/near-wallet#1114]
**Problem**

Here is just a random lockup account: https://wallet.near.org/profile/7f86ec378296b21bb616cb2ee9cf0dcdd7b08ca7.lockup.near

![image](https://user-images.githubusercontent.com/304265/97555569-0ba4ee80-19b7-11eb-862d-656b7a529b2e.png)

Wallet profile page only displays the "native" balance of 35 tokens while there are 500+N delegated through the lockup contract (Explorer pulls that information directly from the staking pool by querying the selected staking pool for the lockup contract: https://explorer.mainnet.near.org/accounts/7f86ec378296b21bb616cb2ee9cf0dcdd7b08ca7.lockup.near)

The owner profile displays the locked balance just fine: https://wallet.near.org/profile/nexus.near (though it lacks the link to the lockup contract informing users about its existance :thinking:)

**Expected Behavior**

Display the locked balance on the lockup profile page, include it in the total balance, and inform users about the delegation

**Comment by Patrick1904** [comment]
Closing as this issue is now outdated.
