### ISSUE TITLE
Staking rewards aren't displayed correctly for some 2FA accounts

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1122]
**Problem**
We can't accurately calculate the staking deposit for 2FA accounts, and the workaround is to store this in localStorage. Many users are erasing the localStorage workaround (for various reasons), and then see their staking rewards balance as 0

**Expected Behavior**
Staking rewards should be accurate for all accounts.

**Steps to reproduce**

1. Create an account
2. Enable 2FA
3. Complete the staking flow on `/staking`
4. Clear localStorage
5. Return to the account after 1 epoch

Discussed with @mattlockyer that the best solution involves using Indexer to determine the staking deposits (functionCall arguments) cc @frol and @khorolets

**Comment by frol** [comment]
@mattlockyer could you describe what information one need to accurately compute the value? Is it the amount of tokens user staked/unstaked explicitly to subtract it from the current stake and thus calculate the rewards?

@kcole16 I want to make sure we talk about native staking experience not delegation, right?

**Comment by mattlockyer** [comment]
@frol Yes. We need what you described prior on Slack.

All 2FA accounts staking will have their `deposit,deposit_and_stake` method calls nested in a multisig request which has method name `add_request_and_confirm`

In order to get the correct "rewards" we to query all currently known deposits and then compute `total_staked - known_deposits`

**Comment by kcole16** [comment]
@frol Sorry, I'm referring to delegation. We do not currently have any interface for native staking in the wallet (just generalized TX signing).

**Comment by frol** [comment]
@kcole16 can we rename the staking in Wallet into delegation to avoid ambiguity?

**Comment by mattlockyer** [comment]
@frol @kcole16 IMHO few use the term delegation.

Staking is the superset term, and your role is validator, delegator, ...

**Comment by kcole16** [comment]
@frol Unfortunately, there is too much convergence on "Staking" as the superset term, and users expect to find
