### ISSUE TITLE
Investigate whether some CSS/JS modules can be removed easily

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#114]
E.g. looks like we include semantic-ui CSS which is 600K uncompressed and 90K compressed. We likely don't use most of this stuff.

**Comment by vgrichina** [comment]
@marcinbodnar @Patrick1904 can you take a look and make rough estimate on how long it will take to get rid of semantic-ui?

I assume it should be possible to provide our internal shims for `Grid`, `List`, `Form`, `Image` and other commonly used components to avoid changing much code.

**Comment by marcinbodnar** [comment]
@vgrichina My rough estimate would be about 40-50h. We got rid of a lot of it since we last talk about it, but there are still some problematic elements.

**Comment by vgrichina** [comment]
@marcinbodnar so based on current state looks like following components are still used from semantic-ui-react:

- [ ] Image
- [ ] Button
- [ ] List
- [ ] Form
- [ ] Segment
- [ ] Grid
- [ ] Header
- [ ] Container
- [ ] Divider 
- [ ] Popup
- [ ] Modal
- [ ] Responsive
- [ ] Input

I think we need to determine which of these we want to re-implement in wallet (probably makes sense for most commonly used) and which to just remove altogether (makes sense for least commonly used).

I assume we already made a lot of progress since last discussion about this, right?

**Comment by Patrick1904** [comment]
> @marcinbodnar so based on current state looks like following components are still used from semantic-ui-react:
> 
> * [ ]  Image
> * [ ]  Button
> * [ ]  List
> * [ ]  Form
> * [ ]  Segment
> * [ ]  Grid
> * [ ]  Header
> * [ ]  Container
> * [ ]  Divider
> * [ ]  Popup
> * [ ]  Modal
> * [ ]  Responsive
> * [ ]  Input
> 
> I think we need to determine which of these we want to re-implement in wallet (probably makes sense for most commonly used) and which to just remove altogether (makes sense for least commonly used).
> 
> I assume we already made a lot of progress since last discussion about this, right?

@vgrichina thanks for doing the audit. The Popup is the main component still missing. It'll take a few days to replace/remove the remaining semantic-ui-react stuff. I'll make sure to prioritize this better. @marcinbodnar we can coordinate async.

**Comment by marcinbodnar** [comment]
@Patrick1904 sure, at this moment I have a lot of things on my plate, that are a bit urgent. But I will have that in mind, I can handle it whenever there will be nothing more urgent.

**Comment by Patrick1904** [comment]
> @Patrick1904 sure, at this moment I have a lot of things on my plate, that are a bit urgent. But I will have that in mind, I can handle it whenever there will be nothing more urgent.

Yep totally I'll be able to handle most of this.

**Comment by Patrick1904** [comment]
We made quite a lot of progress on this with the latest nav and dashboard redesign.

There are four main pages left that are built with semantic-ui:
1. https://wallet.testnet.near.org/full-access-keys
2. https://wallet.testnet.near.org/authorized-apps
3. https://wallet.testnet.near.org/sign
4. https://wallet.testnet.near.org/login

In addition, the current footer is built with semantic-ui, and could use a redesign anyway.

cc @corwinharrell

**Comment by jimmy3dita** [comment]
fixed by Replace semantic-ui modal/tooltip components #1525
