### ISSUE TITLE
Enabling seed phrase several times

### ISSUE THREAD

**Issue by ihaid** [near/near-wallet#1145]
**Problem**
I managed to enable seed phrase several times. Sometimes while switching between accounts it shows that the seed phrase is disabled( in fact it is on). I attached a video with this, it is in low quality because I can't upload more than 10MB

**Expected Behavior**
It should be only one seed phrase

**Steps to reproduce**

[seed phrase.mov.zip](https://github.com/near/near-wallet/files/5493751/seed.phrase.mov.zip)
1. Try to switch between accounts several times
2. Account which was previously with enabled seed phrase now has it disabled
3. Enable seed phrase
4. Now there are two seed phrases

**Comment by Patrick1904** [comment]
@ihaid I've tried pretty hard to repro this without success. Is there any other info/tips you can give me to repro?

**Comment by ihaid** [comment]
@Patrick1904 I will try once again to get to this state and then maybe I will have more info.

**Comment by ihaid** [comment]
@Patrick1904 so just go to the https://wallet.testnet.near.org/setup-seed-phrase/<account that already has seed phrase>/phrase and follow the steps
