### ISSUE TITLE
Add "Use Max" to Send

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1154]
### Overview
To make it easier to send the max amount of NEAR from your account, we should add the convenience button "Use Max" to the `/send-money` flow, similar to the one in the `/staking` flow.

### Acceptance Criteria
- [ ] Selecting "Use Max" on `/send-money` inputs `available balance` - 0.35 NEAR into the field
  - [ ] The user is notified that the amount entered leaves 0.35 NEAR in their account for transaction fees
- [ ] If the user enters their full balance, the "Submit" button is disabled, and they receive error text

**Comment by zavodil** [comment]
Check validation code please, we have a problem right now with "Use Max" (find below). Probably it's because of Local 
Culture settings. 
![Clip2net_201124133713](https://user-images.githubusercontent.com/38926321/100089323-2c4b5180-2e5a-11eb-9f1d-9b29c3501f86.png)
