### ISSUE TITLE
Moderately sized address doesn't fit well on Receive page 

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#1155]
<img width="542" alt="Screen Shot 2020-11-10 at 10 36 53 PM" src="https://user-images.githubusercontent.com/126710/98777330-5bb38600-23a5-11eb-9a1e-1d07f94074b9.png">

Layout looks somewhat broken

**Comment by Patrick1904** [comment]
I will fix the line height to 'normalize' this. @corwinharrell it would be great if we could re-design this page completely.
