### ISSUE TITLE
Feature: add non-live validators to the staking list

### ISSUE THREAD

**Issue by jimmy3dita** [near/near-wallet#1160]
As a user, I want to be free to select the validator I'm going to stake.
However, the current interface won't allow me to manually type the name of my favorite validator unless it's already in the active set.

This feature would allow me to type the name of the validator (e.g. `lowfeevalidation.poolv1.near`), so I can stake with them even if they are not yet in the active set.

Acceptance criteria are:
- the application should check if the staking pool is a valid `poolv1.near`
- the validator should be displayed on the staking page normally after I staked to it
- I should be able to stake whether I have liquid tokens, or I have a lockup contract
- I should see a message which says "select from the list below or type the name of the staking pool"

**Comment by Patrick1904** [comment]
@mattlockyer I believe this was shipped with the last release?

**Comment by mattlockyer** [comment]
Yes thanks for flagging
