### ISSUE TITLE
Account creation flow: enabling "Test TX" user pattern

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1165]
### Overview
We've had many instances of users sending multiple TXs to the implicit account during account creation, even after pushing the recent changes to address this.

At this point, I think it's fairly clear we've broken the crypto "best practice" of first sending a test TX to an account, and then sending a larger one. I'm not sure we can address this with further copy and warnings, as we already have pretty substantial messaging around this.

**Comment by corwinharrell** [comment]
https://www.figma.com/file/y1kyUHVr11lUmDkDSzMKU8/Create-New-Account?node-id=91%3A533
