### ISSUE TITLE
Increase 2FA threshold and make 2FA optional during setup

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1168]
### Overview
Many recent users of NEAR have < 100 NEAR in their accounts, and may get less value from locking up 35 NEAR to enable 2FA. These users are still prompted to enable 2FA during account creation if they fund their accounts with more than 36 NEAR. We should increase the threshold for prompting users, and allow them to "Skip" 2FA setup if they desire.

### Acceptance Criteria
- [ ] Users can enable 2FA in their profile if they have more than 35 NEAR
- [ ] Users are only prompted to enable 2FA during setup if they've transferred > 200 NEAR to their account
- [ ] Prompted users can "Skip" setting up 2FA

**Comment by Patrick1904** [comment]
@corwinharrell I added 'needs design' label but let me know if it's just a 'Skip' link button below the main CTA and I'll add that.

**Comment by NoobFromPH** [comment]
Its doesnt make sense for a balance to be not liquid.

2FA are for the wallets security. There nothing to do with the balance?
Just like any other on chain wallet it doesnt require a min. Threshold. Yet they are putting more Security to the wallet without any balance matters.

Now the onchain wallet is more custodial imo

**Comment by corwinharrell** [comment]
@kcole16 how did we arrive at the 200 NEAR number?

**Comment by Patrick1904** [comment]
> @kcole16 how did we arrive at the 200 NEAR number?
> 
> Also, do we think it's worth asking users to confirm their choice to skip/disable 2FA with a message like "Are you sure? 2FA is the bees knees and makes your account more secure `Confirm or Cancel`." cc @Patrick1904

I'd say we don't need the user to confirm skipping 2FA since they can always enable it afterwards.

**Comment by corwinharrell** [comment]
@Patrick1904 cool in that case feel free to just add a skip link underneath the "Continue" button with some margin-top
