### ISSUE TITLE
Add button to Profile to transfer tokens from lockup

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1169]
### Overview
Users with linear lockups (the majority of early users) have requested a way to withdraw unlocked tokens from their lockup accounts without needing to perform another action to trigger it (e.g. send, stake, etc). 

We should provide a button on the `/profile` page to trigger a withdrawal of all unlocked tokens (minus the staked balance), and to destroy the lockup if there are no tokens left in it.

### Acceptance Criteria
- [ ] "Available to Transfer" balance is displayed on /profile (`unlocked balance - total staked - ready to withdraw`)
- [ ] Users can initiate a withdrawal from the `/profile` page by selecting "Transfer to Main Account"
- [ ] If the user has no remaining Locked tokens, clicking "Transfer to Main Account" will also delete the lockup account

**Comment by vgrichina** [comment]
Doesn't feel like we have a lot of people doing it in practice:

```
mainnet2=> select * from (
    select count(*), date_trunc('day', to_timestamp(included_in_block_timestamp / 1000000000)) as day
    from "action_receipt_actions"
    join "receipts" on "receipts".receipt_id = action_receipt_actions.receipt_id
    where action_kind = 'DELETE_ACCOUNT' and receiver_account_id like '%.lockup.near'
    group by date_trunc('day', to_timestamp(included_in_block_timestamp / 1000000000))
) as report order by day;
 count |          day           
-------+------------------------
     1 | 2020-10-18 00:00:00+00
     1 | 2020-10-20 00:00:00+00
     1 | 2020-10-29 00:00:00+00
     1 | 2020-11-02 00:00:00+00
     1 | 2020-11-03 00:00:00+00
     4 | 2020-11-06 00:00:00+00
     2 | 2020-11-07 00:00:00+00
     2 | 2020-11-08 00:00:00+00
     5 | 2020-11-09 00:00:00+00
     4 | 2020-11-10 00:00:00+00
     1 | 2020-11-11 00:00:00+00
     1 | 2020-11-13 00:00:00+00
     1 | 2020-11-14 00:00:00+00
(13 rows)
```

I feel like currently bigger source of confusion is for cases when lockup account cannot be destroyed (i.e. linear release). We show "Unlocked" tokens in profile, but in reality these can be in either main account or lockup account + can be currently staked (which we don't show in Profile at all). If you have tokens staked – there is no clear way to withdraw. Simply adding a button wouldn't work, as you have to unstake first and it isn't immediate action.

**Comment by vgrichina** [comment]
@corwinharrell @kcole16 after thinking on this for a while, it seems to me that we need to have something like "TODO"  (or "Action Required", etc) section on wallet home page. It can include multiple potential items:
- Setup 2FA or Ledger (accounts > 1000 NEAR)
- Setup Ledger (accounts > 10k NEAR)
- Finish account creation (if dropped the ball before)
- Finish claiming linkdrop (if dropped the ball before)
- Claim funds from implicit account (if transferred accidentally)
- Remove unused keys (to cleanup app keys which haven't been used for a while, potentially full access keys as well once we have good tracking of metadata)
- Withdraw from lockup (if there is lockup and all tokens are unstaked and unlocked)
- Unstake to be able to use unlocked tokens (if there is lockup and all tokens are unlocked)

There is a lot of stuff we potentially want users to do and generally cannot rely on them discovering it in general UI.

**Comment by corwinharrell** [comment]
> There is a lot of stuff we potentially want users to do and generally cannot rely on them discovering it in general UI

This is the key observation IMO and I think summarizes the problem well. That being said, in reality this is a large and complex **_set_** of problems, since not all of these actions should be considered, prioritized, handled in the same way, or even necessarily co-located.

I think it's easiest to want to create a sort of "catch all" solution for drawing a user's attention to a set of unresolved actions, but I think it would be worth considering when it might be more appropriate to present some of these recommendations within specific contexts, with different expectations of how the user should respond.

To design the best possible solution for each unresolved action, we should ask ourselves:

- At what point does each unresolved action become most relevant to the user?
- What component of the experience is each action related to? (eg security, lockup, etc...)
- What is the risk/consequence associated with leaving these actions unresolved? How does it impact the user?

I think if we went through and answered these questions for each instance we would find that it doesn't necessarily make sense to prescribe the same solution across the board.

**Comment by vgrichina** [comment]
## At what point does each unresolved action become most relevant to the user?

I think I listed only things which don't have any specific point of relevance. The only exceptions I think are:
- Withdraw from lockup 
- Unstake to be able to use unlocked tokens

which are dramatically more important when you are trying to send transaction and don't have enough tokens. "Withdraw from lockup" already happens automatically in such case, but it's clearly not enough judging by presence of this issue. Note that it's also somewhat too late to offer to Unstake when sending tokens, as you will have to wait more than 1 day for them to become available.

## What component of the experience is each action related to? (eg security, lockup, etc...)

I don't know what is supposed list of separate components of experience. But each of listed actions is already doable in UI (if you know that you need it and how to do it).

So the only goal here is to send user to corresponding UI.

## What is the risk/consequence associated with leaving these actions unresolved? How does it impact the user?

Risk of complete loss of funds:
- Setup 2FA or Ledger (accounts > 1000 NEAR)
- Setup Ledger (accounts > 10k NEAR)
- Finish account creation (if dropped the ball before)
- Finish claiming linkdrop (if dropped the ball before)
- Claim funds from implicit account (if transferred accidentally)
- Remove unused keys (to cleanup app keys which haven't been used for a while, potentially full access keys as well once we have good tracking of metadata)

Annoyance regarding availability of tokens and support questions:
- Withdraw from lockup (if there is lockup and all tokens are unstaked and unlocked)
- Unstake to be able to use unlocked tokens (if there is lockup and all tokens are unlocked)

**Comment by kcole16** [comment]
@vgrichina @corwinharrell I agree with your points re: notifications and potentially usefulness/considerations around experience. I see that as orthogonal to this issue.

> Doesn't feel like we have a lot of people destroying lockup in practice (though probably better to check who has accounts in a state where they can do it):

@vgrichina Sorry, I should've specified that this feature is aimed mostly at users with linear lockups that want to withdraw their currently unlocked funds without attempting to send or stake tokens. The delete functionality is somewhat secondary, though will eventually be useful (and could be immediately useful for the small number of remaining instant liquidity users).

**Comment by vgrichina** [comment]
> Sorry, I should've specified that this feature is aimed mostly at users with linear lockups that want to withdraw their currently unlocked funds without attempting to send or stake tokens.

@kcole16 I think proposed solution won't really help these users then. Like they'll see "Withdraw" button but it won't work because tokens are staked. I'd say that this is main source of confusion for linear lockup users, not just absence of button.

**Comment by vgrichina** [comment]
> I agree with your points re: notifications and potentially usefulness/considerations around experience. I see that as orthogonal to this issue.

moved to https://github.com/near/near-wallet/issues/1182

it is relevant discussion for this issue however, as I think proper solution covering problems that users have in practice (like unlocked tokens still being locked up in staking) requires thinking about more than just withdrawal.

**Comment by corwinharrell** [comment]
@kcole16 Just so I have the right context, what does a linear lockup entail?

**Comment by kcole16** [comment]
@corwinharrell Shifting this down in priority, as @vgrichina and I agreed to work on balances first before continuing on this (as we may be able to clear up most of the user confusion without necessarily implementing this).

**Comment by corwinharrell** [comment]
@Patrick1904 isn't this done?

**Comment by Patrick1904** [comment]
> @Patrick1904 isn't this done?

Shipped in https://github.com/near/near-wallet/pull/1365
