### ISSUE TITLE
Temporarily remove staking "Rewards earned" for users with 2FA

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1177]
### Overview
We need a short term fix for https://github.com/near/near-wallet/issues/1122 until the Indexer is ready. The proposed fix is to remove the "Rewards earned" calculation entirely for users with 2FA enabled. As many new and existing users expect to see this category, we should clearly state that the rewards are unable to be calculated, and offer a way for them to understand why "Learn more".

### Acceptance Criteria
- [ ] "Rewards earned" calculation isn't displayed for users with 2FA enabled
- [ ] Users can click "Learn more" to view a description of why rewards are unavailable

### Notes
**Learn more**
> We are currently unable to calculate rewards when Two-Factor Authentication is enabled. We hope to enable this functionality in the near future. 
>
> In the meantime, you will be able to see your rewards accumulating under "Total staked amount". This balance will grow while your tokens are staked,  as your rewards are automatically re-staked.

**Comment by corwinharrell** [comment]
@kcole16 what's the TLDR for why 2FA is the blocker for displaying rewards? Just wandering if we could incorporate something brief as the "why" part of the error description.

**Comment by kcole16** [comment]
@corwinharrell We can't accurately calculate the amount of NEAR 2FA users staked initially (since we don't have access to the function call arguments for 2FA without the Indexer), which blocks us from calculating the rewards (total staked - initial stake).

**Comment by corwinharrell** [comment]
Done with design. Lmk if there's any feedback @Patrick1904 @kcole16:

![Unable to display rewards](https://user-images.githubusercontent.com/5934188/99989666-e40c3080-2d80-11eb-834f-b15d0667f9ee.gif)

Figma: https://www.figma.com/file/8RoBuGilnfstTDfTufN5To/Unable-to-Display-Rewards?node-id=0%3A1

**Comment by corwinharrell** [comment]
Also, I know it's not a part of this issues, but you'll see that I've been experimenting a little with removing the actual account names for the staking selector, in favor of labels that delineate `Wallet` vs `Lockup Contract`. This is just an experiment, and doesn't need to be implemented. I was just curious to see how this might feel. It was a suggestion made by @Patrick1904 in #1178

**Comment by Patrick1904** [comment]
@corwinharrell this looks good to me. I will implement this today so that we get this out ASAP if you're ok with this @kcole16

**Comment by kcole16** [comment]
Looks good!
