### ISSUE TITLE
Remove app title from url params for authorize app / login 

### ISSUE THREAD

**Issue by janedegtiareva** [near/near-wallet#118]
This should be queried from contract metadata once contract metadata is implemented.

**Comment by bowenwang1996** [comment]
So contract metadata should have title as well? How do we expect the developer to specify what the title is?

**Comment by janedegtiareva** [comment]
> So contract metadata should have title as well? How do we expect the developer to specify what the title is?

I think that the real world use case that matches this well is publishing an app on playstore, so we can learn a lot by how they are doing this. https://themanifest.com/app-development/how-publish-app-google-play-step-step-guide -- see product details section. 
TLDR: this is data that needs to be specified by developer and saved with the contract. The tricky bit is that title is (ideally at some point in the future) localizable.

**Comment by bowenwang1996** [comment]
Ideally we should figure out how to do this sooner than later. While it is possible to upgrade the format of metadata in the future, it is better if we can avoid the pain of doing so.

**Comment by janedegtiareva** [comment]
> Ideally we should figure out how to do this sooner than later. While it is possible to upgrade the format of metadata in the future, it is better if we can avoid the pain of doing so.

I'll add a comment on the metadata NEP. Do we need any more info? I think that the requirements are pretty clear, it's just a matter of how to implement.

**Comment by bowenwang1996** [comment]
So it is not clear to me where the developer should/can put that information. This will affect how it is implemented.

**Comment by vgrichina** [comment]
We can for example require developer to implement certain contract methods and call them from metadata method. E.g. require developer to implement `title` and `iconUrl` methods

**Comment by bowenwang1996** [comment]
I see. Also I think it doesn't have to be required. It should be the developer's responsibility to make sure that the contract is be convenient to use.

**Comment by kcole16** [comment]
@vgrichina We display the referrer when `appTitle` is blank/not specified, correct?

Given the recent discussion around access key vulnerabilities, it's likely worth making this the default whether appTitle exists or not.

cc @SkidanovAlex @ilblackdragon @Patrick1904 @marcinbodnar

**Comment by marcinbodnar** [comment]
@kcole16 On `/login` we show `appTitle` always.

**Comment by kcole16** [comment]
@marcinbodnar Ah, is it `/sign` that I'm thinking of?

**Comment by marcinbodnar** [comment]
@kcole16 Yes.

**Comment by vgrichina** [comment]
Yeah, we need to change `/login` to show referrer like `/sign` does.

**Comment by jimmy3dita** [comment]
closed by https://github.com/near/near-wallet/pull/725
