### ISSUE TITLE
Add disclaimer to 2FA flow explaining that x NEAR will be locked up

### ISSUE THREAD

**Issue by Patrick1904** [near/near-wallet#1195]
It's not clear that x NEAR will be locked up once the user enabled 2FA. It's especially problematic since you're currently not able to disable 2FA. We should show a disclaimer explaining to the user that x NEAR will be locked up until they disable 2FA.

**Comment by Patrick1904** [comment]
@kcole16 @corwinharrell any thoughts on this? It seems it would help avoid a lot of confusion.

**Comment by vgrichina** [comment]
<img width="610" alt="Screen Shot 2020-11-23 at 9 20 06 PM" src="https://user-images.githubusercontent.com/126710/100051931-bb605700-2dd1-11eb-8ee7-890d93b75bd7.png">

Feel like this intro need to include info about 35 NEAR being locked up. Also I feel like font is too bold to read (looks like heading), so maybe something can be adjusted.

**Comment by corwinharrell** [comment]
@vgrichina @Patrick1904 is the 35N requirement outlined anywhere such as in our docs? It would be nice to not have to go into depth in the UI itself, but to make a brief statement, and then point to somewhere with a more elaborate technical explanation.

**Comment by corwinharrell** [comment]
<img width="1107" alt="Screen Shot 2020-11-25 at 12 23 51 PM" src="https://user-images.githubusercontent.com/5934188/100261657-1781c300-2f19-11eb-9d36-c642fa30fac2.png">

cc @Patrick1904

**Comment by Patrick1904** [comment]
> @vgrichina @Patrick1904 is the 35N requirement outlined anywhere such as in our docs? It would be nice to not have to go into depth in the UI itself, but to make a brief statement, and then point to somewhere with a more elaborate technical explanation.

@corwinharrell yes we have this page that explains contract storage requirements: https://docs.near.org/docs/concepts/storage

The design looks good to me 👍
