### ISSUE TITLE
Authorized apps clickable but nothing happens on click

### ISSUE THREAD

**Issue by ihaid** [near/near-wallet#1216]
**Problem**
When you move the mouse over the Authorized apps field it is shown that the field is clickable but nothing happens on click
**Expected Behavior**
Should be an action?

**Steps to reproduce**

1. Authorize some app on your account
2. Go to the Summary tab
3. Mouse over the Authorized apps field
![image](https://user-images.githubusercontent.com/38665104/100127124-739c0700-2e87-11eb-9f48-204d1aa2c4ce.png)

**Comment by toddpierpoint** [comment]
This appears to work fine for me. When I click on the an authorized app, the details for that app display on the right side of the page and allow me to deauthorize it.
<img width="1228" alt="Screen Shot 2020-11-24 at 11 11 21 AM" src="https://user-images.githubusercontent.com/73570885/100128482-f308e680-2e45-11eb-9e3a-a71e2c7e5477.png">

**Comment by ihaid** [comment]
@toddpierpoint I guess you did it on /authorized-apps page but I did it on the main page in the Summary section

**Comment by toddpierpoint** [comment]
@ihaid Oh, OK. I see now. Yes, it does appear that there needs to be an action. I suggest navigating to the Authorized Apps page with the selected app details visible.
