### ISSUE TITLE
2FA shows as disabled when actually it’s enabled

### ISSUE THREAD

**Issue by ihaid** [near/near-wallet#1227]
**Problem**
2FA shows as disabled when actually it’s enabled

**Expected Behavior**
2FA should be enabled

**Steps to reproduce**

1. Create an account using seed phrase
2. Enable 2FA
3. Go to _/profile_ page
4. Click on enable phone recovery method
5. Enter your phone number
6. Enter the SMS code
7. Then you **don't** need to confirm with 2FA code, click "Cancel" button instead
8. Go to /profile page
9. 2FA shows as disabled

**Comment by Patrick1904** [comment]
@ihaid, I'm trying to repro this without much success. These are the steps:
1. Created an account w/ seed phrase
2. Enabled 2FA (I used email)
3. Started adding phone/SMS as a recovery method
4. Once the 2FA modal shows up confirm enabling the recovery method  -> click 'cancel'
5. Navigate to `/profile`
6. 2FA still shows as active

Are you still able to repro using the steps above?

**Comment by ihaid** [comment]
@Patrick1904 Seems like it’s fixed, I can’t repro.
