### ISSUE TITLE
Resend 2FA code button is not working

### ISSUE THREAD

**Issue by ihaid** [near/near-wallet#1248]
**Problem**
Nothing happens when you click the "resend" button on 2fa verify modal window
![image](https://user-images.githubusercontent.com/38665104/100765754-858a2680-3400-11eb-86bb-7fc99a161068.png)

**Expected Behavior**
Code must be sent again 

**Steps to reproduce**

1. Create an account
2. Enable 2FA
3. Go to /send-money
4. Send some Near
5. Wait for the first confirmation
6. Click on the "resend" button

**Comment by vgrichina** [comment]
@ihaid please make sure the fix works ok

**Comment by ihaid** [comment]
> @ihaid please make sure the fix works ok

@vgrichina I still see this issue on testnet
