### ISSUE TITLE
FB single sign on integration

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#125]
## Story

As a USER who has FB account, I want to use it to login to the wallet so I can start using apps without any pre-work friction from my side.

## Acceptance Criteria

- [ ] Wallet has endpoint to log in with FB creating corresponding NEAR account in process.
- [ ] User can choose to connect FB during regular account creation process
- [ ] FB account can be used to recover NEAR account

## Assets

- Mockup: 

TBD

## NOTES

- Likely best to implement through Passport.js (http://www.passportjs.org/packages/passport-facebook/) so that other types of SSO are also easy to plug in

**Comment by Patrick1904** [comment]
Closing as issue is not under consideration anymore
