### ISSUE TITLE
Calculate lockup balances from contract state

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1253]
### Overview
Lockup balances are incorrect prior to users calling `check_transfer_vote` which only occurs prior to a balance-changing action (transfer, staking). This is confusing to users, who's balances are incorrect for at least some period of time.

Per @ilblackdragon 
> Don’t rely on get_ methods in lockup, parse the state of the contract to get and compute the state. There is full implementation with all the needed hacks in [account-lookup](https://github.com/near/account-lookup/blob/master/script.js).
>
> Methods only works if you have already called the “check_transfer” on the lockup. Which most people have not - hence all of the people’s balances are off.
>
> If there balances are off - they will never call “check_transfers” in the first place, because wallet only calls it when there is something to transfer.

**Comment by vgrichina** [comment]
Fixed here https://github.com/near/near-wallet/pull/1225
