### ISSUE TITLE
Display more transaction info on /sign screen

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1259]
### Overview
The `/sign` screen currently only highlights the amount of NEAR being transferred and the referrer URL of the app requesting the transaction. Users must select "More Info" to see further information about the actions in the transaction. 

Given the majority of our users (both now and for the foreseeable future) are somewhat crypto familiar, we should expose more information upfront about the unique transaction.

**Relevant Information**
- NEAR deposit (if any)
- Actions included in the transaction
- If functionCall
  - Account name (that contains contract being called)
  - Function name
  - Arguments
- Maximum gas cost (in NEAR)

A few transaction scenarios (with legacy decisions re: information to display) can be found here: https://docs.google.com/document/d/18nx139P612h3DPDEb5EtbSCZ-YtLWHGErXLMEVePMOQ/edit

**Comment by Patrick1904** [comment]
Closing as issue is outdated
