### ISSUE TITLE
staking route should reset when switching accounts

### ISSUE THREAD

**Issue by mattlockyer** [near/near-wallet#1272]
**Problem**
I'm looking at a validator page and I switch accounts. I have no stake with the validator, so I stay on the page but see the old data and then eventually the data disappears (after redux update).

**Expected Behavior**
I get redirected to /staking when switching accounts.

**Steps to reproduce**

1. Go to a specific validator page
2. Switch accounts

**Comment by Patrick1904** [comment]
@corwinharrell any thoughts on the proposed UX change?

**Comment by corwinharrell** [comment]
@mattlockyer is this something that someone has given us feedback about? I want to understand the motivation here better. In the future, validator profiles will be more rich with validator data. Consider the following scenario:

1. I'm on account A (whatever account I was on when I used the wallet last)
2. I start looking through validators
3. I see one that I'd like to stake with, but decide I want to stake with a different account.
4. I switch account using the switcher, and then get kicked out to the beginning of the flow, and have to go find that validator again

**Comment by mattlockyer** [comment]
Ya that's fair.

@Patrick1904 we may want to reset the redux state the moment you switch and loading of validators starts.

Otherwise you're sitting there looking at data from prev account.
