### ISSUE TITLE
Add a message on the page with seed phrase that user will need it

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1278]
On the screen with securing your seed phrase - it would be good to have a message saying that you will need to confirm that you have it on the next screen.

People usually would store such seed phrase (in 1password, piece of paper, whatever) somewhere and close it before clicking proceed... And then realize they need to get the phrase again.

**Comment by kcole16** [comment]
This might happen to non-crypto users, but is highly unlikely for anyone that has setup a seed phrase before (as confirming is the standard). 

Certainly open to revisiting the copy in general, cc @corwinharrell @jimmy3dita

**Comment by corwinharrell** [comment]
I'm in favor of adding something like "You'll need to verify your seed phrase before creating your account."

**Comment by Patrick1904** [comment]
Closing as issue is outdated
