### ISSUE TITLE
Inactive button continue on Setup Phrase

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1279]
**Problem**
Button "Continue" is inactive on Setup Phrase on BetaNet Wallet

<img width="526" alt="Screen Shot 2020-12-10 at 1 06 32 AM" src="https://user-images.githubusercontent.com/175486/101750595-16f23c00-3a84-11eb-9f99-db505d7cce48.png">

**Expected Behavior**
Button is active.

**Steps to reproduce**

1. Create new account on BetaNet already having an account
2. Choose Seed Phrase
3. For some reason "Continue" is inactive

This is not happening all the time, but have happened.
Refresh helped.

**Comment by kcole16** [comment]
Possibly related? https://github.com/near/near-wallet/pull/1265#issuecomment-742827036
