### ISSUE TITLE
Weird formatting in details about validator

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1305]
**Problem**
See screenshot

<img width="897" alt="Screen Shot 2020-12-21 at 7 15 39 PM" src="https://user-images.githubusercontent.com/175486/102844798-0e253280-43c1-11eb-9540-8a8af6f604dc.png">

**Expected Behavior**
Not having these visual issues

**Steps to reproduce**

1. Open wallet with an account
2. Go to staking
3. Select specific pool with longer name - https://wallet.near.org/staking/buildlinks.poolv1.near

**Comment by Patrick1904** [comment]
@corwinharrell do you have any ideas how we should format the account ID in these situations? I don't really see how we'd get around it.

**Comment by corwinharrell** [comment]
@Patrick1904 a couple easy wins to start:

1. I don't think it needs to be so big. In the original design for the delegation flow, this type is 24px. On prod it's currently 28. That would give us a bit more breathing room. Once we have figured out a sensical way to concatenate long addresses, I think this is our best bet.

2. I know we removed the `@` for usernames. Is there a reason that persists here?

**Comment by Patrick1904** [comment]
> @Patrick1904 a couple easy wins to start:
> 
> 1. I don't think it needs to be so big. In the original design for the delegation flow, this type is 24px. On prod it's currently 28. That would give us a bit more breathing room. Once we have figured out a sensical way to concatenate long addresses, I think this is our best bet.
> 2. I know we removed the `@` for usernames. Is there a reason that persists here?

Thank you! It's an H1 so font size is dynamic like all other H1's. I adjusted so that 24px is the min vs 28px.
