### ISSUE TITLE
Refreshing page resets staking with a lockup

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1309]
Steps to reproduce
1. Open account with lockup
2. Go to staking and select lockup
3. Select specific pool
4. Go into staking with that pool
5. Refresh the page

Observe that available balance changes from lockup balance to normal account balance.

**Comment by Patrick1904** [comment]
@marcinbodnar can we please persist account selection for page refresh and if the user navigates to let's say profile, and then back to staking again. We can use localStorage.
