### ISSUE TITLE
TX signing isn't working

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1324]
**Problem**
The /sign page is displaying a blank screen with the following error in console
```
Uncaught (in promise) TypeError: Cannot read property 'deserialize' of undefined
    at sign.js:11
    at Array.map (<anonymous>)
    at PARSE_TRANSACTIONS_TO_SIGN (sign.js:11)
    at handleAction.js:35
    at index.js:26
    at Array.reduce (<anonymous>)
    at index.js:25
    at handleActions.js:25
```

**Expected Behavior**
The /sign page should display the transaction, and allow the user to confirm or deny

**Steps to reproduce**

1. Go to berryclub.io
2. Login 
3. Click "Buy 25 for 1 NEAR"

**Comment by vgrichina** [comment]
Reverted release for now https://github.com/near/near-wallet/pull/1325

**Comment by vgrichina** [comment]
Fixed in latest near-api-js as well https://github.com/near/near-api-js/releases/tag/v0.36.2

So going to re-publish release

**Comment by vgrichina** [comment]
Fixed in https://github.com/near/near-wallet/pull/1326
