### ISSUE TITLE
Newly created accounts with Ledger won't recover sometimes

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1330]
**Note**
This might be due to me using the same Ledger to create and fund multiple accounts (using the same funding address), at least one of which I kept as just the implicit account (never created the .near account)

**Problem**
After creating and funding a new account with Ledger as the only key, account recovery doesn't work.

**Expected Behavior**
Account recovery should work.

**Steps to reproduce**

1. Go to /create and choose Ledger as the recovery method
2. Fund the account with 1.1 NEAR
3. Finish creating the account (deleting the funding account)
4. Try to login in incognito: https://wallet.near.org/sign-in-ledger
5. Observe error

Error message is showing that the implicit account doesn't exist (which is true).

In below message, `c006...05824` was the funding account.

```
Uncaught (in promise) Error: [-32000] Server error: account c00604c6988da8767e178347a613f063e4f2d3eb4b72ce3aa285d213ccd05824 does not exist while viewing
    at d.sendJsonRpc (json-rpc-provider.js:163)
    at async d.query (json-rpc-provider.js:70)
    at async p.fetchState (account.js:50)
    at async p.state (account.js:58)
```

**Comment by mattlockyer** [comment]
@kcole16 looks like it's erroring on the implicit account that once had the ledger key.

It finds the implicit and the named account (I'm assuming) during the indexer call, then throws and never gets to try the named account.

**Comment by kcole16** [comment]
@marcinbodnar Can you take a look at this?
