### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1364]
### Overview
Currently, we only capture redux actions and the data included in them. This gives us an incomplete and in some cases misleading picture of user behavior. 

We need to accomplish the following:
- Define what we want to track
- Decide on an implementation strategy
- Determine a process for adding further tracking as we add features

### What to track
- Active users (in aggregate)
- Successful account creations
- Unsuccessful account creations
   - Dropoff points
- Recovery methods added/removed
- 2FA enabled/disabled

### Implementation
Frontend-only? High block rate on Mixpanel

### Process
TODO

**Comment by jimmy3dita** [comment]
## Define what we want to track
I'll start with my list. Keeping it limited, as I want to get quickly to some basic discovery, and then extend where we see opportunity.

**1. Actions**
number of `create account` clicks <- same as `successful` + `unsuccessful account creations`
number of `funded accounts` <- same as successful account creations
number of `staking` accounts
 **2. Visits**
number of returning users <- sessions already "logged in"
list of visits by referral links
**3. Quality**
number of JS console errors
number of active Zendesk tickets
number of solved Zendesk tickets
**4. General KPIs**
total accounts
total NEAR managed

## Implementation strategy
I would separate frontend, backend, and on-chain sources of this data. Some of them may be redundant (e.g., we can measure some metrics either via frontend and backend) so we have to prioritize by resources needed (and their availability).

## Process
1. agree on the goals for these metrics epic (enable discovery? Improve Decision-making? I'd love to hear from the whole team)
2. approve a minimum set of metrics and "freeze" them (leaving the nices to have in a backlog or roadmap)
3. implementation assessment on each, to weight feasibility and dev impact
4. write the acceptance criteria and test/validation methodology
5. start the development, test/validate the collected metrics, fix/improve
6. goto 2

Thoughts?

**Comment by jimmy3dita** [comment]
I want to extend the list above with another class:
**5. Segmentation**
Sessions by screen dimension
IP location
Traffic source
