### ISSUE TITLE
User wants to find applications on NEAR

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1371]
## Story

As a USER who has NEAR, I want to find applications on NEAR to play / spend / buy / sell.

## Acceptance Criteria

- [ ] Find list current of applications with some understanding of their usage
- [ ] See which ones user have already used / logged in
- [ ] See in which ones have assets (tokens, NFTs, LP position, etc)

## Suggestion

Simplest version of this is to put a banner on main page that links to few of the NEAR apps.
If user wants to see more, they can click to expand - which for now can go to https://awesomenear.com or later can be list inside the wallet's app.

**Comment by jimmy3dita** [comment]
Related to https://github.com/near/near-wallet-roadmap/issues/7

**Comment by corwinharrell** [comment]
Completed as a part of https://github.com/near/near-wallet-roadmap/issues/18?
