### ISSUE TITLE
Links to transactions on Explorer right in Wallet Activity

### ISSUE THREAD

**Issue by almal** [near/near-wallet#1389]
## Story

As a USER who logged to wallet.near.org, I want able to click on transactions listed under Activity so I can see the transaction details on explorer.

![image](https://user-images.githubusercontent.com/15792799/105906990-679d0480-5ff2-11eb-90f8-5513c228c02e.png)

![image](https://user-images.githubusercontent.com/15792799/105907213-b8acf880-5ff2-11eb-9f17-8bcd35406895.png)

## Acceptance Criteria

- [ ] Links added
- [ ] Mobile ok
- [ ] Tested

## Unhappy Path
Have to go to View All
![image](https://user-images.githubusercontent.com/15792799/105906921-4fc58080-5ff2-11eb-82cc-d739b29cc7ad.png)

## Assets

- Mockup: 

## NOTES

-

**Comment by Patrick1904** [comment]
Closing as issue is outdated
