### ISSUE TITLE
Make "Withdraw" more obvious in /staking

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1393]
### Overview
We receive questions from users about how to finish the "Unstake" process fairly regularly. The "Withdraw" button is currently located on the validator detail page, a detail these users miss their first time trying to unstake and withdraw.

We should consider how to make this process more clear, especially for first time stakers.

**Comment by jimmy3dita** [comment]
@corwinharrell want to circle back on this one, given that we are already working on #1538.
Maybe worth merging with the most recent one

**Comment by corwinharrell** [comment]
@jimmy3dita I totally agree. The implementation here is virtually identical to unstake with the exception of copy emphasizing withdrawal. As soon as it's decide where this fits into the roadmap, I think it makes sense to implement the same improvements for withdrawal as we are with unstake.
