### ISSUE TITLE
Improve loading time of Profile page

### ISSUE THREAD

**Issue by marcinbodnar** [near/near-wallet#1394]
Improve loading time by adding functionality where `In staking pools` details will be fetched only when the user clicks on the `In staking pools` field - user will see loader and after fetching the data will be displayed.

**Comment by jimmy3dita** [comment]
@marcinbodnar added this card to the current sprint, feel free to drag/drop it in the relative column

**Comment by marcinbodnar** [comment]
@jimmy3dita thanks, done.
