### ISSUE TITLE
Measure the success of the new onboarding flow

### ISSUE THREAD

**Issue by jimmy3dita** [near/near-wallet#1411]
Check if our changes to the onboarding journey were successful:
How we can further improve it?
What are the yet unsolved issues?

**Comment by jimmy3dita** [comment]
Evaluate if changing the account ID is commonly adopted

**Comment by corwinharrell** [comment]
We are still encountering issues with the current funding flow, and need to address this as a part of https://github.com/near/near-wallet/issues/1453. Closing this with the intent to measure the success of the next iteration.
