### ISSUE TITLE
Default Ledger account can be deleted during account creation

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1428]
**Problem**
Creating a new account with a Ledger leads to the deletion of the default HD path address, which may have been in use. This is usually recoverable, but in a rare (hard to reproduce) case can lead to catastrophic loss of NEAR.

**Expected Behavior**
The default account should not be deleted, especially if it already exists on-chain.

**Steps to reproduce**

1. Create a new account with the default HD path via CLI (`44'/397'/0'/0'/1'`) 
2. Send NEAR to it
3. Create a new account in Wallet and choose Ledger
4. Observe that the first account is deleted

**Comment by vgrichina** [comment]
Looks like underlying reason for this problem is that `create_account` doesn't fail transaction on failure:
https://explorer.near.org/transactions/7MuUQdmto8LJyY5pKMimWUcL5UK57UN2tVD3mPMfaF8N

**Comment by kcole16** [comment]
Closing as @vgrichina fixed in #1435 (right?)

**Comment by vgrichina** [comment]
yeah, the important part has been fixed – account only gets removed if is completely equivalent to the one that's not created yet
