### ISSUE TITLE
Requirements for the account name is not fully described

### ISSUE THREAD

**Issue by volovyk-s** [near/near-wallet#1442]
**Problem**
The creation of an account with the Account ID that has a length of more than 64 characters is not possible and it is not clarified in the hint. The current hint is:

Your account ID can contain any of the following:
Lowercase characters (a-z)
Digits (0-9)
Characters (_-) can be used as separators

Your account ID CANNOT contain:
Characters "@" or "."

**Expected Behavior**
Users should know the maximum length of the Account ID (rules can be found here: https://docs.near.org/docs/concepts/account#account-id-rules). Also, it should be clarified, that acc length consists of acc name and network suffix. 

**Steps to reproduce**
1. Go to https://wallet.testnet.near.org/create
2.  Enter Account ID with 65 or more characters

**Comment by brookeperkins** [comment]
I'd take the following approach: 
1. Rename the translation keys to be more descriptive https://github.com/near/near-wallet/blob/7be53589264513200c6df9416cdbe06ae99d46f5/src/translations/en.global.json#L582-L587
2. Add a list item (currently called "note") describing the length limit restriction https://github.com/near/near-wallet/blob/7be53589264513200c6df9416cdbe06ae99d46f5/src/components/common/AccountNote.js#L27
3. Ensure that changes are reflected across all languages

If this sounds good, I'll go ahead and make a PR!
