### ISSUE TITLE
Use protocol config RPC endpoint to get storage costs

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1466]
### Overview
This [PR](https://github.com/near/nearcore/pull/3919) adds an RPC endpoint that returns the latest storage cost. Given that the storage cost will decrease 10x on March 1, we should replace the `EXPERIMENTAL_genesis_config` call with this one to remain future proof.

**Comment by Patrick1904** [comment]
@vgrichina @bowenwang1996 - account storage cost is currently calculated in `near-api-js` here: https://github.com/near/near-api-js/blob/master/src/account.ts#L451

What updates do we need to do in order to get the latest storage cost?

**Comment by bowenwang1996** [comment]
I believe @frol is taking care of the change of near-api-js side. Essentially, we need to replace `EXPERIMENTAL_genesis_config` with `EXPERIMENTAL_protocol_config`.

**Comment by frol** [comment]
FYI https://github.com/near/near-api-js/pull/508

**Comment by Patrick1904** [comment]
> FYI [near/near-api-js#508](https://github.com/near/near-api-js/pull/508)

@frol do we need to make any changes on the wallet side for this or is `near-api-js` enough?

**Comment by frol** [comment]
@Patrick1904 you will just need to replace `experimental_genesisConfig` with `experimental_protocolConfig`. There we will need another round of near-api-js release once the `experimental_protocolConfig` API gets on mainnet (it is not there yet), but Wallet will only need to update the near-api-js version

**Comment by Patrick1904** [comment]
Closing as it's outdated now.
