### ISSUE TITLE
"Import existing account" doesn't work on betanet

### ISSUE THREAD

**Issue by frankbraun** [near/near-wallet#1510]
**Problem**

If I want to import an existing account on **betanet** via https://wallet.betanet.near.org/
it fails with the following error message after I put in my seed phrase:

```
Error
Sorry an error has occurred. You may want to try again.
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```
This breaks:

`env NEAR_ENV=betanet near login`

**Expected Behavior**

"Import existing account" via "Seed Phrase Recovery" should work.

**Steps to reproduce**

1. Create a wallet on https://wallet.betanet.near.org/create and write down seed phrase.
2. Clear cookies.
3. Click "Import existing account" on https://wallet.betanet.near.org/
4. Click "Recover account".
5. Put in seed phrase.

**Comment by vgrichina** [comment]
Unfortunately this won't work unless we have indexer for beta
net @khorolets @frol

**Comment by Patrick1904** [comment]
Closing as issue is outdated
