### ISSUE TITLE
Success message when cancel transaction 

### ISSUE THREAD

**Issue by ihaid** [near/near-wallet#1514]
**Problem**
![image](https://user-images.githubusercontent.com/38665104/109847915-60ec5780-7c58-11eb-84fc-0533960b5baa.png)

**Expected Behavior**
The message "You have successfully sent..." should be removed

**Steps to reproduce**

1. Go to an account with enabled 2fa
2. Go to /send, enter an amount to send, and submit
3. Click "Cancel" on the 2fa window when shows up

**Comment by Patrick1904** [comment]
Fixed in: https://github.com/near/near-wallet/pull/1524
