### ISSUE TITLE
Improve Usability of "Unstake" UX

### ISSUE THREAD

**Issue by corwinharrell** [near/near-wallet#1538]
### Problem Summary
In the current implementation of Staking, users have found that the ability to `Unstake` their tokens is difficult to find, since users must first navigate to their current validator's profile in order to `Unstake`.

### Intended Outcome
Users should be able to initiate the `Unstake` action directly from the staking dashboard. Once they indicate that they would like to `Unstake`, they can then confirm the action without having to navigate to the validator's profile.

### How will it work?
1. From /staking, user clicks `Unstake` next to `Total Amount Staked`.
2. If the user is staking with multiple validators, the user must choose the validator from which they want to Unstake.
3. User inputs the amount they wish to Unstake, and clicks Submit
4. User confirms the action via a confirmation dialogue.
5. User returns to dashboard, where their staking figures are updated.

### Designs
**Figma:** https://www.figma.com/file/UGjVUoDOLrAsRbJw6OosyS/1538-Improve-Unstake-UX?node-id=1%3A2597

**Comment by corwinharrell** [comment]
@jimmy3dita I just want to confirm that currently users can only stake with a single validator? Do we know when this might change?

**Comment by corwinharrell** [comment]
@Patrick1904 As long as our staking UI is limited to a single validator, this should be as simple as adding an "Unstake" button to the dashboard next to "Total Amount Staked". Feel free to go ahead and add this. I don't think a mockup is necessary.

As soon as we enable staking with multiple validators, this experience will need to be expanded to allow the user to select the validator from which they would like to unstake, before indicating an amount.

One small request: Let's knock the 's' off of `Your Current Validators`

**Comment by Patrick1904** [comment]
> @Patrick1904 As long as our staking UI is limited to a single validator, this should be as simple as adding an "Unstake" button to the dashboard next to "Total Amount Staked". Feel free to go ahead and add this. I don't think a mockup is necessary.
> 
> As soon as we enable staking with multiple validators, this experience will need to be expanded to allow the user to select the validator from which they would like to unstake, before indicating an amount.
> 
> One small request: Let's knock the 's' off of `Your Current Validators`

@corwinharrell the single validator restriction only applies when you're staking from a lockup account. You're able to stake with unlimited number of validators when you stake from your main account. We can still add the 'unstake' button for lockup case, but might be confusing with inconsistent UX?

**Comment by corwinharrell** [comment]
@Patrick1904 got it in that case we'll need a slightly different UX. Thanks for clarifying. Will update this issue with the designs shortly.

**Comment by Patrick1904** [comment]
> [Design is complete](https://www.figma.com/file/UGjVUoDOLrAsRbJw6OosyS/1538-Improve-Unstake-UX?node-id=1%3A2597) and ready for review.

@corwinharrell looks great. Everything is clear.

**Comment by Patrick1904** [comment]
Note: Will start on this once https://github.com/near/near-wallet/pull/1556 is merged
