### ISSUE TITLE
Always specify how many tokens are locked to enable 2FA

### ISSUE THREAD

**Issue by jimmy3dita** [near/near-wallet#1541]
## Story

As a USER who wants to enable 2FA, I want to know the number of NEAR tokens that will be locked for this function, so I don't block 36 tokens without knowing in advance.

## Acceptance Criteria

- [ ] The text in the 2FA box shows an alert even when the user holds more than the minimum required tokens
- [ ] The text at the link https://wallet.testnet.near.org/enable-two-factor reflects the 10x lower locked amount (`3.6` instead of `36`)
- [x] ~~Correctly reduce the requirement of `3.6` near tokens to the new lower requirements, which we set to `5` near tokens~~

## How it is today:

<img width="606" alt="Schermata 2021-03-11 alle 17 06 30" src="https://user-images.githubusercontent.com/6222429/110876492-6a934200-828c-11eb-86f5-afc72bba8d14.png">
<img width="606" alt="Schermata 2021-03-11 alle 17 02 49" src="https://user-images.githubusercontent.com/6222429/110876495-6cf59c00-828c-11eb-9da1-adf57cf79cbb.png">

## How it should be:

A message which says "Enabling the 2FA smart contract locks 3.6 NEAR tokens from your available balance, making them unspendable"

## Unhappy path*:

1. As a user who holds 50 tokens, I enable the 2FA feature and I find only after I completed the process that my new spendable balance got from 49 to 15 NEAR tokens
2. As a user who wants to disable their 2FA, I have to open a ticket since there's no component in the UI to remove this feature, such that I can get back my 36 tokens!!!

*The description above is pre [1.18.0](https://github.com/near/nearcore/releases/tag/1.18.0). Now the locked funds will be 10x less, or `3.6` near.

**Comment by jimmy3dita** [comment]
Alernative solution:

Change the color of the alert box from blue to red, and put it right on top of "continue".

## How it is today:

<img width="606" alt="Schermata 2021-03-11 alle 17 14 40" src="https://user-images.githubusercontent.com/6222429/110876964-6287d200-828d-11eb-84ab-481b95ba9f5a.png">

## How it should be:
open to discuss the red color (the red is completely random, should use the standard css) but it's important it stays between the input and the `continue` button

<img width="606" alt="Schermata 2021-03-11 alle 17 22 15" src="https://user-images.githubusercontent.com/6222429/110877502-5ea87f80-828e-11eb-9571-f120c0e27824.png">

**Comment by jimmy3dita** [comment]
cc @corwinharrell and then @Patrick1904 for a quick ack or further review

**Comment by jimmy3dita** [comment]
Also, with the nearcore release [1.18.0](https://github.com/near/nearcore/releases/tag/1.18.0) all accounts reduced 10x their storage costs, so we should also reduce `36` to a lower number (proposing `5`).
Updating the acceptance criteria above to reflect this change

**Comment by jimmy3dita** [comment]
Updated the acceptance criteria to reflect [1.18.0](https://github.com/near/nearcore/releases/tag/1.18.0) reduced storage fees: the messaging is now saying `3.6` instead of `36`.

Also, let's keep the 36 near as the minimum amount to enable 2FA until we merge #1344

**Comment by corwinharrell** [comment]
@jimmy3dita What are the motivations behind these changes? Have users expressed surprise and/or frustration around the 2FA storage cost? Just looking for a little additional context.

**Comment by jimmy3dita** [comment]
> @jimmy3dita What are the motivations behind these changes? Have users expressed surprise and/or frustration around the 2FA storage cost? How frequently? Just looking for a little additional context.

Frustration mostly from not being able to spend/transfer all funds, which is made worse by:
- no ability to disable 2FA
- no way to know it in advance (both the storage cost AND the impossibility to get rid of it)

Overall, the 10x reduction to storage costs improved the sentiment, however we still receive random messages via chat&support channels asking why the available balance is lower, and how they can get their money back (hint: they can't yet).
Impact: not too large, as we still require 36 tokens in the available balance to enable 2FA

**Comment by corwinharrell** [comment]
Rather than plastering messaging everywhere that 2FA is mentioned, I'd prefer that we just ask the user to acknowledge the storage costs before they enable 2FA. This way, we ensure that the user understands the requirement before they activate the feature, and we eliminate the need to repeat ourselves unnecessarily. Let's leave the panel on the account page as is (no message), and add an explicit acknowledgement requirement in order for the user to proceed.

I don't like to use color treatments that imply errors (red), so let's just opt for a "caution" treatment using our warning colors for the alert at the top of the 2FA page. We also don't need to relocate it, since the messaging is reflected in the acknowledgment.

<img width="1150" alt="Screen Shot 2021-04-08 at 11 25 17 AM" src="https://user-images.githubusercontent.com/5934188/114054182-9f7bc000-985d-11eb-936e-c0a0eb935dc9.png">

@MaximusHaximus just a note: Ignore the fact that the above design for the method selection is slightly different from what exists in prod atm. This design is where we are headed in the future, and we can add the acknowledgement to the current design without making changes to the design of the method selection for now. cc @Patrick1904

**Comment by jimmy3dita** [comment]
This is awesome! @MaximusHaximus @Patrick1904 let's specify the right amount: it is 3.6 NEAR tokens, not 35.

**Comment by Patrick1904** [comment]
> This is awesome! @MaximusHaximus @Patrick1904 let's specify the right amount: it is 3.6 NEAR tokens, not 35.

@jimmy3dita the current locked amount (35) is defined as an env variable and can be updated right now from Netlify. @vgrichina can you please update it when you have a chance?

**Comment by jimmy3dita** [comment]
> > This is awesome! @MaximusHaximus @Patrick1904 let's specify the right amount: it is 3.6 NEAR tokens, not 35.
> 
> @jimmy3dita the current locked amount (35) is defined as an env variable and can be updated right now from Netlify. @vgrichina can you please update it when you have a chance?

Is this only for the balances, or also in the displayed amounts on the page?

**Comment by jimmy3dita** [comment]
@Patrick1904 Followup from today's planning:
- [ ] change the env variable in the frontend from 36 to 4 NEAR (netlify.toml)
- [ ] add the confirmation checkbox to the 2FA activation page
