### ISSUE TITLE
Update /login (pre-approval) copy

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#155]
We've updated the copy to simplify the experience for the user, and added a "More Information" tab to provide additional detail, if desired. 

# Acceptance Criteria
- [x] The App Name is displayed
- [x] If the app is requesting an access key (limited), user is displayed "This does not allow the app to transfer any tokens"
- [x] If the app is requesting a full access key, user is displayed "This provides access to your entire NEAR balance. Proceed with caution!"
- [x] "More Information" button leads to a separate page with the following details
  - [x] Contract ID
     - [x] contractId
  - [ ] Methods
     - [ ] List of method names
  - [ ] Transaction Allowance
     - [ ] Gas Fee Allowance: X NEAR

# Assets
Designs
- [Main Screen (limited access)](https://projects.invisionapp.com/share/SKQKQ6B4PYU#/screens/377987985)
- [Main Screen (full access)](https://drive.google.com/open?id=1qeB3EeSAIySkH5pMDjU5_uR-XveO8_P6)
- [More Information Screen](https://projects.invisionapp.com/share/SKQKQ6B4PYU#/screens/387685893)

**Comment by vgrichina** [comment]
> Read and write to the NEAR blockchain

that's not true though. App is only getting permission to call specific contract.

**Comment by marcinbodnar** [comment]
@vgrichina could you please check if shell login info is accurate, I can change it as well if necessary:
https://wallet.nearprotocol.com/login/?title=NEAR+Shell&public_key=5RibhyW1b5j1GqBQDZhV5uZHsgvx2FLkbNKok48j8o4S

**Comment by vgrichina** [comment]
@marcinbodnar that's probably question to @kcole16 as well. The items there are accurate, but don't cover all. Like e.g. you can also access every contract which isn't obvious. And "Deploy Contracts" really only applies to your account for example.

However layout-wise such fixes are needed:
> Does not allow:
column needs to be removed as it's empty

> Contract:
needs to be removed as it's empty too

**Comment by marcinbodnar** [comment]
@vgrichina ok, I will handle fixes. So what would the final text sounds for these two situations @kcole16 ?

**Comment by kcole16** [comment]
@vgrichina @marcinbodnar Updated from

> Read and write to the NEAR blockchain 

to

> Read and write to this app's smart contract on the NEAR blockchain

**Comment by kcole16** [comment]
@marcinbodnar For the near-shell case, let's add

> Call functions on any smart contract

**Comment by vgrichina** [comment]
@kcole16 there are really more things than that though. Like e.g. you can also stake. Or unstake. Or add/remove keys. Basically everything that is available as actions in tx.

**Comment by kcole16** [comment]
@vgrichina Fair, I should've gone through the commands! Think this covers it (all of the actions)

@marcinbodnar Let's add

> Stake and unstake NEAR tokens

> Create and delete access keys

**Comment by Patrick1904** [comment]
Closing as issue is outdated
