### ISSUE TITLE
Success message on failed transaction 

### ISSUE THREAD

**Issue by ihaid** [near/near-wallet#1553]
**Problem**
![image](https://user-images.githubusercontent.com/38665104/111483328-60b28880-873d-11eb-9a46-8fe95fbda6f9.png)

**Steps to reproduce**

1.  Go to an account with Ledger enabled
2. Go to /staking
3. Select validator, enter an amount click confirm, and on the step where you need to confirm with Ledger wait for ~30sec

**Comment by Patrick1904** [comment]
Fixed in: https://github.com/near/near-wallet/pull/1540
