### ISSUE TITLE
Update "Authorized App" display

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#157]
To make the "Authorized Apps" display more similar to the [designs](https://projects.invisionapp.com/share/9ES2D82U8GB#/screens/368389840) using the data we already have:

Remove
- contractId label (keep the value)
- publicKey label and value

Change
- allowance/amount to "Fee Allowance: <0.1% of N Balance"

Add
- default app icon (seems to be implemented but hidden?)

[Screenshot](https://drive.google.com/file/d/14MayM4vPC3fIP_OVOQgTyieEngYSzSer/view?usp=sharing)

**Comment by marcinbodnar** [comment]
@kcole16 it's ready in #161 
default app icon was implemented, but since we don't have real icons for apps yet, a recent decision was to hide it.

**Comment by marcinbodnar** [comment]
@kcole16 I misunderstood amount line, now should be fine
