### ISSUE TITLE
Add new route for `/activity` in order to accommodate robust token lists on `/index`

### ISSUE THREAD

**Issue by corwinharrell** [near/near-wallet#1576]
### Problem

In the current implementation of the display of fungible token balances, the user's NEAR balance, fungible token balances, and account activity are all co-located in the same view in the wallet dashboard. While this is not an issue when the user has little to no fungible token balances, there are a couple flaws:

1. The current design doesn't do a great job of accommodating longer lists of fungible tokens. As the list grows beyond 3-4, we currently don't have any sort of pagination or a dedicated route to display a more robust list of tokens. This would primarily effect DeFi and Bridge users who may have a larger quantity of fungible tokens displayed in the wallet.

2. The current design superficially imposes a limitation on the number of items we display in the activity feed. Because of limited real-estate on the wallet dashboard view, we cut off the feed and force the user to navigate to the explorer rather than allowing the user to scroll or navigate to view more of their transaction history. This is suboptimal as it encourages the user to leave the wallet.

### Intended Outcome

Users should be able to view the entirety of their fungible token balance list, whether on the primary wallet view or from within a new route. Since displaying a long list of fungible tokens would compete for real estate with the activity feed on the dashboard, and since the activity feed is already superficially restricted due to limited real estate, it makes sense to create a new route to accommodate longer lists for both.

### What are we doing about it?

The two most sensical options for solving for this problem are as follows:

1. Create a new route for the complete fungible token list for users that have more robust lists. 
2. Create a new route for `/activity` to accommodate a more robust activity feed, and to allow the full fungible tokens list to be displayed on the wallet dashboard.

My proposal is for Option 2. Since we will likely be adding a new route regardless, it makes sense to create a separation of concerns and to relocate the activity feed to its own route. This way, the function of the wallet view is asset management, while the function of the activity view would be to stay informed about transaction state and history.

**Additionally, this change sets the stage for us to accommodate non-fungible tokens in 2021.** Displaying NFTs in the wallet will require even more real estate than fungible tokens, and it makes sense for asset management to be inclusive of both fungible and non-fungible tokens.

The proposed design changes are represented in the mockups below:

<img width="1258" alt="Screen Shot 2021-03-24 at 9 50 05 AM" src="https://user-images.githubusercontent.com/5934188/112325046-bc26ce00-8c89-11eb-9e1a-99adf9379779.png">

**This change would represent the final change to the information architecture of the wallet before we are ready to implement the redesign of the wallet navigation as proposed in Q4 of 2020**

@Patrick1904 the [Figma link](https://www.figma.com/file/MOMOnm89esHGC4PMKDBEDw/Fungible-Token-Balances?node-id=0%3A1) for this is the same as fungible token balances.

**Comment by vgrichina** [comment]
I have few concerns:
- I don't think it is "Priority 0", at most this is P1 as nobody has this problem in prod yet. Even when we switch to show all the tokens you interacted with (I plan to do this one ASAP) most users not gonna have a lot of non-zero balances right now.
- We need to make sure that this page is discoverable (e.g. user needs to get there after sending transaction, etc). Maybe Receive screen should also show recent activity as well so that you immediately can see what you received. Clicking on main token balance / custom token balances should probably redirect to the activity list as well
- Seems like for desktop / iPad formats there might be enough space to show both tokens and activity side to side, so i think we should use this.

**Comment by vgrichina** [comment]
Looks like we currently show success screen after sending a payment which requires another confirmation from user. Seems like redirecting right to /activity would be a better option.

**Comment by corwinharrell** [comment]
> I don't think it is "Priority 0", at most this is P1 as nobody has this problem in prod yet. Even when we switch to show all the tokens you interacted with (I plan to do this one ASAP) most users not gonna have a lot of non-zero balances right now.

Yeah no problem to switch to P1. It was made out to sound semi-urgent but I realize I've been too liberal with this.

> We need to make sure that this page is discoverable (e.g. user needs to get there after sending transaction, etc). Maybe Receive screen should also show recent activity as well so that you immediately can see what you received. Clicking on main token balance / custom token balances should probably redirect to the activity list as well

> Seems like for desktop / iPad formats there might be enough space to show both tokens and activity side to side, so i think we should use this.

Yeah I'm not in opposition to this and have actually explored this. @Patrick1904 how would you feel about keeping a small "Recent Transactions" list on the dashboard (most recent 5 / two columns on desktop), but still adding a full / complete feed as a separate route that the "Recent transactions" can link to (via "View More"), in addition to being added as a primary nav item? This way we solve for both discoverability and scalability. @vgrichina I'll think about UX following transactions like send/receive.

**Comment by Patrick1904** [comment]
> Yeah I'm not in opposition to this and have actually explored this. @Patrick1904 how would you feel about keeping a small "Recent Transactions" list on the dashboard (most recent 5 / two columns on desktop), but still adding a full / complete feed as a separate route that the "Recent transactions" can link to (via "View More"), in addition to being added as a primary nav item? This way we solve for both discoverability and scalability. @vgrichina I'll think about UX following transactions like send/receive.

Yep I'm all for keeping 'recent transactions' on the dashboard with 'view all' to separate route. @corwinharrell how do you envision the two column layout to look?

**Comment by jimmy3dita** [comment]
From my recent bridge marketing notes, we will have a list of tokens that can be sorted by "liquidity": similarly to the size of validators, certain tokens will have more tokens than others - and may offer valuable returns to users who lend their near (via AMM and yield farming).

In my opinion, makes sense to prioritize as follows:
1. all non-zero balance tokens 
2. if less than 4, fill up with the top tokens by market cap*
3. add the possibility via `+` button to track manually any additional zero-balance token

Use case for 1 is obvious
Use case for 2 is to invite the user to explore the other "stars" in the ecosystem
Use case for 3 is enable users to follow early on other tokens

Overall, these users may want to see the balance to check if and how much is growing, e.g. via AMM fees or other things that fungible tokens offer to them (e.g. farming bananas) 

* I'm wondering if we want to put a smaller number that shows the user the total balance of the contract he's looking at

**Comment by vgrichina** [comment]
@jimmy3dita there is no need for 3 except for airdroped tokens. We know which tokens you are interacting with and are surfacing them in https://github.com/near/near-wallet/pull/1579

There is also whitelist but the logic is slightly different from 4 (whitelisted tokens always show up).

**Comment by vgrichina** [comment]
> *I'm wondering if we want to put a smaller number that shows the user the total balance of the contract they're looking at

do you mean like total supply? Probably worth to have this info in explorer

**Comment by corwinharrell** [comment]
**NOTE: Revising this work slightly to take into account feedback and a more iterative implementation.**

While there is still be a need to introduce a separate route for a more robust activity feed in order to allow users to track their history of transactions without having to leave the wallet, I want to tweak our approach to implementing this to be a bit more iterative.

Ultimately, the activity feed on the dashboard and the feed on its own route will be serving two different functions:

1. "Recent Activity" will remain on the dashboard and will be limited to a small set of your most recent transactions. This will generally be used to verify the state and success of your most recently executed transactions.
2. The dedicated activity view will include a longer history of your account activity, and will serve to enable users to review their history without having to leave the wallet to navigate to the explorer.

Since adding a new route and addressing optimizations to accommodate a more robust activity feed would increase scope, I'm proposing the following:

1. Retain the "Recent Activity" list on the dashboard, and adopt a multicolumn layout to accommodate a longer list of fungible tokens (the original goal of this issue) (as per @vgrichina's suggestion.)
2. Create a separate issue for adding a new route for a full activity feed, so we can address the needs of the fungible tokens list first and create a separation of concerns.

@Patrick1904 has already completed the necessary changes for the dashboard layout here: https://github.com/near/near-wallet/pull/1582
