### ISSUE TITLE
Account Creation: Improve Funding UX w/ Temporary Faucet

### ISSUE THREAD

**Issue by corwinharrell** [near/near-wallet#1577]
### Problem

We continue to receive feedback that the current implementation of funding new wallet accounts is extremely inhibitive for new users, and often results in users getting lost during the process, since funding an account almost never occurs within a short timeframe. The most frequent problems we see are:

1. Users send multiple transactions to the implicit funding address, which results in those funds being obscured by the fact that they are then owned by the implicit address and not the Account ID which the user created. Users then don't understand how to recover these fund from their implicit address.

2. Users exit the account creation flow before completing the funding step, and then have to figure out how to recover both their implicit and named accounts, usually by contacting support. The wallet engineering team has attempted to address this with more explicit messaging during the funding flow, but this has largely been unsuccessful.

### Intended Outcome

There has been a [lengthy discussion](https://github.com/near/near-wallet/issues/1453) around this set of problems, ultimately resulting in the proposal to implement a temporary faucet which reserves the Account ID on behalf of the user for a set period of time during which the user must fund their account by depositing funds **directly into their named account**.

In general everyone is in favor of this solution, since it eliminates the need to force users to interact with multiple accounts (implicit/funding & named) during the account creation flow, which is root of the majority of the issues we've seen.

### What are we doing about it?

1. Implement a temporary faucet to temporarily fund a new user's chosen Account ID for a set time period

2. During this period, the user must fund their account by depositing funds directly into the named account.

3. If the user fails to fund their account within the `reservation period`, the account is released, and the user must start over.

4. If the user successfully fund their new account within the `reservation period`, their account is created successfully, and they can then access their account. There is no need for them to worry about a funding/implicit address.

5. If the user abandons the account creation flow during the funding step (ie exits the wallet), they can resume their progress by simply recovering their named account with their chosen recovery method. We will make some alterations to the language used in the recovery flow to indicate that it can also be used to resume the account creation process.

With these changes, the new flow for creating a new account resembles the following:

<img width="1442" alt="Screen Shot 2021-03-24 at 11 53 45 AM" src="https://user-images.githubusercontent.com/5934188/112341204-99031b00-8c97-11eb-9cb5-23412d700b4f.png">

**Comment by corwinharrell** [comment]
cc @ilblackdragon @kcole16 @jimmy3dita

**Comment by jimmy3dita** [comment]
I agree and approve this proposal.
I think we can close #1453, to discuss the execution details here.

@corwinharrell I'm ready to put here some acceptance criteria and user stories, do you agree with this course of action?
@vgrichina do you see any limitation to get to the UI presented above?

**Comment by corwinharrell** [comment]
yeah I'm happy with this and think it's a big improvement on the existing flow. Will defer to @vgrichina incase there's anything that might be unaccounted for.

**Comment by kcole16** [comment]
Flow looks good, though I believe the plan is to have a permanent funding account that users will fund (like `fund-wallet.near`, rather than sending NEAR directly to their own account. cc @vgrichina

**Comment by jimmy3dita** [comment]
> Flow looks good, though I believe the implementation plan is to have a permanent funding account that users will fund (like `fund-wallet.near`), rather than sending NEAR directly to their own account. cc @vgrichina for feasibility

Given how exchanges work, the ideal flow is to fund the account itself and eventually sign a batch transaction to refund the faucet.
From what I understand, many users fund their implicit account twice because exchanges (like Binance) allow them to set the withdrawal address once, and automatically transfer funds later on. Ideally, we want that they set the named account already in the exchange, and keep it unchanged

**Comment by kcole16** [comment]
That is certainly the ideal flow, though it will require a proper faucet where we actually pay for the cost to create these accounts (like the one for Ethereum holders). 

The "faucet" we'd previously discussed was more of a fixed account for users to transfer to (`fundaccount.near`), rather than needing to have a unique, temporary "funding account".

**Comment by corwinharrell** [comment]
@kcole16 @vgrichina Can I get a confirmation on the exact funding address implementation here? Then we can move this forward and prepare it for dev.

**Comment by vgrichina** [comment]
> @kcole16 @vgrichina Can I get a confirmation on the exact funding address implementation here? Then we can move this forward and prepare it for dev.

not sure what is exact question, so gonna dump my thoughts in general

funding address gonna be the desired `.near` account name with such caveats:
- generally it helps if user knows that they need to fund before we create account in faucet and show them the funding option (as we want to minimise the number of accounts that get created but not claimed)
- we need to think of the case where user abandons the flow after funding. In that case we need to allow user finishing the flow when they either return back to wallet in the same browser or use corresponding recovery option. 

general comments on flow:
- funding screen should also have option to Fund with card when available
- not sure how useful is QR code in this context, that would suggest you are funding with a NEAR wallet from other device? which seems a bit unusual for this use case (like why not create account directly – let's just finish up https://github.com/near/near-wallet/pull/1424 for this). Do exchanges typically provide a way to scan a code for NEAR?

**Comment by corwinharrell** [comment]
> we need to think of the case where user abandons the flow after funding. In that case we need to allow user finishing the flow when they either return back to wallet in the same browser or use corresponding recovery option.

@vgrichina any reason we shouldn't use the standard recovery flow perhaps with some different wording? (eg "Continue Account Creation")

> funding screen should also have option to Fund with card when available

yep will add moonpay

> not sure how useful is QR code in this context, that would suggest you are funding with a NEAR wallet from other device?

It's common for other wallets (eg Trust) and exchanges (eg Coinbase) on mobile to allow scanning of QR code during a send/receive flow. I'm thinking ahead a bit here, but if/when NEAR is on Coinbase for example, would be nice to just be able to scan the QR code with my phone when sending NEAR to my new Account ID in order to fund it. Thoughts?

**Comment by jimmy3dita** [comment]
RE: QR Code
I support the utility of the QR code. 

It may be lower if we switch to named accounts, but it's still very helpful when (as a user) I'm trying to fund the wallet on another computer or smartphone (e.g. a friend). Sending crypto via QR codes was the norm in the last 10 years, and it's also very common in Asian markets.
I'm not aware of technical debt or key changes in the codebase, so I have no clear visibility on the effort

**Comment by ilblackdragon** [comment]
How about we combine here something from #1453, and on the screen of "Reserve Account ID" we allow user to choose "Or signup with random account name NOW". This way for people who want to be anonymous or don't want to reserve name for period of time - they can just choose the implicit route.

**Comment by jimmy3dita** [comment]
> How about we combine here something from #1453, and on the screen of "Reserve Account ID" we allow user to choose "Or signup with random account name NOW". This way for people who want to be anonymous or don't want to reserve name for period of time - they can just choose the implicit route.

I think @corwinharrell has the last word on this one.

I support implicit accounts, but I need more visibility on how many things are going to change, and if we end up in a domino effect where other features and UIs need to be reworked

**Comment by corwinharrell** [comment]
I think there's an opportunity to break this out and approach this as a 3-pronged conversation/epic:

1. Temporary Faucet: Improve funding flow for new accounts (this issue)
2. Fund New Account w/ Existing Account (https://github.com/near/near-wallet/issues/823 and https://github.com/near/near-wallet/pull/1424)
3. Implicit Account Support to enable creation of accounts without the need for an initial deposit

Each of these efforts can be executed independently. While related, they are not dependencies of one another. #3 is something that has most recently been discussed w/ Flux, and feels like the only remaining component that still has some resistance/opposition.

My recommendation for moving forward:

- Continue with the implementation of #1
- Continue with design for #2
- Facilitate more discussion around #3. I also think #3 warrants some light research to concretely define what the core problems and opportunities are here.

I'm going to create an Epic that summarizes all of the above, and will also port in some of the conversation that has been had with Flux around the desire to support creating accounts without the need for an initial deposit. I'll ping the relevant parties once that has been completed.

**Comment by corwinharrell** [comment]
The team has decided that in the short-term, rather than trying to design and implement the changes to the on-boarding UX as laid out above, we will be implementing a faucet similar to Testnet, to automatically fund new accounts. This circumvents the need for a funding step, and therefore renders the following issues irrelevant:

- https://github.com/near/near-wallet/issues/823
- https://github.com/near/near-wallet/pull/1424
- https://github.com/near/near-wallet/issues/1577

After monitoring the use of this new faucet over the coming months in order to observe how it impacts account creation and how resistant it is to the spamming of account creation, we may reconsider if it makes sense to revisit the above. @jimmy3dita I think at this point it may make sense to archive this issue and create a new one outlining the necessary work for the new faucet implementation, as outline in https://github.com/near/near-wallet/discussions/1659

**Comment by jimmy3dita** [comment]
@MaximusHaximus feel free to open a new issue with the scoped down acceptance/testing criteria, so we can archive this work and re-open it when the smart contract and the rest of the work by @vgrichina is ready

**Comment by stefanopepe** [comment]
we are continuing here: https://github.com/near/near-wallet/issues/1752
