### ISSUE TITLE
Wallet makes ton of not needed calls to rpc when signing a tx

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1591]
**Problem**
Currently there are 25 RPC requests on opening signing tx / logining in. Including there are duplicate requests.
This means that page is very slow to load, especially in China.

**Expected Behavior**
2-3 RPC requests tops.
Ideally button is ready to press right away, and loading is async.

**Steps to reproduce**

1. Login with NEAR from any app
2. Observe 25 rpc.mainnet.near.org requests in Networking page. Everything from requesting the target contract couple of times, account itself 10 times,  protocol config 2 times (cache it for at least a day in local storage?), staking deposits and specific amounts of stake in each pool, etc.

**Comment by vgrichina** [comment]
I believe big part of this is solved by https://github.com/near/near-wallet/pull/1583

**Comment by jimmy3dita** [comment]
Closing this one, happy to work together on a new version with a smaller scope
