### ISSUE TITLE
Every screen shows a different balance

### ISSUE THREAD

**Issue by chadoh** [near/near-wallet#1603]
**Problem**

I have no idea what my actual balance is

<img width="683" alt="near wallet  send  balance - 0 00995" src="https://user-images.githubusercontent.com/221614/113287637-d67d2f00-92bb-11eb-822a-44b737fbc456.png">
<img width="683" alt="near wallet main balance - 2 50162" src="https://user-images.githubusercontent.com/221614/113287640-d715c580-92bb-11eb-9703-308c86bb8ef8.png">
<img width="683" alt="near wallet tx approval balance - 0 35995" src="https://user-images.githubusercontent.com/221614/113287642-d7ae5c00-92bb-11eb-8935-d5313a56123f.png">

**Expected Behavior**

NEAR Wallet should tell me a consistent number for my balance

**Steps to reproduce**

Not totally sure what state an account needs to be in to get these sort of mismatched numbers. I've been using this account on testnet for about a year.

**Comment by chadoh** [comment]
I found this when trying to reproduce a bug that showed up when my balance was less than 0.01N on mainnet, and could not, because NEAR Wallet doesn't allow me to send the last 0.35N. This is a separate but related issue.

**Comment by jimmy3dita** [comment]
@marcinbodnar @Patrick1904 let's put it in the queue for the next sprint

**Comment by Patrick1904** [comment]
@chadoh @jimmy3dita balances are contextual and differ depending on what action you're trying to perform. There are total balances, available balances, etc. We should probably adjust the `/sign` page 'available balance' to take into account a minimum reserved amount, like the send/stake pages though.

**Comment by Patrick1904** [comment]
Will be adding a balance breakdown called 'Available to transfer' to the `/sign` page - similar to what we have on send/stake/unstake.

<img width="560" alt="Screen Shot 2021-04-07 at 2 41 50 PM" src="https://user-images.githubusercontent.com/24921205/113938383-65ec7b80-97af-11eb-995c-4ddf28a4eb54.png">

**Comment by mikedotexe** [comment]
I also am getting confused by this, but this one seems like an actual error. The main landing page says I have over 3,000 Ⓝ 

<img width="1106" alt="Screen Shot 2021-04-10 at 8 59 08 PM" src="https://user-images.githubusercontent.com/1042667/114291884-b4b04480-9a3f-11eb-9b6e-334ac09555fa.png">

But I have 118 according to NEAR CLI (and hence the RPC and so on)

<img width="943" alt="Screen Shot 2021-04-10 at 9 00 14 PM" src="https://user-images.githubusercontent.com/1042667/114291914-d27da980-9a3f-11eb-8149-b5e867b7033d.png">

**Comment by Patrick1904** [comment]
> I also am getting confused by this, but this one seems like an actual error. The main landing page says I have over 3,000 Ⓝ


@mikedotexe I can see how this could be confusing. The NEAR balance shown on the dashboard is the total account balance, not just NEAR that's available to send/stake. The balance includes locked, staked balance, etc. To see actual 'available' balance, that's displayed on under 'available' on the profile/account pace (`/profile`)

**Comment by mikedotexe** [comment]
> > I also am getting confused by this, but this one seems like an actual error. The main landing page says I have over 3,000 Ⓝ
> 
> @mikedotexe I can see how this could be confusing. The NEAR balance shown on the dashboard is the total account balance, not just NEAR that's available to send/stake. The balance includes locked, staked balance, etc. To see actual 'available' balance, that's displayed on under 'available' on the profile/account page (`/profile`)

Ah gotcha thanks, I think I legit forgot I had 3k NEAR in that account and thought the number was out of nowhere. My fault.

**Comment by chadoh** [comment]
> I can see how this could be confusing. The NEAR balance shown on the dashboard is the total account balance, not just NEAR that's available to send/stake. The balance includes locked, staked balance, etc. To see actual 'available' balance, that's displayed on under 'available' on the profile/account page (/profile)

I question whether a design that causes confusion and requires explanation is the best design. I understand that this is a tricky design challenge, given the many different kinds of balances, and I don't have a suggestion off-hand. But I think we should probably show "available" here on the dashboard as well, since I probably want to know how much I can actually use, not how much I could potentially reclaim (via unstaking, deleting storage, whatever).
