### ISSUE TITLE
Fix inconsistent support links

### ISSUE THREAD

**Issue by jimmy3dita** [near/near-wallet#1604]
**Problem**
As a user who needs technical support, I can click `help` in the top menu, or `need help?` in the bottom right corner.
While the top link is linking to `https://nearhelp.zendesk.com/` the bottom right sends the user to `https://near.chat/`.
As a result, we have a duplication of tickets that start from Discord, and requires the user to open a ticket on Zendesk.

<img width="1079" alt="Top Help Link" src="https://user-images.githubusercontent.com/6222429/113324830-6aef8d80-92cc-11eb-98ba-17c5f04527ac.png">

<img width="1079" alt="Bottom Right Link" src="https://user-images.githubusercontent.com/6222429/113324883-7d69c700-92cc-11eb-87d1-20600d09bb42.png">

**Expected Behavior**
Help users understand why and when they might open a ticket instead of asking on Discord.
Ideally, the `help` class is always leading the user to the support center (Zendesk with FAQs and email communication), while the `questions` class is always leading to Discord.

Essentially, the solution is changing the words in the bottom right corner from `Need Help?` to something like `Questions?`, and measure if the number of duplicated support requests decreases.

**Steps to reproduce**

1. click `help` in the top navigation menu to land on Zendesk
2. click `join discord` to land in the Discord chat (which requires the additional step to find and open the `wallet-support` channel)

**Comment by Patrick1904** [comment]
@jimmy3dita AFAIU the only change requested is to change the footer support link from 'Need Help?' to 'Questions?'

Can you please confirm and I'll fix that.
