### ISSUE TITLE
NEP-141 Balance is truncated and showing 0

### ISSUE THREAD

**Issue by mfornet** [near/near-wallet#1623]
**Problem**
I transferred 0.002 YFI ERC20 tokens from Ethereum to Near using the bridge. However, when I go the wallet, it shows that I have `0.00` nYFI tokens.

![photo_2021-04-07 23 01 26](https://user-images.githubusercontent.com/28708963/113937895-20a16b80-97fa-11eb-9de2-5ba22c1aa8a1.jpeg)

**Expected Behavior**

I expect to see my balance with some more decimals in this particular case. While there is almost no difference between `1000.001` and `1000`, there is a huge difference between `0.002` and `0.00`. 

Maybe we can also have a tooltip with the exact amount (all decimals displayed), for users having large balances but moving small amounts.

**Steps to reproduce**

Get an account with less than 0.001 balance of any NEP-141 tokens, and check the displayed balance in the wallet.

**Comment by mfornet** [comment]
the rule of thumb I thought was: 

display either two decimals, 
or at least two more significant digits different from 0

for example

* 1234.56789 => 1234.57 (rounded up to two decimals)

* 0.0000123456789 => 0.000012 (display at least to more significant decimals different from zero)

* 123000.00000456789 => 123000.00 (truncate to two decimals in this case)

**Comment by Patrick1904** [comment]
I suggest that we considering showing `< 0.00001` for small values, like we currently do for small NEAR values

**Comment by marcinbodnar** [comment]
We can also show real value on hover using title tag - we already do that for a small amount of Near.

**Comment by Patrick1904** [comment]
> We can also show real value on hover using title tag - we already do that for a small amount of Near.

Yes that'd be great!
