### ISSUE TITLE
nUSDC does not show up in token list after using Ref Finance

### ISSUE THREAD

**Issue by Patrick1904** [near/near-wallet#1625]
**Problem**
nUSDC token balance does not show up in the NEAR Wallet

**Expected Behavior**
nUSDC token balance shows up

**Steps to reproduce**

1. Acquire 1.00 nUSDC on Ref Finance (https://app.ref.finance/)
2. Withdraw 1.00 nUSDC (under the 'Portfolio' tab)
3. Query the token contract using CLI, e.g. `NEAR_ENV=mainnet near view a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.factory.bridge.near ft_balance_of '{"account_id": "johndoe.near"}'` - don't forget to change the account ID
4. Confirm that above query returns the correct value
5. Check the NEAR Wallet and expect nUSDC to not be listed in the token list

**Comment by jimmy3dita** [comment]
Adding also @vgrichina as it may involve the contract helper

**Comment by marcinbodnar** [comment]
I guess it's missing `a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.factory.bridge.near ft_balance_of` in `TOKEN_CONTRACTS` env variable @vgrichina ?

**Comment by jimmy3dita** [comment]
This seems a duplicate to #1648 .
I tried myself, and I solved by:
1. withdraw 1 nUSDC from ref.finance
2. open "deposit"
3. select nUSDC from the dropdown menu
4. deposit 1 nUSDC to ref.finance
5. refresh the wallet dashboard

**Comment by Patrick1904** [comment]
Thanks @jimmy3dita. Closing this one.
