### ISSUE TITLE
Allow apps to pass redirect urls during linkdrop

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1641]
### Overview
As an application user, I want to sign up for an account on Flux, receive a linkdrop to create a NEAR account, and be redirected back to Flux immediately after creation, so I can start predicting the NEAR price.

We have several outstanding, high priority requests to re-implement the redirect after account creation (used to work). Specifically, we should allow apps to pass a `redirectUrl` into a linkdrop link, and redirect rather than sending the user to `/profile`.

### Acceptance Criteria
- [ ] The `/create_account` route accepts a `redirectUrl` parameter
- [ ] After account creation, users are redirected to `redirectUrl`
- [ ] The user's account name is passed as an argument to the redirect URL (`accountId`)

**Comment by jimmy3dita** [comment]
@Patrick1904 @marcinbodnar we need this live within April 22nd, with at least 5 days for testing.
I need your feedback on the resources needed to implement this feature

**Comment by marcinbodnar** [comment]
@Patrick1904 you were working on linkdrop lately (i think), want to handle it?

**Comment by Patrick1904** [comment]
@jimmy3dita @marcinbodnar sure I'm finishing up https://github.com/near/near-wallet/issues/1538 right now so will fix https://github.com/near/near-wallet/issues/1641 after.

ETA for https://github.com/near/near-wallet/issues/1641 is Wednesday the 14th. That should give us enough time to test.
