### ISSUE TITLE
Unlocked and transferrable balance is negative

### ISSUE THREAD

**Issue by think-in-universe** [near/near-wallet#1645]
**Problem**

One user with around 80K NEAR reported an issue that the unlocked and transferrable balance is negative (-1,072.9366 NEAR when checked previously, https://wallet.near.org/profile/08d9a90ffd033fdf966c0a04c1feb70627d1a5e7e9328b13ee6a90c322e58bd8). 

So he cannot transfer NEAR as he usually does previously: https://explorer.near.org/accounts/08d9a90ffd033fdf966c0a04c1feb70627d1a5e7e9328b13ee6a90c322e58bd8

**Expected Behavior**

The unlocked balance should be non-negative. 

**Steps to reproduce**

1. Open the wallet profile: https://wallet.near.org/profile/08d9a90ffd033fdf966c0a04c1feb70627d1a5e7e9328b13ee6a90c322e58bd8
2. The unlocked and transferrable balances are negative (-626.9454 NEAR) at the moment. 

![image](https://user-images.githubusercontent.com/46699230/114420836-43ab9100-9be7-11eb-9959-0b09dda3a279.png)

**Comment by jimmy3dita** [comment]
Escalating to Priority 1: prevents the user from spending their balance.
We have an open ticket on Zendesk too

**Comment by vgrichina** [comment]
@jimmy3dita @marcinbodnar according to information from @evgenykuzyakov the source of problem is a bug in earlier version of lockup contract (always using transfers start date instead of lockup start date).

We need to adjust our calculation to account for it.

**Comment by marcinbodnar** [comment]
> @jimmy3dita @marcinbodnar according to information from @evgenykuzyakov the source of problem is a bug in earlier version of lockup contract (always using transfers start date instead of lockup start date).
> 
> We need to adjust our calculation to account for it.

@vgrichina Ok, but if so then the wallet is calculating the locked balance properly. 
 For example for this account `08d9a90ffd033fdf966c0a04c1feb70627d1a5e7e9328b13ee6a90c322e58bd8`, we take `lockup_timestamp` (as it's bigger than `transfers_timestamp`) as a lockup starting date, so it's correct. So the unlocked balance is actually negative. And the only change that we should do is to check if the balance is negative and if so we should show zero Near. Right?

But I wonder how the user ended with this state. We had the same issue on wallet a few weeks ago (always taking `transfers_timestamp` as a starting point), that was fixed. So I guess that before this fix was made, these few users transferred more Near from lockup than they should be able to?

**Comment by jimmy3dita** [comment]
> @jimmy3dita @marcinbodnar according to information from @evgenykuzyakov the source of problem is a bug in earlier version of lockup contract (always using transfers start date instead of lockup start date).
> 
> We need to adjust our calculation to account for it.

I believe we need more information from @evgenykuzyakov :
- the definition of `early` means we can safely add an if/else statement based on a specific epoch time? Or we have other ways to recognize these "inaccurate" lockups?
- do we know the correct _lockup start date_ ? Or we have to stick to the _transfers start date_ even if the funds are supposed to follow a different vesting schedule?
- do we have to calculate the vesting from a different attribute in the contract json?
- as mentioned by @marcinbodnar , do we risk that users see a too large available balance? We may go in the opposite direction: users transfer too much, and experience a contract fail/panic at the consensus level

It may also help to get 4 or 5 examples of contracts that fall in the two (or more?) categories, so we can run some e2e tests

**Comment by marcinbodnar** [comment]
@vgrichina @jimmy3dita  I pushed fix here #1668 , where we compare the value from our calculation (correct amount) and from `core-contracts/get_locked_amount` (possibly wrong) and use the smaller one. 

If I understand correctly, in these few cases we need to use the wrong amount because it will match the amount of Near that the user can actually transfer. If there is a way to check if the contract is the one with an error then we can refactor it and not use `get_locked_amount`. 

There is possibly other error in contract, if you check this account `cdot.near` you will notice that the release start date is `Feb 10 2021`, but if you check unreleased amount with `get_locked_amount`:
`NODE_ENV=mainnet near view b28eae53bcc3a7ec9a63116f220f468a07b6c5e1.lockup.near get_locked_amount`
it looks like the release never starts.

**Comment by jimmy3dita** [comment]
Leaving this one here too: https://github.com/near/near-wallet/pull/1668#issuecomment-821541655
