### ISSUE TITLE
Terms of Service and Privacy Policy

### ISSUE THREAD

**Issue by corwinharrell** [near/near-wallet#1647]
### Problem

We currently don't present or require acknowledgement of any Terms of Service of Privacy Policy within the wallet. This is a legal and regulatory necessity and is something we should add immediately.

### What are we doing about it?

We'll first be linking to a pdf with the Terms and Privacy Policy, and in the future can display the terms directly within the wallet if we deem that to be beneficial. Within the onboarding flow, we'll need to present this TOS as a confirmation step once the user has selected their Account ID.

<img width="1036" alt="Screen Shot 2021-04-13 at 1 57 13 PM" src="https://user-images.githubusercontent.com/5934188/114598684-2ebf1400-9c60-11eb-89cf-f7d776b9076e.png">

**Comment by corwinharrell** [comment]
@jimmy3dita The content here is placeholder, so please refine it to match our needs.

Another thought I had is that users may not always encounter the "Reserve my Account ID" screen if they are acquiring their wallet from a near name or faucet for example. Where should we display this acknowledgment in those cases?

**Comment by jimmy3dita** [comment]
> @jimmy3dita The content here is placeholder, so please refine it to match our needs.

Please make sure that ToS and Privacy are clickable separately:
- [Privacy Policy](https://near.org/privacy/)
- [ToS](http://wallet.near.org/terms/) >> this link is not yet there

Also, the `Terms of Service` link in the footer points to the privacy policy

> Another thought I had is that users may not always encounter the "Reserve my Account ID" screen if they are acquiring their wallet from a near name or faucet for example. Where should we display this acknowledgment in those cases?

Great catch! Nearnames.com provides the 12 words passphrase, so the user has to recover it. It's a corner case, let's ship this one quickly and I'll ask advice from NF.

**Comment by jimmy3dita** [comment]
@Patrick1904 from what I understand, we have to:
1. generate a new website link at https://wallet.near.org/terms/ and open it on a new link (so we don't lose the focus if they close down the terms window)
2. have the PDF available for download

This is the PDF: 
[_20210319 Revised NEAR Wallet T&Cs.pdf](https://github.com/near/near-wallet/files/6305500/_20210319.Revised.NEAR.Wallet.T.Cs.pdf)

I don't see the necessity to create a new static page right now, while it's important to have this document out asap.

**Comment by Patrick1904** [comment]
> @Patrick1904 from what I understand, we have to:
> 
> 1. generate a new website link at https://wallet.near.org/terms/ and open it on a new link (so we don't lose the focus if they close down the terms window)
> 2. have the PDF available for download
> 
> This is the PDF:
> [_20210319 Revised NEAR Wallet T&Cs.pdf](https://github.com/near/near-wallet/files/6305500/_20210319.Revised.NEAR.Wallet.T.Cs.pdf)
> 
> I don't see the necessity to create a new static page right now, while it's important to have this document out asap.

I recommend that we just host the PDF on the `/terms` route since the PDF already has the correct formatting. The user can download the PDF if necessary using the browser 'save as...' options.
