### ISSUE TITLE
Remove required /profile route to enter the Wallet account page

### ISSUE THREAD

**Issue by Patrick1904** [near/near-wallet#1658]
**Problem**
Currently to access a NEAR Wallet account page, one has to go to wallet.near.org/profile/johndoe.near

Requiring `/profile` as part of the account URL is unnecessary and deviates from web standards (Twitter, FB, Instagram, etc.) 

**Solution**
1. Remove required `/profile` as part of Wallet account route
2. Support any links that still contain the `/profile` route as part of URL

**Comment by Patrick1904** [comment]
@jimmy3dita @corwinharrell any objections/concerns with this one?

**Comment by corwinharrell** [comment]
Nope makes sense 👍

**Comment by jimmy3dita** [comment]
Makes sense to me as well!

I can only think of corner cases, like an account that is named `terms` which would conflict with the current URL `https://wallet.near.org/terms`. This can be easily solved by restructuring the hierarchy:
`https://wallet.near.org/profile/pepe.near` might become `https://wallet.near.org/pepe.near/profile`
`https://wallet.near.org/terms` might become `https://wallet.near.org/terms/terms` 😅

I've put it in P3, will be happy to raise it to P2 if the work is really small (like one day) and we are sure it won't break any existing link or mass-logout everyone, as we might end up with additional pressure on the ticketing platform

**Comment by Patrick1904** [comment]
> Makes sense to me as well!
> 
> I can only think of corner cases, like an account that is named `terms` which would conflict with the current URL `https://wallet.near.org/terms`. This can be easily solved by restructuring the hierarchy:
> `https://wallet.near.org/profile/pepe.near` might become `https://wallet.near.org/pepe.near/profile`
> `https://wallet.near.org/terms` might become `https://wallet.near.org/terms/terms` 😅
> 
> I've put it in P3, will be happy to raise it to P2 if the work is really small (like one day) and we are sure it won't break any existing link or mass-logout everyone, as we might end up with additional pressure on the ticketing platform

Good point!

We have quite a few routes that will have to get priority over an `accountId` (`/staking`, `/terms`, `/buy`, `/sign`, `/login`, etc.). If a username matches an existing route, the route will get priority. So going to `wallet.near.org/terms` will go to the `/terms` page, even if the users account ID is actually `terms`.

cc @vgrichina
