### ISSUE TITLE
The wallet shows only the Near logo and footer before the account state is loaded

### ISSUE THREAD

**Issue by marcinbodnar** [near/near-wallet#1665]
At this moment Near logo and footer are showing immediately after the page loaded, and then we wait for the account state to be loaded before the rest of UI is shown. This is because we want to be sure if the Landing page (no account) or Dashboard should be shown.

The idea is to improve this process, by:
1. First check if there is info about the account in the localStorage, and if so, we can show menu options and some other basic UI, before the account state is loaded.
2. If there is no info about the account in localStorage, we show the Landing page.

**Comment by jimmy3dita** [comment]
What is the issue from the user's point of view?

**Comment by marcinbodnar** [comment]
> What is the issue from the user's point of view?

The user needs to wait 1-2 seconds (or longer if the network is slow) before anything other than the logo and footer is shown.

**Comment by jimmy3dita** [comment]
Thanks, added a priority 2, as the absence of this feature can generate an unnecessarily high number of tickets if the RPC is temporarily slow or unresponsive. 
Also, it's possible that in certain geographic areas this delay is higher anyway.

This issue reminds me of similar sync/async issues, such as the "name is unavailable" in #634 and #1506

**Comment by vgrichina** [comment]
@jimmy3dita I suggest we put it as P1 as the issue is pretty bad if you aren't on excellent network or RPC is slow, e.g. @ilblackdragon is totally frustrated with it in China.

This is something that lies on a critical path to success (like paying for something using NEAR).
