### ISSUE TITLE
Lockup balances behave weirdly when there is early vesting termination

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#1686]
**Problem**

Lockup balances behave weirdly when there is early vesting termination (you can get negative on available tokens).

**Expected Behavior**

Early termination of vesting is taken into account:
https://github.com/near/core-contracts/blob/d84f7a924b79009d3f7aa4e577c07b08a0489dc9/lockup/src/getters.rs#L97
https://github.com/near/core-contracts/blob/d84f7a924b79009d3f7aa4e577c07b08a0489dc9/lockup/src/getters.rs#L112

**Steps to reproduce**

1. Go to Profile page for account with such problem (gonna DM)
2. Notice negative balances

**Comment by vgrichina** [comment]
@marcinbodnar @jimmy3dita setting this as P1 as blocking some of former team members from accessing staking rewards.

**Comment by marcinbodnar** [comment]
@vgrichina ok, I'm on it

**Comment by jimmy3dita** [comment]
This is a good example of logic that we want to "bundle" with smart contracts, and avoid that every wallet must re-implement this same piece of code
