### ISSUE TITLE
Link wallet errors to Zendesk search

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet#1701]
## Story

As a wallet user who encounters an error, I want a one-click query to Zendesk search with my specific error, so I can get articles and FAQs with a solution.

As a NEAR Wallet developer improving the product, I want to see the list of most common Zendesk search queries over time, so I can correctly prioritize new articles and bugfixing

## Acceptance Criteria

- [ ] Given the error `error-one` generate a search URL `https://nearhelp.zendesk.com/hc/en-us/search?utf8=%E2%9C%93&query=error-one`
- [ ] If clicked, open a search result on Zendesk containing the `error` query
- [ ] Have the link to the search query inside the error box (top right corner) so the user can click on it and land on Zendesk
- [ ] Have the link opened in a new window, to avoid interruptions of the user flow
- [ ] Have the right call to action, such as "Click Here to find a solution"

From the screenshot below, the search query should be "2FA code was not verified correctly"
<img width="1426" alt="Schermata 2021-04-23 alle 11 26 56" src="https://user-images.githubusercontent.com/6222429/116482115-57870200-a839-11eb-8f44-f75021853d29.png">

## Unhappy Path
- The user clicks the error link, but it doesn't open any Zendesk page
- The user clicks the error link, and Zendesk doesn't find any article

## NOTES
Zendesk provides a CSV file with a ranked list of most common queries (as of today it is `staking`) and the most clicked article for that specific query.
The goal for this feature is to periodically check the most common queries, and:
1. extend the existing articles with increasingly better answers to the query
2. add articles to new unanswered queries
3. fix any bugs or improve the UX to reduce the incidence of a given error

**Comment by jimmy3dita** [comment]
@corwinharrell I need a quick validation of the idea, and the ideal copy for the call to action.

Right now is "click here to find a solution" but I don't really like it

**Comment by corwinharrell** [comment]
@jimmy3dita I think simply saying "View FAQ" is enough for the user to assume that they might find an answer there.

<img width="532" alt="Screen Shot 2021-05-04 at 10 17 50 AM" src="https://user-images.githubusercontent.com/5934188/117017976-158b0f80-acc2-11eb-8d57-0850533ebd0b.png">
