### ISSUE TITLE
QR code URL incompatible with third-party wallets

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet#1759]
**Problem**
If I try to use the QR code generated by `https://wallet.near.org/receive-money` the QR code generates the entire URL of the web wallet instead of the address alone.

As a result, third-party wallets (tested on Moonlet and Gate.io) will try to setup the recipient as `https://wallet.near.org/ADDRESS.near`

The same issue is present also if I copy the address by tapping on the icon, and seems to be limited only to my mobile device (Safari browser on iPhone)

**Expected Behavior**
Fix: the QR code should publish only the wallet ID

Feature improvement: we might want a `near:` URI standard, similar to [BIP0021](https://en.bitcoin.it/wiki/BIP_0021) and [EIP 681](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md)

**Steps to reproduce**
1. open https://wallet.near.org
2. click "receive"
3. scan the QR code with one of the many mobile applications available
4. paste the resulting value as a recipient for a NEAR transaction

To test the issue end-to-end, install one of the alternative wallet apps (MathWallet, Moonlet, or Gate.io), and use the QR code function to receive funds.

To further test the interoperability, try to scan the QR code generated by Gate or Moonlet

**Comment by stefanopepe** [comment]
@Patrick1904 do you want to give a look to this one?

**Comment by Patrick1904** [comment]
> @Patrick1904 do you want to give a look to this one?

Thanks @stefanopepe I'll fix it.
