### ISSUE TITLE
Auto Redirect vs. Close Button. MISSING TX Hash. 

### ISSUE THREAD

**Issue by BenKurrek** [near/near-wallet#1765]
**Problem**
When a transaction is complete, it gives me the option to click a close button. If I DON'T click this close button, it will automatically redirect me back to my original page. 
![image](https://user-images.githubusercontent.com/57506486/118888602-dd8ee980-b8c9-11eb-8022-3cc172a2dbc5.png)

If I get automatically redirected, it will provide a transaction hash in the query string as shown below: 
![image](https://user-images.githubusercontent.com/57506486/118888683-f7303100-b8c9-11eb-8e57-ee509a10e7cc.png)

If I click the close button manually, it will NOT provide a transaction hash and this is the URL: 
![image](https://user-images.githubusercontent.com/57506486/118888745-0c0cc480-b8ca-11eb-938d-e0089ddaa6ef.png)

This is all occurring on a SUCCESSFUL transaction and so I need to get the transaction hash EVERY time even if the user clicked the close button. Matt Lockyer said this was a wallet issue and as such, I am posting the problem here.

**Comment by Patrick1904** [comment]
@BenKurrek, thanks for reporting this bug. The intended behavior here is that clicking the 'Close' button will simply take the user to the Wallet dashboard, not back to the referring app (fixed here: https://github.com/near/near-wallet/pull/1769). If you provide a `callbackUrl` then the user will automatically return to the provided URL after the transaction is successful.



The guest book is a good example: https://near-examples.github.io/guest-book/

Is there a reason why you're not providing a `callbackUrl` and still want the user to return to the referring app? We could consider adding a 'Return to app' button in addition to the 'Close' button for this case.

**Comment by BenKurrek** [comment]
I looked through the guest book example and I can't find the callback URL. I also have some questions regarding the way that you guys coded the guest book. Is there any way I could schedule a call sometime? if this is possible, could you reach out to my discord Benji KOO#2468 or my email bkurrek@uwaterloo.ca. Thanks so much.

**Comment by Patrick1904** [comment]
> I looked through the guest book example and I can't find the callback URL. I also have some questions regarding the way that you guys coded the guest book. Is there any way I could schedule a call sometime? if this is possible, could you reach out to my discord Benji KOO#2468 or my email [bkurrek@uwaterloo.ca](mailto:bkurrek@uwaterloo.ca). Thanks so much.

`callbackUrl` is optional and falls back to using the current url (referring app) if not provided. See here in `near-api-js`: https://github.com/near/near-api-js/blob/897a650a0ca75952f5ea995766372d7d572aaeb5/src/wallet-account.ts#L208

For contracts:
https://github.com/near/near-api-js/blob/master/src/contract.ts

For the guest book transaction signing, a custom `callbackUrl` would be provided here: https://github.com/near-examples/guest-book/blob/master/src/App.js#L30

I will reach out to you in Discord. Thanks!
