### ISSUE TITLE
Implement ledger support for WebHID & WebUSB

### ISSUE THREAD

**Issue by MaximusHaximus** [near/near-wallet#1775]
**Problem**
Recent updates to Chromium have broken U2F functionality on all Chromium based browsers.  Furthermore, U2F has already been marked as deprecated by Ledger with an intention to remove support for U2F entirely in Q1 2021.

Although Ledger's official migration guide documentation for moving off of the now deprecated U2F transport indicates that we should replace U2F with WebUSB, both U2F and WebUSB have recently been rendered unusable by the latest Chrome v91.xx update.

There is an alternative transport, WebHID, which still works on the latest version of Chromium, however, both WebUSB and WebHID are still in draft stages, and **neither** one is yet supported by Firefox, which _only_ works with the (now deprecated) U2F transport.

Given these facts, and our desire to maintain ledger support for major browsers for as long as we can, we should implement fallback logic that tries each of the available transports and uses whichever one is supported by the current browser.

This pattern has already been introduced in some other open source projects -- an example code pattern that implements fallback for each of the transport types can be found here:
https://github.com/vacuumlabs/adalite/pull/1007/files

We depend on `near-ledger-js` (https://github.com/near/near-ledger-js) for ledger interactions, along with multiple other near ecosystem projects (like `near-cli`, `near-multistaker`), so it would be nice to have this fallback logic in `near-ledger-js` to avoid duplicating it into multiple repositories, especially given how volatile these standards are; we may very well need to implement integration with Ledger Live with the _next_ iteration of changes to Chrome, Firefox, etc.

Reference migration guide **_(obsolete, given Chrome no longer supports WebUSB as of v91.x)_**:
https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_webusb.md
_"We plan to remove the support of U2F channel proxying on our apps in Q1 2021"_

**Comment by volovyk-s** [comment]
Related issue: https://github.com/near/near-cli/issues/762

**Comment by stefanopepe** [comment]
Looks to me that we would essentially limit the use of Ledger on Chrome, as Firefox (and potentially Brave) is not anymore supported. Correct?

**Comment by MaximusHaximus** [comment]
Yes, switching to WebUSB _only_ would result in breaking Firefox support, but for now we can continue to fallback to U2F support for as long as it continues to work.

Update: WebUSB is apparently not functional in Chrome either as of v91.  WebHID appears to work, however.
We can try all 3 transports in code and use whichever one succeeds.

Example code pattern :):
https://github.com/vacuumlabs/adalite/pull/1007/files

:wave: vacuumlabs!

**Comment by ilblackdragon** [comment]
This would be great to have as part of wallet sdk library directly, so all the other projects that use Ledger can start using it right away as well. Might be a good initial piece of functionality to have if wallet sdk has not started yet.

**Comment by MaximusHaximus** [comment]
@ilblackdragon Did some digging/questioning about this, and It looks like this logic would exist in https://github.com/near/near-ledger-js ideally, so that all of our various packages (including `near-cli`, `near-wallet`, `near-multistaker` just to name a few that depend on `near-ledger-js`) can benefit from automatic transport fallback without having to duplicate the fallback logic in multiple places. :+1:

**Comment by MaximusHaximus** [comment]
@volovyk-s Re: near/near-cli#762 - this actually isn't directly related to the CLI, because the CLI uses a specific Node transport `@ledgerhq/hw-transport-node-hid'` which is not used by our `near-ledger-js` library, because it is designed for use in the browser.  That means that #762 won't be resolved by this change and whatever issue with segfaults that we are seeing in near-cli still needs to be investigated independently of this work stream for resolving ledger support in the wallet and other web browser based ledger tools that depend on the `near-ledger-js` package.

**Comment by volovyk-s** [comment]
> @volovyk-s Re: [near/near-cli#762](https://github.com/near/near-cli/issues/762) - this actually isn't directly related to the CLI, because the CLI uses a specific Node transport `@ledgerhq/hw-transport-node-hid'` which is not used by our `near-ledger-js` library, because it is designed for use in the browser. That means that #762 won't be resolved by this change and whatever issue with segfaults that we are seeing in near-cli still needs to be investigated independently of this work stream for resolving ledger support in the wallet and other web browser based ledger tools that depend on the `near-ledger-js` package.

Got it. Maybe we should start using `near-ledger-js` in `near-cli`. Looks like it's platform-agnostic, because it's not using or importing any particular transport in `index.js`. But it will after https://github.com/near/near-ledger-js/pull/44/files is merged. Do you think we should we keep this flexibility?

**Comment by volovyk-s** [comment]
> @volovyk-s Re: [near/near-cli#762](https://github.com/near/near-cli/issues/762) - this actually isn't directly related to the CLI, because the CLI uses a specific Node transport `@ledgerhq/hw-transport-node-hid'` which is not used by our `near-ledger-js` library, because it is designed for use in the browser. That means that #762 won't be resolved by this change and whatever issue with segfaults that we are seeing in near-cli still needs to be investigated independently of this work stream for resolving ledger support in the wallet and other web browser based ledger tools that depend on the `near-ledger-js` package.

Yeah, good point!
`near-ledger-js` is used in `near-cli` and probably other non browser projects, so let's keep it flexible :)

**Comment by andy-haynes** [comment]
Since Chrome now has ledger support I believe we are good to close this out. Please leave a comment here if that's not the case.
