### ISSUE TITLE
Login screen flashes full access key request

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1791]
When wallet login screen opens, first few seconds it shows the full access key request (with warning and everything) and only after that time switches to the request to share account id.

# Steps to reproduce

1. Go to https://app.ref.finance
2. Click "Login"
3. Observe first few seconds the screen like this:

<img width="654" alt="Screen Shot 2021-05-29 at 5 55 04 AM" src="https://user-images.githubusercontent.com/175486/120071081-6e8c6000-c042-11eb-8bfe-745d5cbbfc02.png">

**Comment by stefanopepe** [comment]
Tagging @marcinbodnar, as probably was introduced by the recent changes to redux state

**Comment by marcinbodnar** [comment]
Thanks @stefanopepe
