### ISSUE TITLE
Testnet- Failed to redirect to sign transaction

### ISSUE THREAD

**Issue by xmates0980** [near/near-wallet#1802]
I opened an a testnet on Banana- Wnear recently, but it show error as tittle. i can not add  liquidity for them, some pics attd. Pls help!
![38AD5850-E8ED-4FB2-9720-A8D40A9D1F53](https://user-images.githubusercontent.com/85275705/120595654-ef958e00-c46c-11eb-964e-0d218c64f57c.png)
![B3FBD2A3-B819-4202-9F83-226F30E59985](https://user-images.githubusercontent.com/85275705/120595668-f4f2d880-c46c-11eb-9bf8-06d06a5866e6.png)

**Comment by stefanopepe** [comment]
Dear user,

Thank you for reaching us. I searched for the transaction on the explorer, [here](https://explorer.near.org/transactions/Ce84q2sPjaMaVTCSMpniX9aBXpXQGjkVouKE82n91Qki), and I found the following failure reason:
```
{
  "ActionError": {
    "index": 0,
    "kind": {
      "FunctionCallError": {
        "ExecutionError": "Smart contract panicked: panicked at 'Failed to deserialize input from JSON.: Error(\"missing field `pool_id`\", line: 1, column: 62)', ref-exchange/src/lib.rs:54:1"
      }
    }
  }
}
```

I suggest reaching out to ref.finance support directly, as it seems that later on you were able to add liquidity to some pools (as from [here](https://explorer.near.org/transactions/5NAw8a7jbL6VCsDDFthEMSpcTLz6ndMDKboMGKafjXjX)).
Let me know if you have any other questions, or I can close this issue
