### ISSUE TITLE
Fix padding for items and fix icon size in "Authorized Apps" page.

### ISSUE THREAD

**Issue by thedruny** [near/near-wallet#1805]
**Problem**
![image](https://user-images.githubusercontent.com/53578081/120850458-24463a00-c580-11eb-9ff5-2cec15c7fb2b.png)

**Expected Behavior**

The icon should be correct size and also should be bottom padding for items.

**Steps to reproduce**

1.  Open "Account" page
2.  Click to "View all" button
3.  Click to any items from list.

**Comment by Patrick1904** [comment]
Fixed in: https://github.com/near/near-wallet/pull/1806
