### ISSUE TITLE
Add Liquality.io to the buy alternatives in the wallet

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet#1807]
Recently, Liquality.io added support to NEAR Protocol, as announced [here](https://medium.com/nearprotocol/liquality-launches-on-near-protocol-a-native-cross-chain-atomic-swap-juggernaut-6e539f9a2d8a).

The idea is to have this feature as a "first come, first serve" basis, so this one might be added to the bottom, right next to Gate.io (or Moonpay where it is available)

![Screen Shot 2021-06-07 at 10 26 14 AM](https://user-images.githubusercontent.com/6222429/121063405-19a3c480-c77b-11eb-80ee-f3e1124bc7de.png)

**Comment by stefanopepe** [comment]
@Patrick1904 I know you have already some other things on the table, feel free to triage this one and include it or not within this sprint.
Comes after the account creation flow and the fungible tokens anyway

**Comment by vgrichina** [comment]
I think we also need to do direct ETH->NEAR integration right in a wallet (though obviously that gonna be a bigger separate task).

I've with Simon from Liquality in Miami and looks like they are currently working to make it much easier to integrate into apps.

**Comment by stefanopepe** [comment]
> I think we also need to do direct ETH->NEAR integration right in a wallet (though obviously that gonna be a bigger separate task).
> 
> I've with Simon from Liquality in Miami and looks like they are currently working to make it much easier to integrate into apps.

Agree, but this is a feature that requires some more time - as it would be great to integrate the experience with Metamask and Aurora/Rainbow Bridge. 
Just realized that it never had a proper description: https://github.com/near/near-wallet-roadmap/issues/1
