### ISSUE TITLE
Focusing Send/Receive/Buy buttons with keyboard on wallet page causes text to disappear

### ISSUE THREAD

**Issue by encody** [near/near-wallet#1814]
**Problem**

Button text on Send/Receive/Buy buttons turns white (disappears) on focus with keyboard.

**Expected Behavior**

Text is still visible when focusing with keyboard.

**Steps to reproduce**

1. Navigate to https://wallet.near.org/
2. Focus one of the Send/Receive/Buy buttons by tabbing to it with the keyboard

https://user-images.githubusercontent.com/7459638/121410278-0aae4500-c928-11eb-8ff7-2e7463aa9ab7.mp4

**Comment by esaminu** [comment]
Unable to repro on latest version of code. No style changes when buttons are in :focus state.
Same results confirmed by @Patrick1904 . Closing the issue.
