### ISSUE TITLE
redirect url during linkdrop doesn't work

### ISSUE THREAD

**Issue by think-in-universe** [near/near-wallet#1818]
**Problem**

When user opens linkdrop with a `redirectUrl` param, the page is not redirected to the url after account is created. 

**Expected Behavior**

User should be redirected to the url as described in https://github.com/near/near-wallet/issues/1641 and implemented in https://github.com/near/near-wallet/pull/1652

**Steps to reproduce**

1. Open the create page with link: https://wallet.testnet.near.org/create/testnet/4JHcJkmy8cQ92b1BLZUUUJZKw6ej2URu6rwoiYN3AL8gba626LspzLjQ97FSPs1aPUVb7EjwwAvHGCkQVQe7EMVW?redirectUrl=https://berryclub.io/  or https://wallet.testnet.near.org/create/testnet/5waZiox2Q11VKAeWpDjTxpkDNaVaXKGSbodBHBqhy2nYt1uLXqH74ctPJPnxfACp9HL3uEspnRGADB9YCzfVZJFy?redirectUrl=https://berryclub.io/
2. Create a new account with linkdrop
3. The page is not redirected to https://berryclub.io/

**Comment by stefanopepe** [comment]
cc @marcinbodnar and @Patrick1904 , we were discussing about this the other for the Account Creation v1

**Comment by think-in-universe** [comment]
I tested again just now for several times, and cannot reproduce the issue any more. the url redirect is working now. 

we indeed could reproduce this issue yesterday as reported by several developers. I have asked them to try again and will share the result here.

**Comment by marcinbodnar** [comment]
> cc @marcinbodnar and @Patrick1904 , we were discussing about this the other for the Account Creation v1

@Patrick1904 Want to check it? If I remember correctly you were working on this feature lately, I think it would be good to double-check the code if everything looks fine.

**Comment by think-in-universe** [comment]
> we indeed could reproduce this issue yesterday as reported by several developers. I have asked them to try again and will share the result here.

The developers could still reproduce this issue. I'm doing more investigation and will share more findings here.
