### ISSUE TITLE
Error during account creation on testnet

### ISSUE THREAD

**Issue by ihaid** [near/near-wallet#1825]
**Problem**
![image](https://user-images.githubusercontent.com/38665104/122206090-a5b79980-cea9-11eb-95f9-4511d091fbdd.png)
If you click on the button again after the error then an account will be created

**Steps to reproduce**

1. Create an account on testnet

**Comment by Patrick1904** [comment]
Thanks @ihaid. This has been fixed by @MaximusHaximus AFAIK.
