### ISSUE TITLE
Paras Faucet Integration

### ISSUE THREAD

**Issue by heycorwin** [near/near-wallet#1826]
## Problem
Our current wallet onboarding required users to fund new accounts by making an initial NEAR deposit. This is a barrier to entry for users who are not already holding NEAR, and there is no way currently for users to fund new accounts with other tokens they might be holding such as ETH.

#### How did we discover this problem?
The Paras faucet has proven to be a valuable enabler for Rainbow Bridge users coming from Ethereum who have yet to create a NEAR account since it allows them to do so without the prerequisite of holding NEAR. There is a clear opportunity here to make an experience native to the wallet that enables users to create new accounts by leveraging their existing assets as "social proof".

#### Job Story(s)
- When I create a new account, I want to avoid having to fund my account by leveraging my existing assets to authorize my use of the faucet, granting me an account free of charge.

#### What are we planning to do about it?
During wallet onboarding, users should be able to select an option to receive a funded account by connecting an Ethereum wallet containing a minimum balance of `0.05 ETH` as a kind of social proof.

#### What are we _not_ planning to do about it?
We are not allowing users to fund their new account with ETH or other tokens. Connecting their Ethereum wallet during account creation is simply a means to authenticate the use of the paras faucet, and will not actually cost them.

## Measuring Success
We should monitor the following scenarios to determine the success of this integration:
1. When using the rainbow bridge without an account, users regularly navigate to the wallet to create their new NEAR account by connecting an Ethereum wallet.
2. Independent of the bridge, users creating a new account on `wallet.near.org` regularly take advantage of the ability to connect their Ethereum wallet in order to gain access to the Paras faucet as a means to fund their new account.

## Resources
There was discussion of making this integration native to the bridge front-end, and designs have been explored around how to accommodate this here: https://github.com/aurora-is-near/rainbow-bridge-frontend/pull/215

While we may not use the exact same UX, this can act as a reference and starting point for how it might be integrated within the wallet.

#### UX & UI Design
- https://www.figma.com/file/0LZELExyOkQmL6X1R8q6zM/1826-%E2%80%93-Paras-Faucet-Integration?node-id=1%3A2

**Comment by corwinharrell** [comment]
Design complete.

One thing to keep in mind about interacting with Ethereum Wallets for the purpose of signing txns on the Ethereum side:

On mobile, the only way a user will be able to leverage this faucet is by accessing NEAR wallet from inside a Ðapp browser. Outside of a Ðapp browser, there is no way for a user to connect to a wallet to confirm their Ethereum transactions. I suggest that if there is a way to detect that the user is using a standard browser on mobile, that we hide the option to connect their Ethereum account since it is ultimately inaccessible.

**Comment by Patrick1904** [comment]
Closing as issue is outdated
