### ISSUE TITLE
redirect urls during linkdrop should also work for existing account (when user doesn't create new account)

### ISSUE THREAD

**Issue by think-in-universe** [near/near-wallet#1827]
### Overview

As a linkdrop sender, I want to redirect the receiver to a URL after he/she received the dropped NEAR even if the user claimed NEAR with an existing account (didn't create a new account), so I can the linkdrop redirect workflow will be the same for all the users.

As described in #1641, implemented in #1652, and fixed recently in #1818, new users will be redirected to the `redirectUrl`. Besides new created accounts, we also want to redirect the existing users to the `redirectUrl`.

### Acceptance Criteria
- [ ] When a user open a linkdrop (e.g. https://wallet.testnet.near.org/create/testnet/5waZiox2Q11VKAeWpDjTxpkDNaVaXKGSbodBHBqhy2nYt1uLXqH74ctPJPnxfACp9HL3uEspnRGADB9YCzfVZJFy?redirectUrl=https://berryclub.io/), and claim with an existing account, he will still be redirected to https://berryclub.io
- [ ] The existing account's name is passed as an argument to the redirect URL (`accountId`): https://berryclub.io?accountId=someone.testnet

**Comment by think-in-universe** [comment]
The enhancement is also important to one dapp that will be launched around June 25th. so hopefully we could add the enhancement recently.

**Comment by stefanopepe** [comment]
Robert, thank you for this suggestion.
I'll leave the technical discussion to @MaximusHaximus , while my main concern is around phishing and spear phishing attacks.

An attacker might leverage this feature to create malicious airdrops to be distributed via chat channels (or similar). A small amount of tokens might convince the user to click and claim the funds, but then get redirected to a fake application that could ask for the seed passprhase or require the authorization of a full-access key that is capable to drains funds (imagine a copycat of berryclub).
Let us wait for a rapid feedback by @vgrichina and @kcole16 as they spent some time on these type of issues too.

**Comment by think-in-universe** [comment]
thanks Stefano @stefanopepe 

the security concern of phishing makes sense. 

IMHO, since we already supported `redirectUrl` for newly created account, adding `redirectUrl` support for existing users is not less secure than the current model.
