### ISSUE TITLE
Add a URL parameter `tab` to open Collectibles tab directly

### ISSUE THREAD

**Issue by think-in-universe** [near/near-wallet#1877]
## Story

As a NFT DApp developer who cares about the NFT user workflow of my users, I want to make it possible to redirect my user to the page that can show the Collectibles without clicking the tab, so I can show my user the latest NFTs they have received.

Is it possible to add a query parameter like `?tab=collectibles` in the link, so the page will open the corresponding tab when the user open the **Wallet** page

![image](https://user-images.githubusercontent.com/46699230/123933483-01fbdc80-d9c5-11eb-8f51-e198611ed1bb.png)

## Acceptance Criteria

- [ ] If the wallet page url contains the `?tab=collectibles`, open the **Collectibles** tab directly
- [ ] If the wallet page doesn't contains the tab parameter, or `?tab=balances`, open the **Balances** tab directly.
- [ ] Mobile ok
- [ ] Tested

## NOTES

- the user story is requested by one NFT project that wants to enhance their UX for users.

**Comment by ilblackdragon** [comment]
Btw, I would love to have collectibles and balances page for non my account.
Right now you can only open profile account for other accounts, but there is no reason why other pages shouldn't work the same.

**Comment by stefanopepe** [comment]
@corwinharrell I would batch Robert's request with the pagination.
@MaximusHaximus I suppose the footprint of this additional change is acceptable

**Comment by stefanopepe** [comment]
@MaximusHaximus assigned this to you, so we can make sure it will make it in the current sprint (or not). Feel free to "un-assign" when done
