### ISSUE TITLE
Changing account in the selector has a delay

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1879]
**Problem**
Changing account in the selector has a delay. For example when logging in to an app and need to switch an account from one selected - there is a noticeable delay after selecting a different account in the drop down.

**Expected Behavior**
There is no delay, as there is no information needed be loaded at that point.

**Steps to reproduce**

1. Open https://app.ref.finance
2. Click "Log in"
3. Go to wallet
4. Select another account
Observe that account name in the selection doesn't change right away, but shows "..." loading.

**Comment by stefanopepe** [comment]
@MaximusHaximus is this a bug, or we still need to wait for a response from the RPC?

**Comment by marcinbodnar** [comment]
While switching accounts we need to get new account state data, so it's related to how fast the response will be. 

I tested it, a few minutes ago it's working very fast for me, changing the account took less than 0.5 second. After few minutes it was about 1 second. But it might take longer if the response is slow.

I will take a deeper look and try to improve it.

**Comment by marcinbodnar** [comment]
Added few improvements, it should work faster:
 - there were some unnecessary calls in `checkContractId` action
 - `getAccount` method was checking lockup, and we don't need it in this flow
 - improved `loadAccount` method, so it will not check for 2fa two times.
