### ISSUE TITLE
Add OkCoin to buy options

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet#1885]
Today OkCoin launched NEAR trading for US customers, introducing an airdrop for the first 5000 customers that spend $50 on it.

Since it seems trivial to add this option to our buy button, I'm proposing to have it included in the next release.

This is the landing link: https://www.okcoin.com/prices/near-protocol-near-price-chart
This is the launch article, for additional background to "weight" the decision: https://blog.okcoin.com/2021/07/01/near-protocol-is-now-on-okcoin/

**Comment by stefanopepe** [comment]
@MaximusHaximus let's consider to add this one to the backlog, and have it on the list of the buy options soon =)

**Comment by Patrick1904** [comment]
@corwinharrell I'm not able to find an svg version of OkCoin's latest logo. Do you know if there's potentially an alternative source for this?

**Comment by stefanopepe** [comment]
@think-in-universe do you think we can help Patrick with this task? Do you have the csv logo handy?

**Comment by think-in-universe** [comment]
@stefanopepe I'm working on looking for a svg version of the OKCoin logo. will let you know once I get one.

**Comment by think-in-universe** [comment]
@stefanopepe checked with OKCoin customer support and they suggest us to convert the PNG to SVG ... is this appropriate?

**Comment by think-in-universe** [comment]
@stefanopepe they'll send me the SVG logo. will share with you once I have it.

**Comment by think-in-universe** [comment]
@Patrick1904 @stefanopepe I have sent the SVG logos to Patrick. hope it resolves the problem.
