### ISSUE TITLE
Comma formatting for token amounts

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1897]
Currently near amount has "," to separate 3 decimal places but token balances are not.

**Comment by stefanopepe** [comment]
It may be a bug introduced by different regional settings to the OS >> in US/UK decimal and thousands separators are respectively `.` and `,` such that you can read `1,000,000.50` for one million and fifty cents.
In other locales (I know for sure Italy) they are inverted, and you would read `1.000.000,50`.

I tried myself with no success, do you have a screenshot so I'm sure we are talking about the same thing?

**Comment by Patrick1904** [comment]
Closing as this has been fixed
