### ISSUE TITLE
Hide 0 balances for tokens

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#1900]
Currently if user have touched contracts for any reason, they show up with 0 balances in the wallet without any reason.

Here is an example of a wallet that was whitelisting some tokens for another contract usage:

<img width="569" alt="Screen Shot 2021-07-08 at 12 03 23 PM" src="https://user-images.githubusercontent.com/175486/124976844-9deca000-dfe4-11eb-9836-36e74ee938da.png">

**Comment by stefanopepe** [comment]
It should be fixed with the V0 of fungible tokens transfers in #1714, as is part of the acceptance criteria.
Linking this issue to the epic, so you can test when we are ready
