### ISSUE TITLE
When balance drops below 0.2  wallet thinks account is not initialized

### ISSUE THREAD

**Issue by nearmax** [near/near-wallet#1901]
**Problem**
When balance of an account drops below 0.2 wallet thinks that account was not initialized and shows the below message. However, the account might be fully functional. Even if balance was almost 0 empty accounts can still be used to log in into many dApps, like ref.finance. 0.2 NEAR is enough to pay for the gas for most of the transactions.

![image](https://user-images.githubusercontent.com/35039879/124989477-05f6b280-dff4-11eb-8317-6f339f330bef.png)

**Expected Behavior**
Wallet treats accounts with less than 0.2 NEAR as regular accounts.

**Comment by MaximusHaximus** [comment]
This is expected behaviour that we added intentionally and and just shipped this week.
Ref: https://github.com/near/near-wallet/issues/1752 

Although the main wallet page/UI shows the 'lock' screen, specific routes (such as logging into an app) should **not** be  locked and can be used for interacting with apps.

The idea here was to motivate folks that had accounts that were created by the coin-op faucet to send funds to those accounts, while still retaining their ability to do very cheap/simple things with some apps.

cc: @stefanopepe

**Comment by stefanopepe** [comment]
I agree with @nearmax, the screen should show only the first time - then if a user falls again under 0.2, the wallet should remain operational for login and other related activities (e.g. 2fa and key rotation)

**Comment by MaximusHaximus** [comment]
> I agree with @nearmax, the screen should show only the first time - then if a user falls again under 0.2, the wallet should remain operational for login and other related activities (e.g. 2fa and key rotation)

Currently:

We set a flag on any new funded accounts in the Accounts database that `near-contract-helper` uses.
When the wallet loads, we fetch the state of that flag from the contract helper.
- If the flag is set and the wallet balance is under 0.2N, then we display the splash screen.
- If the flag is set and the wallet balance if over 0.2N, the wallet frontend POSTs to the contract helper and clears that flag.
- If the flag is not set, then no splash screen is displayed to the user even if their account balance is <0.2N

As a result, you should only see the splash screen when the account is under 0.2N _and you have never loaded the wallet frontend while the account balance is >0.2N_.  If you have _ever_ loaded the wallet frontend and the account has >0.2N, then you should not see the splash screen again from then on.

@ihaid Could you test this flow and verify that we don't have a bug around this functionality?  The splash screen should not appear if you have _ever_ loaded the frontend web UI with >0.2N, not _every time the account has <0.2N_.

CC: @Patrick1904

**Comment by Patrick1904** [comment]
> @ihaid Could you test this flow and verify that we don't have a bug around this functionality? The splash screen should not appear if you have ever loaded the frontend web UI with >0.2N, not every time the account has <0.2N.

This is true as long as the user has clicked the 'Continue to my Account' button that appears on the funding screen once the account has been sufficiently funded. If the account was at one point sufficiently funded but the user never clicked the 'Continue to my Account' button, which unlocks the account, then the screen will continue to appear. Clicking the 'Continue to my Account' button is that unlocks the flag in the contract-helper.

We currently do not check if the account has ever had a balance above 0.2N and then automatically unlock the account.

**Comment by ihaid** [comment]
> @ihaid Could you test this flow and verify that we don't have a bug around this functionality? The splash screen should not appear if you have ever loaded the frontend web UI with >0.2N, not every time the account has <0.2N.
@MaximusHaximus I tried: create an account, then recover it when it is not funded, and leave it in an incognito window. 
Then in another window fund that account(>0.2N), log in to it, and send money back(<0.2N). 
Return to the incognito window -  splash screen visible but after the refresh, it will disappear

**Comment by stefanopepe** [comment]
@nearmax is the issue still present in the account? I can give a peek to the database to check for glitches
