### ISSUE TITLE
Email Subscripiton section could be removed

### ISSUE THREAD

**Issue by think-in-universe** [near/near-wallet#1912]
**Problem**

The email subscription section on wallet landing page is not quite useful now, and could be moved, per feedback from Amos and Illia. 

![image](https://user-images.githubusercontent.com/46699230/125500260-fbab4df7-6476-4411-b9ca-3a2a38a0ec76.png)

**Expected Behavior**

The email subscription section should be removed now. 

**Steps to reproduce**

1. Open the wallet landing page without login
2. The `sign up below for early access` message is confusing, since we're not at `early access` stage now

**Comment by MaximusHaximus** [comment]
cc: @stefanopepe
