### ISSUE TITLE
The Selected Language is partially visible behind Language Switch in Firefox

### ISSUE THREAD

**Issue by think-in-universe** [near/near-wallet#1929]
**Problem**

The "E" letter (first letter of English) is partially visible behind the language toggle / dropdown in Firefox (while it works fine in Google Chrome) on Desktop (Mac / Arch Linux, etc.)

![image](https://user-images.githubusercontent.com/46699230/126040627-e06fcbbd-726a-4913-ae79-39d6603dedb0.png)

**Expected Behavior**

The selected language should be totally invisible in any mainstream browsers (Google Chrome, Firefox, Safari, etc.)

**Steps to reproduce**

1. Open https://wallet.near.org in the latest Firefox desktop version (e.g. 90.0 on Mac / Arch Linux)
2. The selected language is partially visible behind the language toggle.

**Comment by stefanopepe** [comment]
This seems easy to test. @MaximusHaximus I've optimistically tagged as "good first issue" but if this is not low-risk, feel free to remove it

**Comment by Patrick1904** [comment]
Linking this issue so that it's closed when fixed: https://github.com/near/near-wallet/issues/1859
