### ISSUE TITLE
Linkdrop Pages cannot be open in certain browsers on Android phones used by Chinese users

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#1933]
**Problem**

This is a China-specific issue. 

For the first-time wallet user, when opening the linkdrop links in certain browsers (QQ Browser, UC Browser, Huawei browser in phones) in Android phone (Huawei, Xiaomi, Meizu, Oppo and so on), the screen is blank and nothing is rendered. The issue can be reproduced in both WiFi and 4G did not work. 

The linkdrop pages can be opened successfully in Chrome browser installed in those Android phones. 

**Expected Behavior**

The linkdrop pages should be open successfully in QQ / UC / Huawei browsers in Android phones with brand Huawei, Xiaomi, Meizu, Oppo, etc. in China.

**Steps to reproduce**

1. Open the linkdrop page in one of the browsers: (QQ Browser, UC Browser, system browser in phones) in Android phone (Huawei, Xiaomi, Meizu, Oppo and so on)
2. The page keeps blank and nothing happens

**Comment by think-in-universe** [comment]
This issue is only reproducible on certain Android phones which are popular among Chinese users. 

I have found some devices to reproduce the issue, and will try to investigate and fix the issue.

**Comment by think-in-universe** [comment]
Debugged with Chrome Inspect for Android Browsers, and the reason the page is blank is because the JS / CSS files are not returned (0 bytes are returned).

![image](https://user-images.githubusercontent.com/46699230/126588963-7bf581a0-a7a1-42e2-8b4d-27a92fc6296e.png)

**Comment by think-in-universe** [comment]
By inspecting with cURL for request to the JS file under difference circumstances, below are the testing result.

(1) Open linkdrop page with Huawei Browser (11.1.2.301) on Huawei Android Phone (Android 10; OCE-AN10 Build/HUAWEIOCE-AN10 / HarmoneyOS) 

- Result: Failure
- Expect: JS File returnd
- Actual: HTML page returned

```bash
curl 'https://content.near-wallet.workers.dev/ntl/mainnet/src.fafd6029.js' \
  -H 'authority: content.near-wallet.workers.dev' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 10; HarmonyOS; OCE-AN10; HMSCore 6.0.0.306; GMSCore 21.24.18) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 HuaweiBrowser/11.1.2.301 Mobile Safari/537.36' \
  -H 'accept: */*' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-dest: script' \
  -H 'referer: https://wallet.near.org/create/near/2x5XV75ocTg8R35rq5wn2ULfqM5qta5S9gdLo7U4JoR8vMigBNfSSxkfofUL6hcZAiJF3iT9uV3w2R4zagAsLPV9' \
  -H 'accept-language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7' \
  --compressed
```

(2) Open Wallet home page with Huawei Browser (11.1.2.301) on Huawei Android Phone (Android 10; OCE-AN10 Build/HUAWEIOCE-AN10 / HarmoneyOS) 

- Result: OK
- Expect: JS File returnd
- Actual: JS File returnd

```bash
curl 'https://content.near-wallet.workers.dev/ntl/mainnet/src.fafd6029.js' \
  -H 'authority: content.near-wallet.workers.dev' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 10; HarmonyOS; OCE-AN10; HMSCore 6.0.0.306; GMSCore 21.24.18) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 HuaweiBrowser/11.1.2.301 Mobile Safari/537.36' \
  -H 'accept: */*' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-dest: script' \
  -H 'referer: https://wallet.near.org/' \
  -H 'accept-language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7' \
  --compressed
```

(3) Open linkdrop page with Google Chrome (91.0.4472.164) on Huawei Android Phone (Android 10; OCE-AN10 Build/HUAWEIOCE-AN10 / HarmoneyOS) 

- Result: OK
- Expect: JS File returnd
- Actual: JS File returnd

```bash
curl 'https://content.near-wallet.workers.dev/ntl/mainnet/src.fafd6029.js' \
  -H 'authority: content.near-wallet.workers.dev' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 10; OCE-AN10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Mobile Safari/537.36' \
  -H 'accept: */*' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-dest: script' \
  -H 'referer: https://wallet.near.org/' \
  -H 'accept-language: zh-CN,zh;q=0.9' \
  --compressed
```

(4) Open linkdrop page with Google Chrome (Version 91.0.4472.114 (Official Build) (x86_64)) on MacOS (10.15.7 (19H1217))

- Result: OK
- Expect: JS File returnd
- Actual: JS File returnd

```bash
curl 'https://content.near-wallet.workers.dev/ntl/mainnet/src.fafd6029.js' \
  -H 'authority: content.near-wallet.workers.dev' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'dnt: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36' \
  -H 'accept: */*' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-dest: script' \
  -H 'referer: https://wallet.near.org/' \
  -H 'accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' \
  --compressed
```

**Comment by think-in-universe** [comment]
> (1) Open linkdrop page with Huawei Browser (11.1.2.301) on Huawei Android Phone (Android 10; OCE-AN10 Build/HUAWEIOCE-AN10 / HarmoneyOS)
> 
> * Result: Failure
> * Expect: JS File returned
> * Actual: HTML page returned
> 
> ```shell
> curl 'https://content.near-wallet.workers.dev/ntl/mainnet/src.fafd6029.js' \
>   -H 'authority: content.near-wallet.workers.dev' \
>   -H 'pragma: no-cache' \
>   -H 'cache-control: no-cache' \
>   -H 'user-agent: Mozilla/5.0 (Linux; Android 10; HarmonyOS; OCE-AN10; HMSCore 6.0.0.306; GMSCore 21.24.18) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 HuaweiBrowser/11.1.2.301 Mobile Safari/537.36' \
>   -H 'accept: */*' \
>   -H 'sec-fetch-site: cross-site' \
>   -H 'sec-fetch-mode: no-cors' \
>   -H 'sec-fetch-dest: script' \
>   -H 'referer: https://wallet.near.org/create/near/2x5XV75ocTg8R35rq5wn2ULfqM5qta5S9gdLo7U4JoR8vMigBNfSSxkfofUL6hcZAiJF3iT9uV3w2R4zagAsLPV9' \
>   -H 'accept-language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7' \
>   --compressed
> ```

By changing **referer** from `https://wallet.near.org/create/near/2x5XV75ocTg8R35rq5wn2ULfqM5qta5S9gdLo7U4JoR8vMigBNfSSxkfofUL6hcZAiJF3iT9uV3w2R4zagAsLPV9` to `https://wallet.near.org`, the JS file could be retrieved sucessfully.

**Comment by think-in-universe** [comment]
The root cause is that browsers like Google Chrome will only send the origin `https://wallet.near.org` to the server, while the Huawei / QQ Browsers will send the entire URL `https://wallet.near.org/create/near/2x5XV75ocTg8R35rq5wn2ULfqM5qta5S9gdLo7U4JoR8vMigBNfSSxkfofUL6hcZAiJF3iT9uV3w2R4zagAsLPV9` to the server, which caused the issue.

One solution is to enforce `strict-origin-when-cross-origin` in html as we did in https://github.com/near/near-wallet/pull/1937

**Comment by think-in-universe** [comment]
Another possible solution is to allow non-origin `referer` on Cloudflare worker, but I didn't take time to investigate yet.
