### ISSUE TITLE
It takes long time to receive the verification code

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#1934]
**Problem**
This is a China-specific issue.

When the Chinese users registered with email, it took about 2 or 3 minutes to receive the verification code. It takes so long and the experience of users is not good enough.

**Expected Behavior**
Users could receive the verification code immediately when registering with email, .

**Steps to reproduce**

1. Register wallet account with email
2. Wait for the verification code

**Comment by stefanopepe** [comment]
Is this issue persistent across all email providers? Or it's specific with some of them, like qq.com?

**Comment by RubyJiao** [comment]
Most of the issues are with qq.com

**Comment by stefanopepe** [comment]
It seems that these email providers apply some extra checks on the emails before forwarding them to the user. This is an example by [Salesforce](https://help.salesforce.com/articleView?id=sf.mc_es_email_deliverability_in_china.htm&type=5).
Will close this issue, let's take it on support channel, and re-open the issue with directives for the dev team on the available mitigations,
