### ISSUE TITLE
Can't receive the 2FA code with email when authorizing transactions

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#1943]
**Problem**
The user can't receive the 2FA code with email when authorizing transactions. He tried many times but it still didn't work.

**Expected Behavior**
Users could receive the 2FA code with email when authorizing transactions

**Steps to reproduce**

1. Send transaction
2. Can't receive the 2FA code with email

**Comment by stefanopepe** [comment]
Did the user open a ticket at https://nearhelp.zendesk.com/ ? 
We can take it from there, and then move here the discussion when it's clear how the developer can reproduce the issue. I used the 2FA email a few minutes ago, and it all worked fine, so we need to further investigate why the user is not receiving it.

Will take this one via direct messages

**Comment by RubyJiao** [comment]
The user did not open a ticket. He found that the 2FA email worked the next day.
