### ISSUE TITLE
Can't send tokens with 2FA enabled

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet#1949]
**Problem**
As a user with 2FA enabled, I can't send fungible tokens or NEAR tokens.

<img width="1029" alt="Schermata 2021-07-23 alle 11 25 33" src="https://user-images.githubusercontent.com/6222429/126756460-50174193-17ac-487c-8e58-17143d67d1bf.png">

**Expected Behavior**
I should be able to send tokens normally, with the usual 2FA process

**Steps to reproduce**

Use https://wallet.staging.near.org and:
1. (if not enabled) enable 2FA on the account (SMS or email is the same)
2. click "send"
3. set the amount and use NEAR as selected token, click "continue"
4. set the recipient and click "continue"
5. click "confirm & send"

**Comment by ihaid** [comment]
Seems like the issue was fixed!

**Comment by MaximusHaximus** [comment]
This has been resolved!
