### ISSUE TITLE
"Load More" for NFT Collections

### ISSUE THREAD

**Issue by corwinharrell** [near/near-wallet#1951]
## Problem

The current implementation of the NFT gallery in the wallet isn't accomodating of larger collections since there is no pagination being used.

## What are we doing about it?

The proposed solution is to add a load more button to each collection. Each collection would display only the 2-4 most recent NFTs received, with an option to load more. Clicking this button would increase the height of the collection container in order to display additional collectibles (+4 each time the user clicks the button).

<img width="617" alt="Screen Shot 2021-07-23 at 9 14 54 AM" src="https://user-images.githubusercontent.com/5934188/126786977-a1b59b0c-4676-4f6a-86a6-7ffbf9a3d976.png">

## Resources

- Figma document: https://www.figma.com/file/Co5Rx8i9Cx4SxgRZv0MUa7/NFTs?node-id=0%3A1

**Comment by corwinharrell** [comment]
@Patrick1904 @MaximusHaximus The designs for the collectibles tab have been updated to include the load more pattern.

**Comment by Patrick1904** [comment]
Closing as this has been released with https://github.com/near/near-wallet/pull/1995
