### ISSUE TITLE
Linkdrop Flag to Skip Claim or Create Account Screen

### ISSUE THREAD

**Issue by mattlockyer** [near/near-wallet#1982]
## Story

![image](https://user-images.githubusercontent.com/321340/127525883-9e74810b-4d32-4dac-9dae-63a3e9b5c52d.png)

## Acceptance Criteria

- [ ] Linkdrop has flag to skip Claim or Create Account Screen
- [ ] Linkdrop with flag takes user directly to "Reserve AccountId" step in the current linkdrop flow
- [ ] Everything else is the same, including redirectUrl which should take them back to the application

## NOTES

- was discussed and agreed upon in Discord as a necessary UI/UX feature since users are leaving apps and "pre-choosing" the option to Create an Account with linkdrop coming from application's server.

**Comment by MaximusHaximus** [comment]
💖  This will be a nice flow for onboarding, I think we can do it in the next sprint :)

**Comment by Patrick1904** [comment]
@mattlockyer while @MaximusHaximus and I were looking into this we realized that there's already support for `?redirect=false` on the `/create` route to 'skip' the linkdrop landing page. 

In order to skip the linkdrop landing page and go straight to selection of account ID, simply switch out `/linkdrop` with `/create` and add `?redirect=false` at the end of the linkdrop URL.

Example: `https://wallet.near.org/create/someFundingContract/someFundingKey?redirect=false`

**Comment by mattlockyer** [comment]
This is good! I'll give it a try ASAP thank you! 👍

Is this also compatible with `redirectUrl`?

**Comment by Patrick1904** [comment]
> This is good! I'll give it a try ASAP thank you! 👍
> 
> Is this also compatible with `redirectUrl`?

Yep it supports a `redirectUrl` too. So could be `https://wallet.near.org/create/someFundingContract/someFundingKey?redirect=false&redirectUrl=https://google.com`

**Comment by mattlockyer** [comment]
Confirmed, working with redirect on testnet. :+1: 

Flow is super smooth now thank you gentlemen! :rocket:

**Comment by Patrick1904** [comment]
@mattlockyer, after further discussion with @MaximusHaximus, we're considering removing the `redirect` param all together. It was only implemented when we launched the `/linkdrop` landing page to support legacy linkdrop that send users directly to the `/create` route. However, it seems that all linkdrop-generating apps have caught up and are creating linkdrop links with the `/linkdrop` param.

The main drawback of removing the `redirect` param all together, would be that any lingering linkdrops using `/create`, won't automatically be redirected to the `/linkdrop` page, and therefore it wouldn't be obvious how to claim a linkdrop to an existing account.

Any thoughts/concerns with that?

**Comment by mattlockyer** [comment]
Can you still create linkdrops that go directly to /create if you DO want to skip the claim/create page?

If so then it's fine to drop redirect param correct?

You're now using:
/linkdrop
Or
/create

To create linkdrops. Instead of using redirect method.

**Comment by Patrick1904** [comment]
> Can you still create linkdrops that go directly to /create if you DO want to skip the claim/create page?
> 
> If so then it's fine to drop redirect param correct?
> 
> You're now using:
> /linkdrop
> Or
> /create
> 
> To create linkdrops. Instead of using redirect method.

Yes exactly. By removing the `redirect` param, you don't have to worry about it. Examples:

Linkdrop for when you want users to **always create a new account**:
https://wallet.near.org/create/someFundingContract/someFundingKey?redirectUrl=https://google.com

Linkdrop for when you want users to be able to **choose between creating a new account, or claim to existing**:
https://wallet.near.org/linkdrop/someFundingContract/someFundingKey?redirectUrl=https://google.com

**Comment by mattlockyer** [comment]
https://giphy.com/clips/rickandmorty-season-3-rick-and-morty-s3e10-s8IyxZUpz5PBcBVEVt

**Comment by Patrick1904** [comment]
> https://giphy.com/clips/rickandmorty-season-3-rick-and-morty-s3e10-s8IyxZUpz5PBcBVEVt

Added a PR here:) https://github.com/near/near-wallet/pull/2004
