### ISSUE TITLE
404 page should rendering on non existing page

### ISSUE THREAD

**Issue by ihaid** [near/near-wallet#1987]
**Problem**
If you go for [https://wallet.staging.near.org/tab=collectibles](https://wallet.staging.near.org/tab=collectibles) you will see the wallet, but the URL is invalid cause it missed `?` before `tab=...`

**Expected Behavior**
404 not found should rendering

**Steps to reproduce**

1.  Go to https://wallet.staging.near.org/tab=collectibles
2. Click `Collectibles` 
3. See the error in console
![image](https://user-images.githubusercontent.com/38665104/127631643-82518134-2e31-4ce5-8cc4-b4a0c9a28b27.png)

**Comment by stefanopepe** [comment]
adding @MaximusHaximus 
Maybe @Patrick1904 or @marcinbodnar can give feedback on this one

**Comment by Patrick1904** [comment]
> adding @MaximusHaximus
> Maybe @Patrick1904 or @marcinbodnar can give feedback on this one

We are currently missing a `404` page. @corwinharrell let me know if you have a `404` page design (or other UX) in mind and I can add it.

**Comment by corwinharrell** [comment]
> > adding @MaximusHaximus
> > Maybe @Patrick1904 or @marcinbodnar can give feedback on this one
> 
> We are currently missing a `404` page. @corwinharrell let me know if you have a `404` page design (or other UX) in mind and I can add it.

np if you could just go ahead and create the route and put some placeholder text at the top of the page I'll follow up and do the design in code.

**Comment by Patrick1904** [comment]
Fixed by @worldclassdev in https://github.com/near/near-wallet/pull/2289 :)
