### ISSUE TITLE
"Explore Apps" block does not show

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#1996]
**Problem**
After closing the "Explore Apps" block, it does not show any more.
<img width="522" alt="297581c653a448f5e1f641949f4633d" src="https://user-images.githubusercontent.com/87597805/128128299-1cf74999-292e-40ca-b8dd-e1b9dbbf63f9.png">

**Expected Behavior**
After closing the "Explore Apps" block, there is anaccess to find and open it again.

**Steps to reproduce**

1. Close the "Explore Apps" block
2. The "Explore Apps" block disappeared

**Comment by Patrick1904** [comment]
Closing as issue is outdated
