### ISSUE TITLE
Cannot view the passphrase of the sub-account created by near-cli

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#2001]
The user created a sub-account by near-cli and did not view the passphrase of it. He want to view the passphrase and log in with it.

We can support the creation of sub-accounts, or allow the user to copy passphrase in the command line.

**Comment by stefanopepe** [comment]
Unfortunately NEAR Wallet is not fully tested with sub-accounts, do we have a Zendesk ticket with this issue?

**Comment by RubyJiao** [comment]
> Unfortunately NEAR Wallet is not fully tested with sub-accounts, do we have a Zendesk ticket with this issue?

No，the requirement is from a Chinese  wechat user.

**Comment by stefanopepe** [comment]
I'll close this one for two reasons:
1. this is blocked by near-cli, as it doesn't support the export of a private key via seed passphrase
2. NEAR Wallet wouldn't be able to recover a sub-account from a raw private key, the only way is to enter the seed phrase
