### ISSUE TITLE
2FA initialization failed on testnet, account got locked down

### ISSUE THREAD

**Issue by danielwpz** [near/near-wallet#2010]
**Problem**
Hey, I tried to enable 2FA on my account `danielwpz.testnet`. I got 2FA successfully turned on, but when I tried to transfer tokens to others an error was thrown: 
```
Querying call/danielwpz.testnet/list_request_ids,AQ4 failed: wasm execution failed with error: FunctionCallError(HostError(GuestPanic { panic_msg: "Multisig contract should be initialized before usage" })). { "block_hash": "FTDouqiRKnSUNJxtBbwwfYHekDsxKk7idKy7M8RagCP9", "block_height": 57483374, "error": "wasm execution failed with error: FunctionCallError(HostError(GuestPanic { panic_msg: \"Multisig contract should be initialized before usage\" }))", "logs": [] }
```

And seems I CANNOT disable 2FA on my account now, so it's ’locked down‘ now :(

**Expected Behavior**
I can successfully enable 2FA and transfer my token with 2FA confirmation.
If I want, I can always turn off 2FA any time.

**Steps to reproduce**

1. Enable 2FA on your account
2. Make a transfer

**Comment by stefanopepe** [comment]
Looping in @marcinbodnar and @MaximusHaximus as we introduced some changes with the fungible token transfers, and it may have had an impact on the Testnet instance

**Comment by stefanopepe** [comment]
@ihaid please test this loop, I tried myself but all worked normally

**Comment by ihaid** [comment]
@stefanopepe I can't reproduce it

**Comment by marcinbodnar** [comment]
@stefanopepe Tested, I enabled 2FA, sent Nea, sent FT, after that deactivated 2FA - didn't receive any error.

**Comment by danielwpz** [comment]
😂, do you guys know if there is another way to disable 2FA?

**Comment by danielwpz** [comment]
btw i'm using email as 2FA method, are u guys using phone num?

**Comment by stefanopepe** [comment]
> btw i'm using email as 2FA method, are u guys using phone num?

We can try to change the email in the system and see if it works. Please open a ticket at https://nearhelp.zendesk.com/hc/en-us we'll take it from there. Specify that you want to change the 2FA, and it's a testnet account, so we don't begin the throughout verification process

**Comment by danielwpz** [comment]
cool, will do
