### ISSUE TITLE
Asia only: staking page failed to load

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#2011]
**Problem**
The staking page failed to load in China. When the staking link is opened, it would request this link [https://raw.githubusercontent.com/frol/near-validators-scoreboard/scoreboard-mainnet/validators_scoreboard.json](https://raw.githubusercontent.com/frol/near-validators-scoreboard/scoreboard-mainnet/validators_scoreboard.json) In China, users can not open github link without vpn. It may be the reason that it is slow to open the staking link. When users facing this problem, we used to introduce them to open the vpn and try again. The staking page would work fine with vpn, but it may not be the good way to solve the problem. A user who is a developer also suggests that if we could do anything with the request link to provide a better experience of using NEAR Wallet.
![f7b604e3a096976f2fa64d1496f3d98](https://user-images.githubusercontent.com/87597805/128464207-04a98fef-83b1-487b-9231-a90b23308981.jpg)

**Expected Behavior**
The staking page would be loaded quickly.

**Steps to reproduce**

1. Click "staking" in NEAR Wallet
2. It shows noting detailed

**Comment by stefanopepe** [comment]
@MaximusHaximus this is the usual latency/filtering problem with our wallet helper and indexer.

It seems we can't give up on localizing a node there, at least for the trustless components (indexer&RPC), eventually using a separate domain

**Comment by MaximusHaximus** [comment]
This is definitely something that we can resolve, either by querying the data on-chain (if possible), via our indexer (more likely), or by proxying this json file through the `near-contract-helper` REST API (as a last resort).

I'll try to get this resolved in this sprint. <3 thanks for the report @RubyJiao !

**Comment by MaximusHaximus** [comment]
@RubyJiao We are now loading the list of historic validators from the contract helper, no longer referencing github user content.  This should be usable without a firewall for users inside of China now (it's live on mainnet!)
