### ISSUE TITLE
Wrong Lockup information (triggered by Lockup Core Contract update)

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet#2014]
**Problem**
Recently, @frol and @telezhnaya updated the [lockup contract](https://github.com/near/core-contracts/tree/master/lockup), introducing changes that break how the wallet is measuring the vesting of a lockup contract.

Example:
NEAR Wallet display: https://wallet.near.org/profile/scarce1.near (shows all tokens vested)
Account-lockup display: https://near.github.io/account-lookup/#scarce1.near

**Expected Behavior**
NEAR Wallet should display the correct vesting schedule for lockup contracts

**Steps to reproduce**

1. open https://wallet.near.org/profile/scarce1.near to see "0 locked" tokens
2. open https://near.github.io/account-lookup/#scarce1.near to see the correct value instead

Here the rewritten logic to calculate the lockup vesting and available funds: https://github.com/near/account-lookup/commit/1ca44052789fed57e40d634402ba7d4625b7aa21

**Comment by stefanopepe** [comment]
@frol is this breaking change impacting the display of existing lockup accounts? Or it will be needed going forward, and we don't have to fix this "asap"?

**Comment by telezhnaya** [comment]
@stefanopepe we hope that it's finalized, so it's better to fix that.

FYI: for now, these are only 3 accounts reproducing this bug: `scarce1.near`, `crypsterio.near`, `marcusr.near`. All of them were created on August 6th.

**Comment by frol** [comment]
@stefanopepe There is nothing wrong with lockup. No breaking changes were introduced to the contract. The problem is the buggy JS display implementation, which we finally replaced with a line-by-line translation of lockup (Rust) implementation into JS. Wallet should take the implementation and also replace the previously taken buggy version of account-lookup.

**Comment by stefanopepe** [comment]
All clear! My concern was for previously deployed lockups, given the number of impacted accounts I'll have @MaximusHaximus manage the priority with other short-term work in the pipeline.
