### ISSUE TITLE
The NFT droplink can not be opend

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#2033]
**Problem**
The Chinese user scanned a NFT QR code and opened the droplink. 
![image](https://user-images.githubusercontent.com/87597805/129153945-e9ebd133-c576-4f9b-bf26-70d77dffe3b9.png)

After he clicked "create or log in to the NEAR account", the page showed like this, so the user failed to claim NFT. 
![573c45415093a8e7ba624c994e32a43](https://user-images.githubusercontent.com/87597805/129151658-fa9bbc6c-46fa-4f24-b1b5-c17c579c16f0.jpg)
Here's one of hie QR code.
![image](https://user-images.githubusercontent.com/87597805/129153479-a7144980-96ea-4683-99d7-4947970b447a.png)

**Expected Behavior**
After he clicked the "create or log in to the NEAR account", the page could be opened and go to the next page.

**Steps to reproduce**
1. Scan a NFT QR code in wechat
2. Open the page in Chrome browser 
3. Click "create or log in to the NEAR account"
4. It shows like this 
![573c45415093a8e7ba624c994e32a43](https://user-images.githubusercontent.com/87597805/129151658-fa9bbc6c-46fa-4f24-b1b5-c17c579c16f0.jpg)

**Comment by stefanopepe** [comment]
I tested it myself, creating the account `nft-test01.near` and I got a different error:

`Querying access_key/drop.hhsviewer.near/ed25519:GAVrJSFY85FyJFXxvFYHPSGuBHgPNi3jeLHbmUY358vt, failed: access key ed25519:GAVrJSFY85FyJFXxvFYHPSGuBHgPNi3jeLHbmUY358vt does not exist while viewing. { "block_hash": "4eKiFH9MDBnjZoqMtxaPWQAxAJzhqwjVkxLJquGKgVNs", "block_height": 45066594, "error": "access key ed25519:GAVrJSFY85FyJFXxvFYHPSGuBHgPNi3jeLHbmUY358vt does not exist while viewing", "logs": [] }`

It seems that the login didn't go through properly, are we sure it's a problem of NEAR Wallet? Maybe @think-in-universe can assist with more debugging information

**Comment by think-in-universe** [comment]
@RubyJiao @stefanopepe this seems to be an issue of hhs.art, not NEAR wallet. 

let me confirm with Ruby later.

**Comment by Patrick1904** [comment]
Closing as issue is outdated
