### ISSUE TITLE
Tracking for login on NEAR Wallet using a mobile device and the QR code

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/near-wallet#2045]
Question to Answer: 
How frequently the QR login feature is used? 
Success rate for this method of login? 
How it impact DAU/WAU/MAU?

End Result: 
1. Event --- Clicked on View Mobile Code on user wallet dashboard
2. Event --- Clicked reveal QR code
3. Event --- Successfully Logged in using QR code
4. Event --- Failed to Login using QR code, with property _error_

Need by: 
August 30

**Comment by Patrick1904** [comment]
Closing as issue is outdated
