### ISSUE TITLE
Wallet Onboarding: Coin-op 1.5

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet#2050]
## Context

In order to scope down #2012, this issue represents a non-smart-contract version of the onboarding flow, with the goal to re-enable the coin-op onboarding flow sooner rather than later

## Story

As a Wallet Manager who needs to keep the coin-op up and running, I want to introduce additional protection for the 0.02 tokens so I can better support real users who are creating a NEAR account.
As a new Wallet user, I want to choose the name of my account and complete the onboarding process without the friction of the implicit account creation flow.

## Acceptance Criteria

- [ ] Users who used email or mobile number to create their wallet skip the funding step and get to dashboard with 0.02 tokens
- [ ] If a user decides to use the seed passphrase recovery method, the email or mobile number are requested anyway
- [ ] If a user doesn't want to disclose such information, they can fall back to the legacy account funding process at any moment
- [ ] Works with linkdrops
- [ ] Works with Ledger

## Unhappy Path
User is stuck waiting for an SMS or email and can't create the account

## Assets

Figma Link: https://www.figma.com/file/NKZYW9B3HkYnMKH0E5NjKr/2050-Coin-op-1.5?node-id=350%3A2933
## NOTES

Needs validation by @MaximusHaximus (backend work) and @Patrick1904 (frontend work)

**Comment by danielwpz** [comment]
hi this looks good, is there any progress on this now?

**Comment by corwinharrell** [comment]
@danielwpz hey Daniel, design for this is wrapping up and our aim is to get it completed within our current sprint. Stay tuned!

**Comment by Patrick1904** [comment]
Closing as this was shipped in https://github.com/near/near-wallet/pull/2099
