### ISSUE TITLE
Add the link of the guide of creating an account on create page 

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#2061]
As a new user, I need a guide of creating an account. In this way, I could know how to do step by step, and I could avoid some wrong operations.

We could add the guide link on this page.
https://nearhelp.zendesk.com/hc/en-us/articles/1500002248242-Creating-a-NEAR-Wallet-account
![image](https://user-images.githubusercontent.com/87597805/130909587-f9575d3a-366f-42ed-a1a2-2150c58b76ce.png)

**Comment by stefanopepe** [comment]
I'm closing this one, as #2099 (Coin-op 1.5) will remove this specific blocker for users adopting email/sms
