### ISSUE TITLE
Transfer NFTs

### ISSUE THREAD

**Issue by think-in-universe** [near/near-wallet#2071]
## Story

As a NEAR user who owns a number of NFTs, I want to transfer one of my NFTs to other users so I can enable more scenarios regarding NFTs.

## Acceptance Criteria

- [ ] In the `Collectibles` tab, provide an button or link to transfer the specific NFT
- [ ] A NFT transfer workflow is designed to make the transfer process easy to use
- [ ] Mobile ok
- [ ] Tested

## Assets

- Mockups: https://www.figma.com/file/Co5Rx8i9Cx4SxgRZv0MUa7/NFTs?node-id=426%3A387

## NOTES

- The NFTs transfer feature is frequently requested by not only NFTs users but also developers.

**Comment by corwinharrell** [comment]
@think-in-universe I've updated our Figma mockups to show how new might go about implementing a flow for transferring NFTs: https://www.figma.com/file/Co5Rx8i9Cx4SxgRZv0MUa7/NFTs?node-id=426%3A387

A couple things to note:

1. Each NFT should ideally have a details page that displays a larger preview image and key metadata. Initially, this would just be title, description, and creator/owner IDs, but this would evolve to show different characteristics of the NFT, such as unique traits and rarity.

2. From this page, the user can choose to Transfer the NFT. They would then enter the recipient address, and would proceed to confirm the transaction.

3. Once complete, they would be redirected the collectibles tab on the dashboard.

Content in the mockups is placeholder. @think-in-universe if you have any questions or feedback about any of this just let me know, but for the most part, the flow is fairly similar to a fungible token transfer. Questions about the location and specific components used here should be directed to @Patrick1904. Aside from the NFT details page, all the components here should be pre-existing.

**Comment by Patrick1904** [comment]
@think-in-universe you'll be able to re-use some of the UI that's being shipped here: https://github.com/near/near-wallet/pull/2166

Please ping me if you have any questions.

**Comment by danielwpz** [comment]
The design looks good to me! However two questions need to be clarified before we are good to develop.
1. How could we find the creator ID ? It's currently not in the metadata. Since we don't have a standardized `mint` function, it could be hard to tell who firstly created the NFT.
2.  There are two external links in the `Proof of Authenticity` section (NEAR transaction and View on IPFS). What pages should they link to? And I suppose the `View on IPFS` link should only appear if `reference` exists in NFT metadata?

**Comment by danielwpz** [comment]
PR: https://github.com/near/near-wallet/pull/2205

**Comment by Patrick1904** [comment]
Closing as issue is outdated
