### ISSUE TITLE
Display Release Notes

### ISSUE THREAD

**Issue by corwinharrell** [near/near-wallet#2074]
## Problem

Users currently don't have any way to stay up to date about the changes occurring in the wallet with every release. Some changes may come as a surprise to users who don't interact with their accounts daily.

## Solution

With each release, a release notes summary should be displayed to the user when visiting the wallet after a major release. 

The release notes should contain:

- [ ] A version number
- [ ] A link to the full release on Github if they decide they want to go into more depth around the changes
- [ ] A summary each for `New Features`, `Enhancements`, and `Fixes` that made it into the most recent release

The release notes component should:

- Be permanently dismissed once closed by the user
- Pull in markdown / metadata from a source on Github (TBD by @MaximusHaximus)
- Be scrollable and restricted with a max-height on desktop (full-screen on mobile)

## Resources

Design: [Figma Document →](https://www.figma.com/file/wOx1u3M1RAyrFjVbqC9OYG/Release-Notes-Modal?node-id=205%3A143)

<img width="947" alt="Screen Shot 2021-08-31 at 2 50 12 PM" src="https://user-images.githubusercontent.com/5934188/131559383-49183018-a70d-42c7-9abd-b8ff7a14e0d5.png">

**Comment by stefanopepe** [comment]
This is blocking the new release on staging, as it will communicate the available balance changes to the users.
