### ISSUE TITLE
Wrap / Unwrap NEAR from within the Wallet

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#2089]
Some users are confused about how to swap near into wnear. Some users get wnear in their wallets because of various reasons，but they don't know how to swap wnear into near. Basicly, wnear is used for all Defi projects. It is necessary to add a feature of swapping near and wnear into each other like that in the pulse, although users can swap tokens on ref.finance and pulse. It is convinence for users to swap near and wnear.

**Comment by RubyJiao** [comment]
**Summary
Some users are confused about how to swap near into wnear. Some users get wnear in their wallets because of various reasons，but they don't know how to swap wnear into near. Basicly, wnear is used for all Defi projects. It is necessary to add a feature of swapping near and wnear into each other like that in the pulse, although users can swap tokens on ref.finance and pulse. 

Desired outcome
As a user, I want to swap near and wnear on the wallet page instead of another Dapp. In this way, I can swap tokens directly and instantly. I don't have to deposit and withdraw tokens in another Dapp and swap tokens.
The success of this feature will be measured in terms of amount of tokens and times of swap.

How will it work?
The feature will be added on the wallet page. We could take the UI as reference.
![4d4ccdcf52c1b97a74b8252e569a27f](https://user-images.githubusercontent.com/87597805/133211953-35b89546-f31c-452f-83ad-d1d893573219.jpg)

**Comment by Patrick1904** [comment]
Closing as issue is outdated
