### ISSUE TITLE
Display Options to Create/Purchase Fungible Tokens

### ISSUE THREAD

**Issue by corwinharrell** [near/near-wallet#2112]
## Problem 
Discovery of the NEAR ecosystem through the Wallet is currently limited. Users don't have many ways to get acquainted with the options for participating in NEAR DeFi for acquiring the requisite tokens. 

## Intended Outcome
As a user interested in DeFi, I want a simple way to navigate to a location where I can get acquainted with the DeFi options on NEAR.

The success of this feature will be measured in terms of absolute adoption of fungible tokens, and as a second-order effect in terms of engagement (DAU/MAU).  

## How will it work?  
Today, NEAR Wallet's dashboard contain a list of fungible tokens, with just a link to NEAR Explorer. This feature adds a button to the "Explore" banner that points directly to the DeFi subsection of awesomenear.com: https://awesomenear.com/categories/defi/

The wallet needs to remain an unbiased and neutral party. Adding direct links to specific applications in the context of our UI leans towards favoritism and bias. Until we have more robust discovery mechanisms in place within the wallet, we should avoid pointing directly to specific projects/products, especially if the list of options in a particular context (eg DeFi) is anticipated to grow rapidly.

<img width="1320" alt="Screen Shot 2021-09-14 at 10 07 31 AM" src="https://user-images.githubusercontent.com/5934188/133273023-6d31b09c-d553-4103-8d18-fa1869c08167.png">

**Comment by corwinharrell** [comment]
Link to feature: https://wallet.productboard.com/feature-board/planning/features/9146799

**Comment by corwinharrell** [comment]
@stefanopepe I've taken the liberty of making some changes to the scope and solution of this issue. Ultimately, what we are trying to do here is increase engagement of users with NEAR DeFi. Until we have a robust discovery mechanism in place, I don't think it's appropriate or non-partisan for us to be pushing users to specific products. Happy to hear if your disagree, but I think this solution is sufficient until the discovery portion of the wallet matures.

**Comment by stefanopepe** [comment]
It's not the same as landing users on Ref.finance or tkn.farm, there's one more click in the middle, but it's very good to achieve the desired goal: track who is clicking "explore DeFi" and build a set of signals that will justify a more structured approach to this feature class in the future.

Your solution looks good to me =)

**Comment by MaximusHaximus** [comment]
@marcinbodnar We should have Mixpanel tracking for both buttons so we can compare which are clicked most often :). 
@TiffanyGYJ What should the event names be when people click on the `Explore Apps` and `Explore DeFi` buttons?

**Comment by TiffanyGYJ** [comment]
> @TiffanyGYJ What should the event names be when people click on the `Explore Apps` and `Explore DeFi` buttons?

I think _Clicked Explore Apps_ and _Clicked Explore DeFi_ are pretty good
