### ISSUE TITLE
Display Total Account Value in the balance breakdown

### ISSUE THREAD

**Issue by heycorwin** [near/near-wallet#2138]
## Problem

With the recent updates to balances and the decision to prioritize the available balance in the wallet, some users express that the Total Balance figure, while maybe not needed front and center, is still valuable in saving them the headache of doing extra math to determine the sum of their account and staking balances.

<p></p>

## Solution

The balance breakdown should be revised to reflect the total value of the account, including funds being staked. This doesn't have to be the primary balance of the wallet, since most users are primarily concerned with seeing the funds they have available to transfer, but should stil be accounted for and displayed for convenience.

**Comment by corwinharrell** [comment]
Link to feature: https://wallet.productboard.com/feature-board/planning/features/9484609

**Comment by Patrick1904** [comment]
Closing as issue is outdated
