### ISSUE TITLE
error：Failed. reCAPTCHA verification failed

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#2171]
**Problem**
2 users failed to create an account by email. It showed"Failed. reCAPTCHA verification failed，please try again."
![116eaa8e4eeb43474c2328eeb1b2b8c](https://user-images.githubusercontent.com/87597805/135231511-b38cc9fd-a91d-490c-b68e-2a73032336e0.jpg)

**Expected Behavior**
Users can succeed to create an account by email

**Steps to reproduce**
1. Input the email address(on this page above)
2. Click "continue" button

**Comment by Patrick1904** [comment]
Closing as issue is outdated
