### ISSUE TITLE
Adding E2E tests for lockups on wallet

### ISSUE THREAD

**Issue by esaminu** [near/near-wallet#2180]
As we begin to add e2e tests for lockup functionality on the wallet I'd like to raise / confirm the following questions:
- In order to add E2E tests for wallet lockup flows we need to use `testingLockup.{accountId}`  and build the web server with the `REACT_APP_USE_TESTINGLOCKUP` env variable set. We can't test `{sha(accountId)[:40]}.lockup.near` accounts since the test suite can't create them. This also means we can't test lockups in prod (testnet/mainnet..) since this env variable is not set. Additionally it means we can only have one lockup per account since we are using the predictable naming. Maybe it would have been possible to query for all lockups with `owner_account_id` as the selected account? If this was the case we could have deployed a lockup anywhere and validated our test cases in prod.
- @stefanopepe what assertions would we like to make and what scenarios would we like to test. Ideally we would also like to repro https://github.com/near/near-wallet/issues/2014. Any config values and info on how to will be helpful.

**Comment by stefanopepe** [comment]
From a product perspective, we have to check four things:
1. if present - the lockup account appears in the wallet profile page
2. the profile page shows the correct amounts (locked, unlocked and vesting schedule)
3. the wallet correctly manages the available balance when signing transactions
4. the wallet correctly withdraw all funds and removes the lockup when there's nothing more to "vest"

I understand the issue on Mainnet, it's not possible to deploy, check and clean up a new lockup every time the test is run. What if we periodically issue a lockup contract with a predefined amount and duration?
E.g. 10 near locked for 4/8 weeks, deployed at a regular cadence every 2 weeks, rotating the funds using transfers and withdrawals? 
All that I know about #2014 is written in the issue itself, I suggest asking @frol or @telezhnaya if they have any docs or internal notes that can help us deploy either "a wrong lockup" or a good one, and check the behavior in the wallet.

**Comment by stefanopepe** [comment]
Adding to the above these additional staking-related tests that I didn't mention:
1. select the staking pool
2. deposit and stake funds to it
3. unstake funds
4. withdraw funds after the expected unbinding period
5. unselect staking pool and select a new one
