### ISSUE TITLE
Handle invalid contractId on /login/ request

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#219]
**Problem**
If the contractId is wrong in a /login/ (e.g. ```login/?contractId=THISDOESNTEXIST```) request from an app, a useless access key is created (or is it?) and the app is forced to identify the error with little to no information.

**Expected Behavior**
If a contractId is invalid, we should prevent the user from going through the /login/ step, and return an error to the app.

**Steps to reproduce**

1. Go to corgis.nearprotocol.com
2. Select "Login w/ Near"
3. Edit the contractId argument in the url to ```contractId=notrealid``` and resubmit
4. Complete login
5. Try to generate a Corgi

**Comment by kcole16** [comment]
## Acceptance Criteria

Login `/login` 
- [ ] If `contractId` does not exist, the user is displayed a warning message (see below) in a modal
- [ ] Clicking "Return to App" in the modal redirects the user to the referring application

**Warning Message**

"The contract `<contractId>` does not exist. This may be an issue with the application you are trying to use, or this contract may have been deleted. You will be redirected back to the application"

**Comment by vgrichina** [comment]
question from @marcinbodnar 
> how can we check if contract_id from param is valid?

It has same constraints as account Id + it also needs to be an existing account (i.e. we'd want to query near node for that account). Can be done similarly to user profile component I think (after Chad changed it to work with any account vs current account).
