### ISSUE TITLE
Add support for custom HD path when enabling Ledger as a recovery method

### ISSUE THREAD

**Issue by Patrick1904** [near/near-wallet#2200]
## Problem
The Wallet currently supports _importing an account_ using a custom HD path, however, it does not support _enabling Ledger as a recovery method with a custom HD path_.

#### What are we planning to do about it?
Add support for custom HD path when enabling Ledger as a recovery method.

## Acceptance Criteria
- [ ] Multiple accounts managed with single Ledger but different public keys

**Comment by alexauroradev** [comment]
Upvoting this issue.

**Comment by Patrick1904** [comment]
@gutsyphilip all the UI exists for this and can be grabbed from the `/sign-in-ledger` route. We're adding the `LedgerHdPaths.js` component for whenever the user is setting up Ledger for a **new** or **existing account**. This means that the current routes that are missing the HD path selector are: `/setup-ledger/:accountId` and `/setup-ledger-new-account` 

Please let me know if you have any questions:)
