### ISSUE TITLE
How to derive `account_id` from key pair?

### ISSUE THREAD

**Issue by ghost** [near/near-wallet#2204]
According to https://github.com/near/nearcore/blob/master/core/crypto/src/signer.rs#L53-L66

expects `account_id` as argument.

According to https://wallet.near.org/recover-account deriving `account_id` from seed does not require having `account_id`

What is or where is the explanation for this?

**Comment by bowenwang1996** [comment]
Account id has nothing to do with the keypair itself unless you are referring to implicit accounts.
