### ISSUE TITLE
There are errors in the console and blank page (https://wallet.testnet.near.org/authorized-apps) after adding app with a new key

### ISSUE THREAD

**Issue by SergZen** [near/near-wallet#2207]
**Problem**
I see errors in the console and a blank page (https://wallet.testnet.near.org/authorized-apps) for the testnet wallet after adding the app with a new key the first time.

https://prnt.sc/1voxpo8

This code creates many requests for function because call yourself with the same params:

https://prnt.sc/1voxmn5

**Expected Behavior**
After adding the app with a new key I will see (https://wallet.testnet.near.org/authorized-apps) with info about apps

**Steps to reproduce**
1. Remove key ed25519:9us69knzU25GvpkjSgWrBeTpr8sPmyTMkg2e6GMxCq6z if you have it in your apps
2. Add a new app from the link (https://wallet.testnet.near.org/login?title=NEAR%20Bot&public_key=ed25519:9us69knzU25GvpkjSgWrBeTpr8sPmyTMkg2e6GMxCq6z&contract_id=test.testnet)

**Comment by MaximusHaximus** [comment]
Thanks for the report @SergZen 
We're shipping a fix for this now 💖

**Comment by MaximusHaximus** [comment]
Fix has been landed to mainnet -- thanks for the report @SergZen :)
