### ISSUE TITLE
Removing lockup account breaks /staking tab

### ISSUE THREAD

**Issue by AngelBlock** [near/near-wallet#2210]
**Problem**
Removing lockup account by utilising Wallet feature to move funds (green banner) breaks /staking path

<img width="476" alt="Screenshot 2021-10-21 at 10 45 10" src="https://user-images.githubusercontent.com/80400686/138253381-8d69dad7-5aa9-43d5-9cc5-55db33f7a3ef.png">

**Expected Behavior**
Should display staking pools, but showing an empty page

**Steps to reproduce**

1. When lockup term is up, go to /profile
2. You will see the green banner `You have XXX available to withdraw from your lockup!`
3. Click on Transfer to wallet
4. Accept add full access key to lockup
5. Accept delete lockup account
6. Go to /staking path.
7. Empty page is shown.

**Comment by MaximusHaximus** [comment]
@esaminu Could you take a look into this and make sure we have an e2e test that covers this case?

**Comment by marcinbodnar** [comment]
Fixed in #2247
