### ISSUE TITLE
Testnet Wallet unable to display airdrop/linkdrop link.

### ISSUE THREAD

**Issue by AngelBlock** [near/near-wallet#2211]
**Problem**
A user tries to utilise the linkdrop link to claim funds/account on the **`TESTNET`** wallet, but instead showed an empty page
Works on mobile phone

**Expected Behavior**
Should show the claim form

**Steps to reproduce**

1. Go to the claim link https://wallet.testnet.near.org/linkdrop/abcdeabcdeabcdeabcdeabcdeabcdea.eclipseer.linkdrop.testnet/4YzGcHohEEz4gbZU34egsHCAdiucfdMXrCAM64Pa8qVb6qA5h41MySKCL5kyZ9dhFgu5EaEKxWgNoVYZwq3bFyy4 
2. Empty page is displayed

**Comment by stefanopepe** [comment]
@AngelBlock do you have a source to create these linkdrops, so we can embed them in the test route?
cc @esaminu

**Comment by stefanopepe** [comment]
Fixed ♥️
