### ISSUE TITLE
walletConnection.requestSignIn() shows `full access` key warning on testnet

### ISSUE THREAD

**Issue by paouvrard** [near/near-wallet#2229]
**Problem**
walletConnection.requestSignIn() creates a `full access` key on testnet.
![image](https://user-images.githubusercontent.com/29397451/140260424-5dff716f-4ff5-42d3-b127-3f5834f5ff54.png)
https://github.com/near/near-wallet/blob/78054302312d743769febb061bd02808e6b00ce3/packages/frontend/src/routes/LoginWrapper.js#L14
Here I see only 2 kinds of login access types, is there a new way to login without creating access keys ?

**Expected Behavior**
Don't create any access keys when requestSignIn() just to get the account id.

**Steps to reproduce**
Go to testnet.rainbowbridge.app and login with NEAR account.
On testnet a full access key will be created.
On mainnet (rainbowbridge.app) it doesn't create an access key which is the expected behavior.

**Comment by Patrick1904** [comment]
> **Problem** walletConnection.requestSignIn() creates a `full access` key on testnet. ![image](https://user-images.githubusercontent.com/29397451/140260424-5dff716f-4ff5-42d3-b127-3f5834f5ff54.png)
> 
> https://github.com/near/near-wallet/blob/78054302312d743769febb061bd02808e6b00ce3/packages/frontend/src/routes/LoginWrapper.js#L14
> 
> 
> Here I see only 2 kinds of login access types, is there a new way to login without creating access keys ?
> **Expected Behavior** Don't create any access keys when requestSignIn() just to get the account id.
> 
> **Steps to reproduce** Go to testnet.rainbowbridge.app and login with NEAR account. On testnet a full access key will be created. On mainnet (rainbowbridge.app) it doesn't create an access key which is the expected behavior.

Thanks @paouvrard for reporting this UI bug on the testnet wallet. Please be assured that no full access keys are created, but UI is incorrectly saying that.
