### ISSUE TITLE
Broke with shields up Brave for Android

### ISSUE THREAD

**Issue by mattlockyer** [near/near-wallet#2263]
**Problem**

Brave on Android shields up gives blank page.

**Expected Behavior**

Page loads.

**Steps to reproduce**

1. Brave on Android with shields up
2. Open wallet.near.org

Obviously some third party JS e.g. probably mixpanel or something like this has been made critical path and is throwing exception while wallet is loading.

![20211123_045829-ANIMATION](https://user-images.githubusercontent.com/321340/143028725-789fdd0a-7964-4623-a117-0868044e6c24.gif)

**Comment by MaximusHaximus** [comment]
Thanks for the report @mattlockyer!  I'm unable to reproduce this one, even with shields up and both Mixpanel and Sentry being blocked, the UI continues to function as expected.  Is there any additional details that you can get from your Brave browser about what exactly is being blocked? A blank screen indicates either our JS bundle is not loading or something inside of our rendering loop is throwing an error -- do you have any console error output by any chance that might provide a stack trace indicating where the rendering is failing and why?

**Comment by mattlockyer** [comment]
Desktop Brave, Linux, Shield Down

Third Party Scripts Blocked?


![image](https://user-images.githubusercontent.com/321340/143085269-7ee68fb4-bcd1-4871-b695-16597cc6aaab.png)

**Comment by mattlockyer** [comment]
Turning OFF uBlock Origin on my desktop fixes this.

However, on my android, shields up fails - probably blocking the third party script delivered via the **cloudflare workers URL**.

**Comment by stefanopepe** [comment]
@MaximusHaximus @mattlockyer is this still an issue?

**Comment by mattlockyer** [comment]
Appears to work now. Not sure what changed.
