### ISSUE TITLE
Wallet translation (Italiano)

### ISSUE THREAD

**Issue by crypto-credit** [near/near-wallet#2267]
I am involved in setting up a new guild to promote NEAR to the italian speaking community. To make it easier to onboard new users it would be great to provide the option to select Italiano in the wallet.

We have bi-lingual members in our group who would be interested to help with translation from English to Italiano

I posted on the forum - https://gov.near.org/t/proposal-near-wallet-upgrade/8936/2?u=cryptocredit

**Comment by stefanopepe** [comment]
Ottima idea!

We are working to structure this type of contribution, biggest question mark is the QA around too long words that may break the UI

**Comment by stefanopepe** [comment]
Don't miss the opportunity to leave your comments here: https://github.com/near/near-wallet/discussions/2293

**Comment by crypto-credit** [comment]
Hi @stefanopepe just wanted to let you know that the Italiano translation is finally finished... all 1560 lines of code!

What do we need to do next?

**Comment by EveFitz** [comment]
[translations.txt](https://github.com/near/near-wallet/files/8398861/translations.txt)
This is the translation of the NEAR Wallet in italian, hope everything is alright, if not just say!

**Comment by crypto-credit** [comment]
Any update on when to expect the Italian version to be available?
