### ISSUE TITLE
Improve Release Notes

### ISSUE THREAD

**Issue by marcinbodnar** [near/near-wallet#2269]
If we want to add/show Release Notes frequently, we need to consider that the user can enter Wallet after a few releases happened. Considering that, the solution with showing release details in modal will not work, because a user will see the latest release information only.

We should show a general modal including information that the new release is ready, and a link to the release details page, where all releases will be listed with detailed information.

Additionally, we can consider, storing release text in the .md file.

**Comment by marcinbodnar** [comment]
@MaximusHaximus What do you think about @corwinharrell proposition?
`I think it makes the most sense to pull release notes content from a .md file that gets reviewed and then committed with each release. `
https://near--inc.slack.com/archives/C02L5DSRL8G/p1637787040158300?thread_ts=1637781567.148700&cid=C02L5DSRL8G

**Comment by stefanopepe** [comment]
I like the concept of replacing an existing .md file (e.g. RELEASE.md), as linking to previous versions must include the release hash.
