### ISSUE TITLE
Unable to open wallet

### ISSUE THREAD

**Issue by tdogj21** [near/near-wallet#2270]
## Story
I'm trying to load near into my near wallet. I'm unable to because no wallet is excepting the ENS. Also, the NEAR Wallet itself will not open. I've attached screenshots below. I cannot get pass this screen. 

Also. I'm sending errors that are showing up in the Dev tools

As a USER who PRECONDITIONS, I want to DO_THING so I can ACCOMPLISH_GOAL.
![Dev Load Error](https://user-images.githubusercontent.com/75482149/143621590-a56d9d5e-2175-49f2-b46b-16eff273c0ca.png)
![Near Wallet Fault](https://user-images.githubusercontent.com/75482149/143621596-346620af-ace4-49e4-bb55-e702cf202979.png)

I want to add funds so that I can get to my NFT that is inside my NEAR Wallet

[wallet.near.org-1637953098561.log](https://github.com/near/near-wallet/files/7610368/wallet.near.org-1637953098561.log)

Below is the text of the attachment link

src.680ada80.js:3407 lockupAccountId e00d687f9ce2fb52c60917fd548139eca2d0ce27.lockup.near
src.680ada80.js:3407 lockupAccountId e00d687f9ce2fb52c60917fd548139eca2d0ce27.lockup.near
DevTools failed to load source map: Could not load content for chrome-extension://hnfanknocfeofbddgcijnmhnfnkdnaad/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://hnfanknocfeofbddgcijnmhnfnkdnaad/requestProvider.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://hnfanknocfeofbddgcijnmhnfnkdnaad/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://hnfanknocfeofbddgcijnmhnfnkdnaad/requestProvider.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for https://content.near-wallet.workers.dev/ntl/mainnet/src.680ada80.js.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://content.near-wallet.workers.dev/ntl/mainnet/src.1bb9d401.css.map: Load canceled due to load timeout

## Acceptance Criteria

- [ ] AC1
- [ ] AC2
- [ ] Mobile ok
- [ ] Tested

## Assets

- Mockup: 

## NOTES

-

**Comment by stefanopepe** [comment]
Thank you for your request. We are already handling this one via Zendesk at nearhelp.zendesk.com/
