### ISSUE TITLE
adding Turkish language choice to Near Wallet

### ISSUE THREAD

**Issue by KriptoRaptor** [near/near-wallet#2271]
As a Near community member, I offer adding Turkish version of the wallet. 

Translation is a part of my Profession, I'm a full time crypto guy and I'm Turkish native I want to have this task.

according to some research Turkish Crypto users are in top 10 and that many Turkish People aren't so good in English
this will help us reach new Turkish crpto communities make it easier for them to claim an account and will support our claim that Near Protocol is a user friendly Decentralized Blockchain Protocol

links. [ Crypto Usage in Turkey](https://news.bitcoin.com/latin-america-and-turkey-have-the-most-cryptocurrency-users-poll-shows/)

**Comment by MaximusHaximus** [comment]
Howdy! 

We'd love the help with translations!  

You can see our existing translation files at https://github.com/near/near-wallet/blob/9f358d76cea6d2f12750b2874d5dadb187805db6/packages/frontend/src/translations/en.global.json
If you create a `tr.global.json` file that contains Turkish equivalent translations for the values in `en.global.json`, we'd be happy to merge it and get Turkish language support added to the wallet! :). 

We can take care of adding the loading of the file to the frontend if you'd like, but if you are curious/motivated, you could add the references necessary.  We will be adding an entry for the language around here: https://github.com/near/near-wallet/blob/f27ce083ae36d1f8f2b130179c65120af239ffa9/packages/frontend/src/components/Routing.js#L131-L138 and then importing your new file and adding a single line of code around here:  https://github.com/near/near-wallet/blob/f27ce083ae36d1f8f2b130179c65120af239ffa9/packages/frontend/src/components/Routing.js#L162-L161 to make it load the Turkish translations :)

**Comment by stefanopepe** [comment]
Don't miss the opportunity to leave your comments here: https://github.com/near/near-wallet/discussions/2293

**Comment by KriptoRaptor** [comment]
well Daryl tbh i still have no clue about how to do it using your tools. 

 I can attach SS of each page and paste corresponding Turkish texts into a .doc file ?? 😃  or wonder if i can access the offline version with a software and edit all the text on it just like that 🤔

**Comment by marcinbodnar** [comment]
Hey @KriptoRaptor 
Added necessary changes in this PR:
https://github.com/near/near-wallet/pull/2319

Turkish version of texts is available in this file:
https://github.com/near/near-wallet/blob/c0385fe4b7306b88a62cf86ec42eb6c85ad97521/packages/frontend/src/translations/tr.global.json
(packages/frontend/src/translations/tr.global.json)
Edit version:
https://github.com/near/near-wallet/edit/issue-2271/packages/frontend/src/translations/tr.global.json?pr=%2Fnear%2Fnear-wallet%2Fpull%2F2319

All that needs to be done is to replace English texts.

Also, added `Türk` as the Turkish version - is that correct?

**Comment by KriptoRaptor** [comment]
> 

hello marcinbodnar, it's 'Türkçe' (which means Turkish) 
I will try this, if I can't manage editing this json file I will ask for help but the translation is still not ready. It will take a couple of weeks more.

**Comment by marcinbodnar** [comment]
Thanks @KriptoRaptor , changed to `Türkçe`. 

Sure, let me know if you will have any problems.

**Comment by KriptoRaptor** [comment]
> 

can we schedule a 30 min call and you show us how you instert the script in here?

**Comment by marcinbodnar** [comment]
@KriptoRaptor Sure, but it's generally straightforward - you can download the file that I'm adding here (`tr.global.json`), open it with for example: https://code.visualstudio.com/ , and change the English texts into Turkish. So for example if you see something like:
`"descOne": "Your initial deposit has been received and transferred to your new account. Your account is now active!",`
you change into:
`"descOne": "Turkish version of the text",`

Generally, the value before `:` stays as it is because it's a prop name, and you change the text after `:` which is the text that will appear in the Wallet.

After you finish, or if you would like to check the partial translation, send it to me and I will prepare the commit, you will be able to see the wallet with translations before it's merged into the live version and check it or adjust it
[tr.global.json.zip](https://github.com/near/near-wallet/files/7840867/tr.global.json.zip)
.

**Comment by KriptoRaptor** [comment]
> 

ok cool. let's first do this then, we're starting. can I have your telegram or discord id in case we need to ask someting? :-)

**Comment by marcinbodnar** [comment]
> ok cool. let's first do this then, we're starting. can I have your telegram or discord id in case we need to ask someting? :-)

Sure, `Marcin Bodnar | NEAR#4420`

**Comment by KriptoRaptor** [comment]
[tr.global - TURKISH.json.zip](https://github.com/near/near-wallet/files/7941234/tr.global.-.TURKISH.json.zip)
we've completed translating all of it @marcinbodnar 
Please help us check the syntax and then let's see how does it look on the html
