### ISSUE TITLE
Login UI should always display both the target contract ID and the referrer of the login request

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-wallet#2275]
**Problem**

The new wallet UI (testnet) doesn't display contract ID in the limited access key authorization flow.

It only displays the domain name of the website, but not the contract you're authorizing with.

The malicious website can trick user into authorizing any contract. It allows to steal locked tokens from the user or interact with any contract. 

**Expected Behavior**

The contract ID should be explicitly displayed during the login flow. It's a blockchain operation, similar to signing a transaction. Hiding this information from the user may lead to a loss of funds.

**Steps to reproduce**

1. Click login on any testnet app.
2. Observe the contract ID is not displayed.

**Comment by zavodil** [comment]
This affects mainnet as well
![Screenshot 2021-11-30 at 7 25 29 PM](https://user-images.githubusercontent.com/38926321/144097072-8dba182b-a642-4e8b-92cf-54ae3bb1e78d.png)

**Comment by MaximusHaximus** [comment]
@evgenykuzyakov @zavodil Thanks for the report, we're working on this now.
