### ISSUE TITLE
Unknown App in testnet wallet

### ISSUE THREAD

**Issue by alsakhaev** [near/near-wallet#2290]
**Problem**

Login page doesn't display an application name in testnet version of the wallet.
Mainnet version works properly.

https://wallet.testnet.near.org/login/?public_key=PUBLIC_KEY_HERE&referrer=APP_NAME
![image](https://user-images.githubusercontent.com/15713727/144385404-34d257e2-9577-4315-8ab4-29328f43e7db.png)

https://wallet.near.org/login/?public_key=PUBLIC_KEY_HERE&referrer=APP_NAME
![image](https://user-images.githubusercontent.com/15713727/144385707-3101e4fc-e6af-4e0f-8783-7ad0bde85ee6.png)

**Expected Behavior**

Testnet wallet should display an application name from `referrer` parameter of URL.

**Steps to reproduce**

1. Open `https://wallet.testnet.near.org/login/?public_key=PUBLIC_KEY_HERE&referrer=APP_NAME` link.

**Comment by alsakhaev** [comment]
Now it works in testnet and mainnet the same. 
Looks like you refused to read `referrer` parameter of URL for displaying an application name.
And now `referrer` HTTP-header is used for it.
![image](https://user-images.githubusercontent.com/15713727/144584767-cb02936d-1545-42b3-9a15-25fc2d666ac6.png)
![image](https://user-images.githubusercontent.com/15713727/144584812-483249e9-15d0-4065-a47a-0d236ab32f80.png)

**Comment by alsakhaev** [comment]
I close the issue.
Probably, this is not a bug, this is a feature :)

**Comment by Danail-Irinkov** [comment]
Okay but, I am creating a Slack Integration, and when redirecting users from Slack, I can't set any headers...
Slack opens a new browser tab to open the redirect link to the wallet => hence no referer
