### ISSUE TITLE
Can not create a wallet

### ISSUE THREAD

**Issue by Tagvi** [near/near-wallet#2295]
**Problem**
It shows Error: The account wouldn't have enough balance to cover storage, required to have 1023536697836184553165 yoctoNEAR more even tho I am trying to use one-time passcode for verification

**Expected Behavior**
Should just let me register

**Steps to reproduce**

1.  Reserve Account ID
2. Choose secure passphrase
3. Enter answer to the passphrase question
4. Verify with email (it fails here)

**Comment by stefanopepe** [comment]
We are happy to help with this issue, please open a ticket at https://nearhelp.zendesk.com/hc/en-us/requests/new

**Comment by Tagvi** [comment]
looks like the issue is already fixed!
