### ISSUE TITLE
Show NFTs information from Indexer DB

### ISSUE THREAD

**Issue by telezhnaya** [near/near-wallet#2300]
We have `assets__non_fungible_token_events` table in [Indexer for Explorer](https://github.com/near/near-indexer-for-explorer) (testnet, mainnet). It contains all the needed information about NFT movements for the specified contract, if the contract implements [events](https://nomicon.io/Standards/NonFungibleToken/Event.html).
We collect this information specially for different kind of wallets.
It would be great to show these NFTs in NEAR Wallet.

People complain in telegram: https://t.me/nearnft/1706

**Comment by stefanopepe** [comment]
Do you have a set of contracts or events that are not tracked? There's already a PR merged at https://github.com/near/near-contract-helper/pull/532

**Comment by telezhnaya** [comment]
Did you deploy it both for mainnet and testnet?

Please check this transaction https://explorer.testnet.near.org/transactions/6SJ8uRKeu9vKJhhnVZXT19zrchsuLz6HthcHa5beMZsp
The info is in Indexer, I checked, but there's no information in the Wallet

**Comment by telezhnaya** [comment]
Another case on mainnet https://explorer.near.org/transactions/9ooei4QcKhTRbaqALtTYfmeusHVt5CfAz7uEiedaMpRs

**Comment by telezhnaya** [comment]
Investigated the issue thanks to @MaximusHaximus 
Each contract should implement `nft_metadata` and `nft_tokens_for_owner` to be shown on Wallet
Added this information to the doc https://github.com/near/NEPs/pull/295
