### ISSUE TITLE
Developer feature proposal: Displaying the project validators in the list of validators 

### ISSUE THREAD

**Issue by Solniechniy** [near/near-wallet#2303]
## Story
There is an announcement about project validators that will validate and give a possibility to farm tokens. The proposal in changing the UI of validators in order to show additional project-validators information. 

## Acceptance Criteria
[ ] Change the logic of near wallet to parse two types of validators: project validators and simple one
[ ] Create new component for displaying project validator with tooltip where additional info will be shown
[ ] Add possibility to claim tokens on the staking page

**Comment by Solniechniy** [comment]
- In order to change the render component, we should type the project validators and others validators. By which criteria we should differ the project validator on the frontend from the simple one?
- Is there any project validator running on testnet?

**Comment by referencedev** [comment]
- I suggest there is a decision on deploying the factory under some account name, e.g. `poolv2.near`.
Then determining the type will be done via prefix match `.poolv2.near`.

- There is one here - `validator2.factory01.littlefarm.testnet`

**Comment by Solniechniy** [comment]
Ok, so we will make a decision based on prefix match `.poolv2.near`.

`validator2.factory01.littlefarm.testnet`  - Does it actually returned by the indexer with the list of all validators?

**Comment by Solniechniy** [comment]
@ilblackdragon  Got it.
Is any information on how to get the project validators list? Will it be with return with common validators?

**Comment by ilblackdragon** [comment]
All validators, independent of which contract they are using, that have submitted the proposal will show up in proposals RPC request.

If you are creating a new validator - it needs to have minimum stake (10k $NEAR I think or something like that) for staking proposal to go through.

**Comment by Solniechniy** [comment]
@ilblackdragon so the proposal should be sent to https://reskin-testnet.sputnik.fund/select-dao in addition to adding a test validator to the list of all validators?

**Comment by Solniechniy** [comment]
@ilblackdragon so the proposal should be sent to https://reskin-testnet.sputnik.fund/select-dao in addition to adding a test validator to the list of all validators?

**Comment by Solniechniy** [comment]
@ilblackdragon 
For getting any information about the user and future development there are two ways, as I understand 
1. Deploy to mainnet, whitelist the contract, create validator and then submit a proposal
2. Create a validator on testnet and submit the proposal 
So if the difference is only on deploying and whitelisting, should we proceed with mainnet?

**Comment by ilblackdragon** [comment]
Staking proposals are sent by the contract itself, when there is enough stake on the contract.

**Comment by stefanopepe** [comment]
@Solniechniy how's the progress of this on Testnet?

In order to proceed, we need to build a few tests against:
- a small set of validators running this new type of pool
- a small set of users adopting these pools and receiving rewards

By now I can see only https://explorer.testnet.near.org/accounts/validator2.factory01.littlefarm.testnet - do we have more than one?

**Comment by Solniechniy** [comment]
@stefanopepe we've been trying to set up a new testnet validator but always have different troubles with it. If you will have a possibility to run any testnet validator with a new type of pool it will be helpful.
