### ISSUE TITLE
accountId=undefined url param of SignIn redirect

### ISSUE THREAD

**Issue by paouvrard** [near/near-wallet#2310]
**Problem**
Often when sining in with: `nearWalletConnection!.requestSignIn()`, the redirect url will contain `accountId=undefined` instead of the Wallet's account id.
This is particularly a problem if the dapp UI is not checking the accountId format: if it goes unnoticed, the user will be logged in as `"undefined"`.

**Expected Behavior**
Login is successful and `accountId` equals the user's account id or the user is not logged in.

**Steps to reproduce**
I couldn't reproduce it deterministically, happens after multiple SignIn attempts at rainbowbridge.app.

**Comment by Patrick1904** [comment]
@paouvrard thank you for reporting this. We've pushed a fix for this some time ago. Would you be able to confirm that this issue isn't occurring anymore?

**Comment by paouvrard** [comment]
Yes this is fixed, thank you !
