### ISSUE TITLE
Error 32700 Missing field account_id

### ISSUE THREAD

**Issue by mayurjobanputra** [near/near-wallet#2316]
**Problem**
After connecting my Ledger, I'm getting this message frequently. I often have to refresh the page and then it goes away. 

`Error - An error occurred while approving this action. Please try again! Error [-32700] Parse error: Failed parsing args: missing field 'account_id'
`
![image](https://user-images.githubusercontent.com/6332663/146532553-5b941144-05c3-4c6b-b2f0-89ea67a5e021.png)

**Expected Behavior**
Just normal behaviour with Ledger (seeing the allow/deny msg)

**Steps to reproduce**
Use one of the dapps to stake/mint etc and then redirected to wallet website and then gets the error

**Comment by stefanopepe** [comment]
Have you tried contacting the wallet support at https://nearhelp.zendesk.com/hc/en-us ?

**Comment by mayurjobanputra** [comment]
Haven't. Good to know. Thanks!
