### ISSUE TITLE
Account creating with email as confirmation failed to create with not enough for storage error 

### ISSUE THREAD

**Issue by AngelBlock** [near/near-wallet#2332]
**Problem**
creating with email as confirmation failed: `The account wouldn't have enough balance to cover storage, required to have 1727866813955785990885 yoctoNEAR more`

**Expected Behavior**
Account created

**Steps to reproduce**
1. Go to near wallet
2. Enter near name
3. Select email as confirmation

<img width="515" alt="Screenshot 2021-12-23 at 09 33 12" src="https://user-images.githubusercontent.com/80400686/147220194-fdd9f8f5-36f3-4e04-ba56-2a90e5efdd1f.png">

**Comment by MaximusHaximus** [comment]
@AngelBlock -- Thanks for the report! We've resolved this bug, which happened when funded accounts were not available. From now on, when funded accounts are not available the UI will automatically take you to the implicit account funding flow. Sorry for the inconvenience!
