### ISSUE TITLE
Social media links not working on ios 

### ISSUE THREAD

**Issue by johny1690** [near/near-wallet#2339]
**Problem**

If you use iPhone 13 either chrome or safari the medium/twitter URLs from the bottom of the website are not working on mobile version. I tried in chrome on desktop using devConsole to replicate the bug but is not working.  I think this bug is activated only on native env.

**Expected Behavior**
the links should be enabled so that we can open the social media accounts. 

**Steps to reproduce**

1. i used an iphone 13 on chrome and safari
2. open any near.org page (i tried in wallet.near.org)
3. scroll till bottom of the page
4. try to click on any social media icons
5. the website is doing nothing.

**Comment by stefanopepe** [comment]
Checked and I confirm the behavior of not showing these links, but I'm not 100% sure it is a feature and not a bug.

cc @Patrick1904 and @corwinharrell

**Comment by Patrick1904** [comment]
> Checked and I confirm the behavior of not showing these links, but I'm not 100% sure it is a feature and not a bug.
> 
> cc @Patrick1904 and @corwinharrell

@johny1690 thanks for reporting this. I am able to reproduce the issue where the links at the bottom of the page on near.org are unresponsive on iOS. @jakestutzman can you please check the links on near.org? I'm only able to reproduce this issue on a mobile device.

@stefanopepe we're not showing any social media links in the NEAR wallet but I can see there's an issue for adding Telegram and Twitter links: https://github.com/near/near-wallet/issues/2255.

**Comment by jakestutzman** [comment]
This is fixed up
