### ISSUE TITLE
Display of creating new account with Ledger

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#2340]
**Problem**
Currently, users cannot create new account with ledger in Google Chrome. However, they may not know it and create account as usual. Finally, after they made a deposit, they cannot recover the account and lose tokens.

**Expected Behavior**
From the beginning, let users know the Google Chrome is not supported for Ledger in this page.
![image](https://user-images.githubusercontent.com/87597805/147809235-800851e9-0b7b-4a1d-9161-15e8ca309dbb.png)

**Steps to reproduce**
1. Click create new account
2. Set up an ID
3. Select Ledger hardware wallet
4. Connect ledger device
5. Make a deposit to the single-used funding address
6. Cannot recover the account in Google Chrome

**Comment by stefanopepe** [comment]
there's an update that will solve this problem, enabling Chrome again. cc @MaximusHaximus who will link here the PR
