### ISSUE TITLE
Ledger

### ISSUE THREAD

**Issue by hanakannzashi** [near/near-wallet#2341]
**Problem**
1.when using ledger to recover account, it will add a function call key to call (__wallet__metadata) function, this key seems useless

2.when delete above key, wallet can work normally, but on this page (https://wallet.near.org/profile), it shows that i did not enable passphrase, i enabled actually, page displays wrong.

**Comment by stefanopepe** [comment]
Thank you for your feedback.

What is the step-by-step process followed to delete the Ledger key?

**Comment by hanakannzashi** [comment]
@stefanopepe No I did not delete the 【Ledger Key】, I delete the 【FuncationCall Key added by every recovery with Ledger】
1.I have 【Passphrase Key A】 and 【Ledger Key B】 ,I went to page (https://wallet.near.org/profile) ,it shows I enabled Ledger and Passphrase
2.I recover my account with Ledger, then a 【FunctionCall Key C】was added to my account
3.I used near-cli to delete key C
4.I transferred, it success, it seems key C make no sense
5.I went to page ((https://wallet.near.org/profile) , it shows I enabled Ledger but did not enable Passphrase

**Comment by hanakannzashi** [comment]
@stefanopepe When using passphrase and email link to recover the account, generate a new key confuse users
