### ISSUE TITLE
Pending state after enabling ledger

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#2343]
**Problem**
After enabling ledger, there is a page about suggesting user to delete other recovery methods, and there is no response after the operations on that page and always pending. 

![5348ccb7d8c33be947b46b382afd8bd5_](https://user-images.githubusercontent.com/87597805/148175063-a6d11818-8484-4582-a766-6b17a417ce58.jpg)
![160262dd528a472718d9f98b26597e73_](https://user-images.githubusercontent.com/87597805/148175079-6b2d57e5-f1a3-4305-9fe1-dae4fe0e8ca2.jpg)
![c586fc964699d6e8ebbcb70cce045f12_](https://user-images.githubusercontent.com/87597805/148175096-3d984a22-1730-4859-8792-fda2220fbfc5.jpg)

**Expected Behavior**
It works without pending.

**Steps to reproduce**

1. Enable ledger
2. Delete other recovery methods
3. Pending

**Comment by stefanopepe** [comment]
Let's debug over the ticketing platform first, ask the user to open an incident on Zendesk
