### ISSUE TITLE
Add integration with Utorg on-ramp provider

### ISSUE THREAD

**Issue by samkrew** [near/near-wallet#2365]
## Story

Integrate Utorg provider for following scenarious:

1. Account top-up from main page.
2. Account verification via first deposit via credit card.
3. Account top-up on insufficient funds for some operation.

## Assets

Link template: https://app.utorg.pro/direct/wallet.near.org/{address}/?currency=NEAR&amount={amount}
Detailed docs: https://docs.utorg.pro/#direct-flow
Logo: https://static.utorg.pro/utorg-logo.png

**Comment by stefanopepe** [comment]
Do you have visual material available, to add to this PR? This would accelerate the review process by @corwinharrell

**Comment by samkrew** [comment]
@corwinharrell  [NEAR Wallet + Utorg](https://www.figma.com/file/arErH9yVOjMRW98d4abuMn/NEAR-Wallet-%2B-Utorg?node-id=0%3A1)

We will update PR if design would be approved.

**Comment by corwinharrell** [comment]
Addressed by https://github.com/near/near-wallet/issues/2445
