### ISSUE TITLE
Check if coin-op is available by calling the 'fundedAccountAvailable' endpoint 

### ISSUE THREAD

**Issue by Patrick1904** [near/near-wallet#2372]
**Problem**
While creating an account, the wallet shows the verification options regardless of whether coin-op is available/funded or not. This leads to a suboptimal UX since the user may try to verify using their phone/email but end up on the 'self funded' option anyway.

<img width="658" alt="Screen Shot 2022-01-13 at 4 50 45 PM" src="https://user-images.githubusercontent.com/24921205/149432269-ab2d3b9b-7d4b-46da-8f99-1252ba557f0b.png">

**Expected Behavior**
The wallet calls the `checkFundedAccountAvailable` endpoint in `near-contract-helper` to check if coin-op is available. If coin-op is not available, the email and phone verification options are not visible to the user.

**Steps to reproduce**

1. Initiate account creation with a seed phrase
2. Verify the seed phrase
3. Observe the phone and email verification options

**Comment by Patrick1904** [comment]
@MaximusHaximus the `checkFundedAccountAvailable` in `near-contract-helper` is currently returning `true` but suspecting it just doesn't have the same minimum amount logic that we added for the identity funded account creation yet?

**Comment by MaximusHaximus** [comment]
❇️ 💖  -- Resolved the issue with the `checkFundedAccountAvailable` endpoint!  Nice work @Patrick1904, this is a big improvement. Shipping this out today.
