### ISSUE TITLE
Cache address on the Initial Manual Deposit setup

### ISSUE THREAD

**Issue by AmagiDDmxh** [near/near-wallet#2374]
## Story

As a USER who first starts using near wallet, I want to be able to recover the initial setup wallet, so I can back into the flow when there's some interruption happend.

## Acceptance Criteria

- [ ] AC1
- [ ] AC2
- [ ] Mobile ok
- [ ] Tested

## Unhappy Path

When setting up the initial wallet, click on Manual Deposit and an address appears. I copied this address and closed the current page. After depositing money to this address, when I reopened the wallet page to initialize it with the previous information, the address was changed and the previous transfer was lost。

## Assets

- Mockup: 

## NOTES

Is this intentional? Is there no way to return the money? At first experience, I was amazed by the UI, but this gave a bad impression.

**Comment by Patrick1904** [comment]
@AmagiDDmxh thanks for sharing your experience creating an account. We're currently revamping the onboarding flow and will make sure to address these 'drop off' scenarios.

As long as you saved your seed phrase, ledger key, or email link during the onboarding flow, you still have access to your account. So if you've deposited NEAR into the account, please try importing it in on https://wallet.near.org/recover-account

**Comment by AmagiDDmxh** [comment]
Thanks for the quick reply, @Patrick1904 

Checking email and found the recovery link helped!
