### ISSUE TITLE
Attempts to use Ledger always attempt to open `chrome-extension://` links (even on Firefox)

### ISSUE THREAD

**Issue by nagisa** [near/near-wallet#2377]
**Problem**

Any attempt to use Ledger attempts to open a `chrome-extension://` link. On firefox this shows a dialog asking to select application to use to open these links. This dialog won't go away without a manual user action which is not a great experience. 

**Expected Behavior**

Uh… not sure. Ideally I wouldn't need to tell firefox that it shouldn't actually try to open this link.

**Steps to reproduce**

1. Try using ledger to recover and/or create an account with Firefox that has no `chrome-extension://` protocol handler assigned.

**Comment by stefanopepe** [comment]
Please open an issue at https://nearhelp.zendesk.com/hc/en-us/requests/new and we'll look into it. 
Make sure to provide screenshots or (better) videos so we can better investigate and understand how to reproduce the issue on our machines.
