### ISSUE TITLE
Stake Farming Feature on Wallet 

### ISSUE THREAD

**Issue by pretfood** [near/near-wallet#2383]
**Problem**

On stake farming contracts, users cannot see rewards in their wallet. At present, only $NEAR rewards are visible on the wallet. In new stake farming contracts, rewards are returned in $AURORA, but these are not visible. 

**Expected Behavior**

Staking rewards should be displayed in more than one currency. 

**Steps to reproduce**

1. Stake $NEAR tokens in aurora.pool.near
2. Watch how the rewards number never moves beyond 0, despite claimed APY of 29%.

**Comment by stefanopepe** [comment]
There's work in progress, but no commitment on the timing for the release, as it needs a final review on the UX side.

**Comment by esaminu** [comment]
@corwinharrell Would appreciate some design input on this. We created a first iteration on #2384 that impacts the main [staking page](https://wallet.staging.near.org/staking) to display NEAR token icons and the validator page to display NEAR balance with icon and other tokens if any e.g. the [aurora validator](https://wallet.staging.near.org/staking/aurora.pool.near):

<img src="https://user-images.githubusercontent.com/5849204/150241837-ba74ca75-28ad-4005-a3a8-34bfac0212cb.png" width="500">

**Comment by corwinharrell** [comment]
<img width="563" alt="Screen Shot 2022-01-20 at 6 47 43 PM" src="https://user-images.githubusercontent.com/5934188/150440558-28ad0f05-f58b-4c8e-befe-addf1cc5684c.png">

Until we have a new UI, I think it is actually clearest to group the rewards under a single section and label. This way, it simply becomes a list of `Rewards earned`, and the icon and symbol denote the particular token, without the need for separate labels and sections.

I think the only remaining necessary change then would be to change the tooltip icon to read something like:

Rewards earned but not withdrawn. NEAR token rewards are compounding and are automatically re-staked.

**Comment by esaminu** [comment]
UI and copy for v1 (token rewards display) updated in #2388
