### ISSUE TITLE
Farming validator token claiming

### ISSUE THREAD

**Issue by Solniechniy** [near/near-wallet#2392]
## Story

As a USER I see the farming token, I want to claim so I can get a reward from staking in farming validator.

## Acceptance Criteria

- [x] Claim button is available for each token on the validator page. Should open the modal for claiming.
- [x] Token prices should be taken from ref.finance and displayed below the token name. 
- [x] Since token prices are taken, we can show the APY on the validator page and for farming validators row among all validators page.
- [x] Get whitelisted token from ref.finance and display that farming token is not whitelisted by ref.
- [ ] Works with legacy Lockup accounts
- [ ] Total token rewards earned are displayed on the [staking landing page](https://wallet.testnet.near.org/staking) for both lockup and owner accounts
- [ ] Total token rewards earned are displayed on the [profile page](https://wallet.testnet.near.org/profile) for both lockup and owner accounts

## Unhappy Path
Can't claim token

## Assets

![telegram-cloud-photo-size-2-5429190957292698673-x](https://user-images.githubusercontent.com/26657914/150552758-06a8f1ac-1df4-4c38-bb69-ca75121cc94f.jpg)
![telegram-cloud-photo-size-2-5426960864243726572-y](https://user-images.githubusercontent.com/26657914/150551973-a181c59e-3184-4a93-ac8b-8d123c345482.jpg)
![image](https://user-images.githubusercontent.com/26657914/150553413-76ddc3db-f076-49b1-9183-13abef8c29b0.png)

**Comment by esaminu** [comment]
@Solniechniy we need to get design and flow approval for these first so assigning to @corwinharrell and @stefanopepe for review. Could you also include all UI including ref whitelisting for their reference?

**Comment by Solniechniy** [comment]
ref whitelisting looks like that 
![telegram-cloud-photo-size-2-5438138392077515063-y](https://user-images.githubusercontent.com/26657914/150820873-ad85c82c-4a0b-47ae-aacc-cfefdb167d36.jpg)
![telegram-cloud-photo-size-2-5438138392077515064-x](https://user-images.githubusercontent.com/26657914/150820891-a6079525-c6fb-463a-90c5-08d21153977f.jpg)

**Comment by Solniechniy** [comment]
But there is an issue with claim modal and APY, it looks like that 
![image](https://user-images.githubusercontent.com/26657914/150821362-cb6406ac-8901-4a71-8af0-af8a21d1ec93.png)

**Comment by stefanopepe** [comment]
Added a new acceptance criteria, we have to make users aware the `pool.near` contract is not audited and "staking is at your own risk"

**Comment by stefanopepe** [comment]
Further extended the design acceptance criteria to specify the source for the token value in USD

**Comment by stefanopepe** [comment]
@Solniechniy Added another acceptance criteria: make the "claim button" able to withdraw the tokens owned by a legacy lockup contract.

As far as I know, there's a method to claim from legacy lockup accounts: https://github.com/referencedev/staking-farm/blob/master/HowTo.md#cashing-out-farmed-tokens (see "claim from lockups")
