### ISSUE TITLE
Cannot select account on transaction confirmation screen

### ISSUE THREAD

**Issue by emarai** [near/near-wallet#2396]
**Problem**
No matter which account is active on an app, wallet will always use the current wallet active account. Despite the account that made the transaction on the app is also logged in on wallet.near.org. 

**Expected Behavior**
As I remember, wallet uses the account that signed the transaction from the app, rather than the currently selected account on the wallet.

**Steps to reproduce**

Accounts: a.near, b.near
1. Login on any app (paras.id, app.ref.finance) as a.near
2. Ensure that a.near and b.near logged in on wallet.near.org
3. Select active account on wallet as b.near
4. Make transaction on the app with a.near

**Comment by stefanopepe** [comment]
cc @MaximusHaximus

**Comment by esaminu** [comment]
Don't think we can tell which account the dapp is logged in with from a serialized transaction (@MaximusHaximus to confirm?) but #2401 should resolve this.

**Comment by esaminu** [comment]
Closing this in favor of #2402 . Transactions coming from dapps are composed specifically for the account on the `signerId` prop of the transaction. Signing and sending the transaction from another account will throw an error.
