### ISSUE TITLE
Switch account during transaction confirmation

### ISSUE THREAD

**Issue by corwinharrell** [near/near-wallet#2399]
## Problem
During transaction confirmation, users should retain the ability to switch between accounts incase they want or need to confirm a transaction with an account other than their active account.

**Related to:** https://github.com/near/near-wallet/issues/2396

<img width="972" alt="Screen Shot 2022-01-24 at 10 28 08 AM" src="https://user-images.githubusercontent.com/5934188/150812462-23de6e67-be72-4d0d-ac41-eef823e667d2.png">

## Resources
Figma: https://www.figma.com/file/Jl4i7oFfkM7uMxBidkZ3Tk/Signature-Screens?node-id=1%3A606

**Comment by stefanopepe** [comment]
Related to #2396

**Comment by esaminu** [comment]
Cosing this in favor of #2402 . Transactions coming from dapps are composed specifically for the account on the `signerId` prop of the transaction. Signing and sending the transaction from another account will throw an error.
