### ISSUE TITLE
critical web wallet bug: cannt show balance or allow any operation

### ISSUE THREAD

**Issue by shypkov** [near/near-wallet#2400]
**Problem**
There is an error appears on the  web wallet. and i cannt operate with account and its all: 
"Ошибка
К сожалению, произошла ошибка. Попробуйте еще раз.
View FAQ
Error: [-32000] Server error: account prometei.poolv1.near does not exist while viewing"
**Expected Behavior**
Allows to withdraw and operate with account.
**Reason**
Previously was created a pool with wrong name connected to account with cli. it seems like there is no timeouts when reading the delegated pools according to account.

**Comment by Patrick1904** [comment]
Closing as issue is outdated
