### ISSUE TITLE
Add integration with NearPay on-ramp widget  

### ISSUE THREAD

**Issue by ivan-ilin-nearpay** [near/near-wallet#2403]
Add an option to top up the wallet using NearPay widget.

## Description

1) the main screen: add the most popular and easy way (or the last one the user had chosen) to purchase NEAR right in the wallet. We made it: "Refill with NearPay" button next to the "Top Up" button.
2) the "Top Up" page: add a block with NearPay. We support only card payments now (and we want to add Apple/Google Pay in the near future).

## Acceptance Criteria

- The "Buy" button leads to widget.nearpay.co with correct parameters and a valid signature
- The "Learn more" link leads to https://help.nearpay.co/en/
- Tested

## For development

- list of supported countries: https://supremacy-1111.notion.site/NearPay-geographic-restrictions-6f409e1b738049c3a83a2a2b6b41c6eb (is going to grow in the future)
It may be better to show the button on the main page and on the top up page only to users or ips from this list.

- instructions how to generate a link from backend (needs a signature): https://supremacy-1111.notion.site/NearPay-Widget-Documentation-for-Merchants-fbf29ddaf92d4ea190ad92aef4d90474

## NOTES

On the main screen:
![Main screen](https://user-images.githubusercontent.com/98379101/150926525-d36c526f-9fee-4125-a98b-47ab504e35ee.png)

On the "Top Up" page (2 versions: with and without apple pay):
![TopUp without ApplePay](https://user-images.githubusercontent.com/98379101/150926521-258c36c9-485e-4fa5-ac96-bb459bf3eec4.png)
![TopUp with Apple Pay](https://user-images.githubusercontent.com/98379101/150926527-b476cc22-72bd-4ee7-82a7-5388bee5ee89.png)

**Comment by kirillarutyunov** [comment]
@stefanopepe @MaximusHaximus We have WIP PR with implementing our integration. So we have a question about implementing some logic around button enabling–disabling via our API like MoonPay do it. Can you check it in the PR please? So we can finish our PR after your reply and test it :)

Please check it here: https://github.com/near/near-wallet/pull/2419#issuecomment-1023298763.

**Comment by corwinharrell** [comment]
Addressed by https://github.com/near/near-wallet/issues/2445
