### ISSUE TITLE
"What's on Near?" => Explore apps link returns a 404

### ISSUE THREAD

**Issue by AustinBaggio** [near/near-wallet#2425]
**Problem**
Wallet.near.org Explore apps link opens a new tab and returns a 404 instead of the trending page of awesomenear.com
![Screen Shot 2022-01-31 at 9 20 37 AM](https://user-images.githubusercontent.com/10964366/151832554-9f2cf895-7db0-4be1-b9fb-9ab7183539f9.png)

**Expected Behavior**
I assume clicking on the "Explore Apps" Link should bring you to https://awesomenear.com/

**Steps to reproduce**

1. Log-into wallet
2. Click "Explore Apps" (see screenshot)
3. 404 page returns in a new tab
Expected: https://awesomenear.com/ opens in a new tab

**Comment by Patrick1904** [comment]
Thank you for reporting @AustinBaggio! 🙏
