### ISSUE TITLE
Success URL appended with `?` despite it has already query params in it

### ISSUE THREAD

**Issue by ahnafalfariza** [near/near-wallet#2442]
**Problem**
Unable to log in to dApps. The success URL after request sign-in method is appended with `?` despite it has already query params in it. 
Just found this on testnet. However, by the time I write this issue, it still working normally on mainnet

**Expected Behavior**
Wallet returns correct URL which results in successful login on dApps

**Steps to reproduce**
1. Wallet.requestSignIn from current URL appended with params ex: https://paras.id/search?q=query
2. Connect the near account to dApps
3. The URL changes to: https://paras.id/search?q=query?account_id=...&public_key=...&all_keys=... with double `?`, which resulted in failed login

If I'm not mistaken a few days ago was still normal, perhaps this may be the cause: https://github.com/near/near-wallet/blob/master/packages/frontend/src/redux/actions/account.js#L210

**Comment by BenKurrek** [comment]
We're experiencing the same problem. Bumping this issue ^

**Comment by MaximusHaximus** [comment]
Thanks for the report folks!

@esaminu Could be related to the recent query-string changes, especially since this is only on Testnet -- could you investigate?

**Comment by paouvrard** [comment]
Also looks related: experiencing issues sining in when there are already url params in the redirect url.
For example signing in from https://testnet.rainbowbridge.app/transfer

**Comment by paouvrard** [comment]
@MaximusHaximus @esaminu The fix improved it, but at login, when redirecting to https://testnet.rainbowbridge.app/transfer, the `/transfer`path was removed and redirected to [https://testnet.rainbowbridge.app](https://testnet.rainbowbridge.app/transfer) instead

**Comment by alsakhaev** [comment]
I have a weird behavior now. I develop a browser extension, where callback url looks like `chrome-extension://ogcojbmjgfbdhgoedagklhoginpblbon/callback.html?request_id=af67c1511c3648588f390acd8d574507&success=true` and after authorization the wallet redirects me to `chrome-extension://invalid/`

**Comment by esaminu** [comment]
Thanks guys! Pathname that was omitted in previous PR has been readded in #2451 😃

**Comment by alsakhaev** [comment]
> Thanks guys! Pathname that was omitted in previous PR has been readded in #2451 😃

We're waiting the release ;)
