### ISSUE TITLE
Unexpected removing hash from target link on redirection from wallet

### ISSUE THREAD

**Issue by SteMak** [near/near-wallet#2452]
**Problem**
When signing in or confirming transaction from near wallet hash dissapears from the success_url or failure_url

**Example**
```
https://wallet.testnet.near.org/login/?title=NEAR+Place&contract_id=place.meta&success_url=https%3A%2F%2Fnear-examples.github.io%2Fplace%2F%23super_hash&failure_url=https%3A%2F%2Fnear-examples.github.io%2Fplace%2F%23super_hash&app_url=https%3A%2F%2Fnear-examples.github.io&public_key=ed25519%3ArwpXPe65x1jn9Tv9dTp5S2uYjXwUkNPhr7VbYQvKAuy
```
is redirected to
```
https://near-examples.github.io/place/
```
but should be to
```
https://near-examples.github.io/place/#super_hash
```

**Steps to reproduce**

1. Go to `https://near-examples.github.io/place/#super_hash`
2. Try to login
3. Got `https://near-examples.github.io/place/`

**Comment by marcinbodnar** [comment]
Thanks @SteMak , I will check it.

**Comment by esaminu** [comment]
Thanks for reporting @SteMak!

**Comment by SteMak** [comment]
Thank a lot for quick reaction!

**Comment by dvconsultores** [comment]
i'm presenting  the excact problem here, all was working ok and suddenly crashed, i have several days, debuging, almost crazy whithout sleep, i can't login. This is a new change from NEAR Wallet login.
