### ISSUE TITLE
Full access is unexpectedly requested on signing

### ISSUE THREAD

**Issue by SteMak** [near/near-wallet#2463]
**Problem**
On the end of signing in with contract that requests limited permissions you are redirected not to dapp, but to getting full access.

**Expected behaviour**
After confirming connection your account should be redirected to dapp.

**Steps to reproduce**
1. Go to `https://near-examples.github.io/place/`
2. Try to log in
3. Got `requesting limited access`
4. Chose account and press `Connect`
5. Got `requesting full access`

**Comment by esaminu** [comment]
Thanks @SteMak ! This should be fixed in #2462, Please confirm! 😄

**Comment by SteMak** [comment]
Thank you for your work!
