### ISSUE TITLE
When creating a new account, "Continue" button doesn't work when getting to the "Set Recovery" phase

### ISSUE THREAD

**Issue by mieubrisse** [near/near-wallet#2468]
**Problem**
I rebuilt the Wallet Docker image to work inside Kurtosis and things seem to work at first, until I get to "Set Recovery". Clicking the "Continue" button doesn't do anything, and nothing shows up in the Network tab or Console.

<img width="1434" alt="Screen Shot 2022-02-09 at 7 04 12 PM" src="https://user-images.githubusercontent.com/1142185/153300958-8b36d713-3ab0-472a-b5f6-b4a30c124cf5.png">

**Expected Behavior**
Proceeds to the next screen where it shows me my passphrase

**Steps to reproduce**

1. Install Kurtosis if not done already: https://docs.kurtosistech.com/installation.html
2. Run `kurtosis module exec kurtosistech/near-kurtosis-module:2022-02-09`
3. Open the returned Wallet URL
4. Try to create an account

**Comment by Patrick1904** [comment]
@mieubrisse thank you for reporting this issue. We had a bug that made it into the testnet wallet but shipped a fix earlier today: https://github.com/near/near-wallet/pull/2466.

Please try using the latest version of the master branch as this issue should be solved now.

**Comment by andy-haynes** [comment]
Hi @mieubrisse, we can absolutely look at incorporating Docker image builds into our upcoming CI pipeline. Are you currently relying on the Docker image built from `near-wallet/packages/frontend` without any custom behavior on top of it?
