### ISSUE TITLE
Able to sign with wrong signerId on /sign route (esp. slow connection)

### ISSUE THREAD

**Issue by Patrick1904** [near/near-wallet#2482]
**Problem**
Able to sign a TX using wrong `signerId` on `/sign` before the correct account has been selected / made active in wallet

**Expected Behavior**
Not able to sign a TX using wrong `signerId` on `/sign` before the correct account has been selected / made active wallet

**Steps to reproduce**

1. Log in on https://berryclub.io/ with account A
2. In a separate tab, make account B active on wallet.near.org
3. Refresh page on https://berryclub.io/
4. Initiate buying something on https://berryclub.io/
5. Observe that the 'approve' button is still enabled before the `signerId` matches the active wallet account

**Comment by Patrick1904** [comment]
@esaminu is this something you can have a look at? Seems we should disable the 'approve' button as long as the `signerId !== wallet.accountId`?

**Comment by andy-haynes** [comment]
@esaminu I didn't notice this had been assigned to you when I created the PR, my bad 🤦. Hopefully you haven't had a chance to start on it yet, I'm just working my way down the list of recent priority issues for the support rotation 🤞

**Comment by esaminu** [comment]
No problem! Yeah I hadn't started on it but was intending the same idea as #2499 for the fix, thanks for covering! 😄
