### ISSUE TITLE
Not possible to select a token

### ISSUE THREAD

**Issue by k-o-l-e-s** [near/near-wallet#2484]
**Problem**
Not possible to select a token when sending when in wallet two tokens with the same symbol,
by example GOLD

**Expected Behavior**

**Steps to reproduce**
1. deposit two tokens with the same symbol
2. send first token
3. send second token

![Screenshot 2022-02-15 at 16 21 14](https://user-images.githubusercontent.com/92436869/154080745-1d811601-e35e-459f-a412-4946ce056c21.png)

**Comment by Patrick1904** [comment]
Thanks for reporting this @k-o-l-e-s! 🙏  Will investigate and ship a fix for this.

**Comment by k-o-l-e-s** [comment]
Extra fast! Big thanks guys!
