### ISSUE TITLE
UI for available balance of lockup account

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#2515]
**Problem**
The available balance of the locked account shows incorrect data(35.65433). 

<img width="636" alt="23df55ed376b78b4624001641643456" src="https://user-images.githubusercontent.com/87597805/156724550-1e5877d1-1b96-43af-aff4-fcc90a113d6c.png">

<img width="673" alt="4998529ea59773cd63c93fed34250ab" src="https://user-images.githubusercontent.com/87597805/156724640-514e3e5c-f57c-4bb4-a026-d3af2077abd6.png">

<img width="665" alt="8d42eeb34b55b82c890cc7553be7b5e" src="https://user-images.githubusercontent.com/87597805/156724468-58f60cc7-0d2a-4ae6-be01-6ed5bbc28e52.png">

An error will occur when the user stakes more than 4.15434 tokens.
<img width="512" alt="13fc7c19ed4be77a7de884346b09d71a_" src="https://user-images.githubusercontent.com/87597805/156724878-492b8282-2224-4915-be9f-2562d2fbf6ea.png">

**Expected Behavior**
It can show the right data, so uses will avoid facing the error.

**Steps to reproduce**

1. Stake more than 4.15434 tokens(30 or max) on lockup accout
2. The error occurs
3. Stake 4.15434 tokens on lockup accout
4. It works

**Comment by Patrick1904** [comment]
@esaminu do you have any idea why the storage amount shows as available on the staking page? Could it be related to recent changes to the lockup balance?

**Comment by Patrick1904** [comment]
Closing this issue as it's outdated. @RubyJiao please re-open if issue appears again.
