### ISSUE TITLE
Newly registered users, custom IDs need to create a new account

### ISSUE THREAD

**Issue by Leroy-X** [near/near-wallet#2525]
**Problem**
Hi, newly registered users, custom IDs need to create a new account, I want to keep the current passphrase and customize the ID, what should I do?

Thanks

**Comment by Patrick1904** [comment]
Thanks for your question @Leroy-X. Current account creation in the NEAR Wallet requires a new passphrase for each new account, and it's not possible to change only the custom ID at this point.

We're planning on adding the ability to re-use a passphrase when creating a new account, but it requires more extensive key management features before we can release it, so there's no ETA for this feature yet.

**Comment by Leroy-X** [comment]
Thank you very much for your reply, newbie is a little confused about this :P
