### ISSUE TITLE
Unable to withdraw funds from staking (after release period)

### ISSUE THREAD

**Issue by JoaquimLey** [near/near-wallet#2548]
**Problem**
When trying to withdraw the funds from a validator (stacking) I'm unable to go on with the tx (there's no error feedback)

**Expected Behavior**
I should be able to withdraw my funds after the the pending release period

**Steps to reproduce**

1. Go to the [Near Wallet stacking](https://wallet.near.org/staking/) page
2. Select a validator to which you've previously clicked `Unstake` and waited the 4 epoch period
3. Click `Withdraw`
4. Nothing happens... No visual feedback

```json
{
  "block_height": 62126595,
  "error": "wasm execution failed with error: FunctionCallError(MethodResolveError(MethodNotFound))",
  "logs": []
}
```

**Comment by zcstarr** [comment]
I'm able to repro this same exact issue. 
<img width="403" alt="image" src="https://user-images.githubusercontent.com/173187/160150179-0006ed7b-eda8-4b22-8ff7-dbdadf2714d6.png">
Redact some of the info but seems like get_farms method call is failing

**Comment by gutsyphilip** [comment]
Hey @JoaquimLey @zcstarr 

Thanks for creating this. We are now investigating this issue.

**Comment by MaximusHaximus** [comment]
This fix is now live on mainnet, sorry about the inconvenience!

**Comment by zcstarr** [comment]
Confirmed fixed thanks!

**Comment by JoaquimLey** [comment]
Confirmed, I was able to withdraw.

Thank you for the quick response.

**Comment by Todun2020** [comment]
I can't withdraw pls help me

**Comment by JoaquimLey** [comment]
> I can't withdraw pls help me

Please provide as much context as possible, and stackoverflow/discord might be a better place to seek help 🙂

**Comment by Todun2020** [comment]
I chat on discord but no one answer me
