### ISSUE TITLE
Ledger modal fails to dismiss

### ISSUE THREAD

**Issue by gutsyphilip** [near/near-wallet#2557]
**Problem**
During account creation flow using ledger, ledger modal fails to dismiss automatically on completion of account setup and activation.

Environment: Testnet

**Expected Behavior**
Modal should automatically dismiss on completion

**Steps to reproduce**
1. Create new account
2. Select ledger
3. Follow through with prompts to approve ledger and sign transaction
4. Modal should still be open on completion

**Comment by agileurbanite** [comment]
marked as Priority 1, @gutsyphilip is OOTO and returning next week 4/11.  Will hold off on taking this over by someone else until he gets back.
