### ISSUE TITLE
[Feature] Support for viewing Video NFTs in collectibles tab

### ISSUE THREAD

**Issue by roshaans** [near/near-wallet#2559]
#### What problem are we solving with? Is this epic part of the planned features [here](https://github.com/near/near-wallet-roadmap/projects/1), and which ones?

- Currently, the collectibles tab defaults to viewing collectible's metadata within a `<img>` tag. This should be dynamic based on the file type. 

#### How did this problem originate? If it was revealed through user feedback, how was that feedback received and from whom?
- My video nfts show up blank on the collectibles tab. 

#### Job Story(s)
- When I view a video file embdded NFTs/collectibles, I want to see them in the collectibles view similar to how Paras.id does it so I can enjoy my collectibels for what they are suppose to be made for.
#### What are we planning to do about it?
- What is the scope of the design and engineering work required for this project?
- Along the way, this epic will be linked with issues and pull requests
it is easier to assume that the picture from the metadata is an image. Many IPFS links in the token data do not expose what type of metadata it is. The metadata link type should be embedded as part of the NFT standard. Then, the front should decide what tag to choose `<img>` or `<video>` based on this. 

#### What are we _not_ planning to do about it?
- What items have been considered but may fall out of the scope of design and engineering work for this project?
Sometimes the scope is too large, and this section may lead to other epics, other features [here](https://github.com/near/near-wallet-roadmap/projects/1) or even other products
Do a sophisticated hacked-out approach that pings the IPFS link and awaits to see what type of data it returned. Possible, but introduces a lag for loading all collectible items, even images. Perhaps, we can load images by default and if images do not load, then only then check for other types of media. 

## Measuring Success
- Are there a set of quantifiable metrics that we can surface once the work has been completed in order to determine how successful our solution was?
Being able to view a dynamic set of media in the collectibles tab. 

### Are there any resources that are necessary or that will aid in the completion of this work?
- paras.id appraoch

**Comment by roshaans** [comment]
I noticed that the webm format NFTs or any Video NFTs are not supported on the NFT detail tab at all. 

I made a PR for it if you would kindly review it. 

https://github.com/near/near-wallet/pull/2562

**Comment by agileurbanite** [comment]
I believe this is  closed by #2562
