### ISSUE TITLE
how can I fix it?

### ISSUE THREAD

**Issue by bryanForSafe** [near/near-wallet#2564]
![image](https://user-images.githubusercontent.com/87746660/161261883-fa13f704-ea7b-46b6-b9c3-ca4d78c75666.png)

Hi,  When I run the wallet (https://github.com/near/near-wallet/tree/master/packages/frontend), its interface is blank. I see the following error in Chrome, how can I fix it?

**Comment by andy-haynes** [comment]
Hi @bryanForSafe, you'll need to set a value for the `NEAR_WALLET_ENV` environment variable. This is used determine the default configuration for your local environment, the set of valid environments can be found as the values of the JSON object here: https://github.com/near/near-wallet/blob/master/features/environments.json.

I will update that error message to be a bit more helpful 🙂
