### ISSUE TITLE
Failed to withdraw unstaked $NEAR available for withdrawal from `aurora.pool.near`

### ISSUE THREAD

**Issue by paouvrard** [near/near-wallet#2566]
**Problem**
I unstaked some $NEAR from `aurora.pool.near` which became `available for withdrawal` after 4 epochs as expected.
When confirming the withdrawal transaction, the Ledger error message is shown immediately:
![image](https://user-images.githubusercontent.com/29397451/161412792-6a422751-77a6-41e2-b654-6addbe087e88.png)
The Ledger also prompts to sign a transaction but it is not a withdrawal transaction: it is the same `claim` function being called when claiming aurora rewards. So it appears that the UI is calling the wrong function when withdrawing.

**Expected Behavior**
Withdraw unstated $NEAR tokens

Browser: Firefox.

**Comment by esaminu** [comment]
Thanks for reporting @paouvrard. This is expected behavior as far as the transaction being signed. The wallet will claim any remaining unclaimed farm rewards before withdrawing.

You seem to be experiencing a connection issue with your ledger that is unrelated to the transactions being signed.

**Comment by paouvrard** [comment]
Thanks, withdraw_all is now being called.
