### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by kariolina** [near/near-wallet#2577]
## Story
hi there 
Firsst of all after all of your efforts discuraging a user to interact with you i finaly made it after 5 hours .
Your wallet is the most discouraging thing to interact in crypto .
Whyyyyyy??????
Why i have to pay to interact with you protocol ??\
Why i have to open  a temporary wallet and then get to the . near wallet why?????
Why users use other things then your wallet to ineract ??
Why i have to pas fbi to get into discord ???
Why i have  to have 4 near for 2fa ?????
You supposed to be the better and cheaper version of ethereum and yoy ask for money before even i made atrrade whyyyyyyyyyyyyyyyyyyyyyyyy?????????????????????

As a USER who PRECONDITIONS, I want to DO_THING so I can ACCOMPLISH_GOAL.

## Acceptance Criteria

- [ ] AC1
- [ ] AC2
- [ ] Mobile ok
- [ ] Tested

## Assets

- Mockup: 

## NOTES

-

**Comment by agileurbanite** [comment]
This is great UX feedback and duly noted, you can learn more about the concept of gas here: https://docs.near.org/docs/concepts/gas.  For DApps you connect to they might require minimum storage staking to use the DApp that's up to the DApp authors. https://docs.near.org/docs/concepts/storage-staking

**Comment by agileurbanite** [comment]
Closing for now and made a note about improving our ux copy to clarify
