### ISSUE TITLE
Account creation when the network is slow

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-wallet#258]
**Problem**
If the network is slow, the account creation might get stuck saying `username is taken` after the user clicks the `create account` button, which is caused by an timeout error from rpc. However, at this point the account might have been already created on the network, which means that the user cannot create the same account again if they retry.

**Expected Behavior**
There should be some way to inform the user about the timeout error and then allow them to do some manual refresh of the page (or some better way) so that they can proceed with the same account id.

**Steps to reproduce**

1. Try to create an account on https://wallet.tatooine.nearprotocol.com
2. Observe that it says `Username taken` after the `create account` button is clicked. However, from near-shell `near state <account_id>` shows that the account exists.

**Comment by joesixpack** [comment]
Still occurring.  Can't login for stakewars staking because of the username taken already bug.  I'm wondering exactly where there recovery phrase is provided also.

**Comment by kcole16** [comment]
**Steps to reproduce locally (using Chrome)**
1. In dev tools "Network" tab, set speed to "Slow 3G"
2. Try to create an account
3. View recent [Explorer](https://explorer.nearprotocol.com) TX to see transaction succeeded
