### ISSUE TITLE
Transaction .csv export

### ISSUE THREAD

**Issue by tinmoney** [near/near-wallet#2586]
US taxpayers need to document all blockchain transactions for tax reporting. 

While this can be manually done, it is cumbersome, even at small volumes. 

All other blockchain explorers I am aware of have the ability to download a .csv transaction history file.

NEAR does not support this feature. I think it should.

**Comment by gutsyphilip** [comment]
Thanks for opening this issue @tinmoney.
It has been forwarded to the appropriate team to take it from here.

cc: @frol

**Comment by frol** [comment]
There is a relevant discussion on NEAR Explorer bug tracker: https://github.com/near/near-explorer/issues/422
