### ISSUE TITLE
Swap reverts back to pairing option when price refreshes.

### ISSUE THREAD

**Issue by joe-rlo** [near/near-wallet#2610]
**Problem**
If the user chooses swap and the chooses to invert the direction (USN -> NEAR v. NEAR -> USN) then the initial swap direction reverts when the price refreshes.  This causes confusion to the user as the pairing can become negative.

**Expected Behavior**
If the user changes the direction, the swap direction should be retained

**Steps to reproduce**

1. Select swap from either token
2. Enter value in top token
3. Invert the pairing
<img width="652" alt="Screen Shot 2022-04-25 at 4 53 28 PM" src="https://user-images.githubusercontent.com/103778941/165173667-541a214e-04c9-4f92-8ee1-da8dfb670eeb.png">
<img width="642" alt="Screen Shot 2022-04-25 at 4 53 39 PM" src="https://user-images.githubusercontent.com/103778941/165173670-7734e0e2-43a1-43b0-a659-bd00ea6635ea.png">

**Comment by hcho112** [comment]
I believe this problem has been solved by UI improvements that has been released lately. 
<img width="596" alt="image" src="https://user-images.githubusercontent.com/6027014/173164405-c8557bab-9793-46f8-873c-8ba544785fb7.png">
![image](https://user-images.githubusercontent.com/6027014/173164415-40d6d70c-c2ef-4442-861f-4729f94f5fb2.png)

values are retained to corresponding selected coin type before/after swap. Will close this issue.
