### ISSUE TITLE
Undefined localization for a "Wallet" page

### ISSUE THREAD

**Issue by SerDorosh** [near/near-wallet#2634]
After git pull the master commit ([a753384](https://github.com/near/near-wallet/commit/a7533840a5194ce990c9bbc92fd98b7d0a545efb)) the main page (Wallet.js) crashes. 
When the function “getCurrentLanguage” is called it return “currentLanguage.code = undefined”.
![image-20220428-114052](https://user-images.githubusercontent.com/88776413/166918385-7816d5e6-9d7b-482c-b955-31e0b68cf58f.png)

**Comment by gutsyphilip** [comment]
Hi @SerDorosh, Thanks for opening this issue. The linked commit however doesn't seem to have any relation to the displayed error. It'd be great if you can share more context on this as replicating is an issue.  Happy to jump on a call to take a look if necessary.

**Comment by SerDorosh** [comment]
I found a problem. It was my local problem, and I solved it.  Sorry for disturbing.
