### ISSUE TITLE
Enabled an unavailable email for 2fa

### ISSUE THREAD

**Issue by RubyJiao** [near/near-wallet#2638]
**Problem**
Some users enabled an unavailable email for 2fa and they can do nothing with their accounts. They cannot disable or change 2fa as well because they cannot verification code.

**Expected Behavior**
Make sure email for 2fa enabled only once users enter a right verification code sent to an available email.

**Steps to reproduce**

1. set an email A(sometimes which may be a wrong address by mistake) for 2fa
2. cannot receive verification code(even it is a right email)
3. set another email B for 2fa
4. receive verification code and enter it
5. find email A enabled instead of B
6. can do nothing with the wrong 2fa enabled

**Comment by andy-haynes** [comment]
@RubyJiao I tested this out after applying the fix and it seems to be working now. Please let me know if you continue to see this behavior.

**Comment by RubyJiao** [comment]
@andy-haynes Thanks for fixing. Will the previously enabled wrong email be automatically removed?

**Comment by andy-haynes** [comment]
@RubyJiao unfortunately we can't fix that data retroactively. If the user has 2FA enabled but the email address is still incorrect then they will need to escalate to support to have the email address corrected.
