### ISSUE TITLE
HAPI integration 

### ISSUE THREAD

**Issue by Solniechniy** [near/near-wallet#2646]
## Problem
There is a problem with managing addresses that are under regulations during sanctions, scams, and so on.

#### What are we planning to do about it?
Integrate the HAPI protocol into the near wallet, which allows checking the address before sending the funds and displaying the information about it. 

#### Job Story(s)
- User wants to send funds to another address. While entering the address of the receiver wallet sends get requests to HAPI protocol in order to check any information about this address. If there is any - show it with the red alert or input border.

## Scope
- [x]  Create hapi service which will give the information about address in module/services
- [x]  Create the design proposal which will display the information about the checked address from HAPI protocol smartcontract 
- [x]  Expanding the wallet functionality according to created design proposal

**Comment by PinkiNice** [comment]
Implemented in #2840

**Comment by PinkiNice** [comment]
Implemented in #2840

**Comment by agileurbanite** [comment]
Wait did security review this service? @PinkiNice
