### ISSUE TITLE
Select HD Path for Enable Ledger on Existing Account

### ISSUE THREAD

**Issue by mattlockyer** [near/near-wallet#2657]
**Problem**

Enable Ledger uses default HD Path, no option to change like in recovery.

When securing with Ledger user should be able to choose HD Path. This changes the keypair used to secure the account. Since some people could use key inspection to identify accounts e.g. where was this key also used, **this is a major privacy issue for some people.**

**Expected Behavior**

Should be able to select HD Path to secure account with Ledger so the key used is different.

**Steps to reproduce**

1. Create account with seed phrase
2. Enable ledger (uses default HD Path)

**Comment by gutsyphilip** [comment]
Hi @mattlockyer. Thanks for raising this. I'll push an update that fixes this shortly.

**Comment by Patrick1904** [comment]
@gutsyphilip I believe this has been fixed? Can you please confirm and close this issue?
