### ISSUE TITLE
User should be not allowed to stake to account/contract with full access key

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#2672]
## Story

As a user who stakes, I want to be not allowed to staked to a contract/account that has full access key so I won't loose the funds.

## Acceptance Criteria

- [x] User is blocked from staking to the account/contract that has a full access key

**Comment by agileurbanite** [comment]
@ilblackdragon even if this is prevented by the wallet can't this be circumvented using the CLI or making a POST request to RPC?  We will prioritize on our end but should we reach out to respective projects to prevent users across the board?

**Comment by agileurbanite** [comment]
@morgsmccauley FYI
