### ISSUE TITLE
Incorrect order of dapp transaction actions ?

### ISSUE THREAD

**Issue by paouvrard** [near/near-wallet#2675]
**Problem**
When transferring $NEAR from NEAR network to Aurora, $NEAR is wrapped to wNEAR (`near_deposit`) then transferred (`ft_transfer_call`).
Clicking on `+ More information` the first time, the actions are in the wrong order:
![image](https://user-images.githubusercontent.com/29397451/168414233-92553193-5609-4c66-a7ae-f2bb59adbcbc.png)
Going back and clicking on `+ More information` the 2nd time, the actions are back in the correct order:
![image](https://user-images.githubusercontent.com/29397451/168414349-b570cd43-49b6-4212-8887-925f26e1f2f3.png)

Clicking `+ More information` will switch the order of actions every time it is clicked.

**Expected Behavior**
`near_deposit` always comes before `ft_transfer_call`

**Comment by agileurbanite** [comment]
@paouvrard thanks for reporting this bug.  Are you open to submitting a PR to address this?  Open to contributions.

**Comment by agileurbanite** [comment]
@morgsmccauley as FYI

**Comment by marcinbodnar** [comment]
I checked the exact same type of transactions and I'm not able to reproduce the bug. Also checked the code where the transaction actions are sorted and everything seems to be working well.

@paouvrard Please check again, if you can reproduce it.

**Comment by paouvrard** [comment]
@marcinbodnar Thank you for looking into it. I did some more testing observed that it happens only in Firefox. The same transaction in Chrome doesn't switch the order of actions.
