### ISSUE TITLE
mystery: Wrong User Bug

### ISSUE THREAD

**Issue by chadoh** [near/near-wallet#2691]
Last Friday, dozens of people who were trying to participate in the [NearTrees](https://tenk-dao.github.io/neartrees/en/)' free mint saw incorrect accounts after signing in with NEAR Wallet.

* [dannyggc.near](https://explorer.mainnet.near.org/accounts/dannyggc.near) saw account [`e33e…`](https://explorer.mainnet.near.org/accounts/e33ecff38be0f68fbe28b59da9c4fef31691e49806804cfddd235c268dc73081):

    ![dannyggc-as-e33e](https://user-images.githubusercontent.com/221614/169844481-f8b3c434-8968-4775-90c4-788ad68b919d.png)

* [bitwine.near](https://explorer.mainnet.near.org/accounts/bitwine.near) saw account [smartovich.near](https://explorer.mainnet.near.org/accounts/smartovich.near):

   ![bitwine.near-as-smatovich.near](https://user-images.githubusercontent.com/221614/169844727-7bf0fb7e-299b-4ccd-ba6b-cf3c014efe01.png)

* [firstnft_mint.near](https://explorer.mainnet.near.org/accounts/firstnft_mint.near) saw account [ilya228.near](https://explorer.mainnet.near.org/accounts/ilya228.near):

   ![firstnft_mint.near as ilya228.near](https://user-images.githubusercontent.com/221614/169846335-2013b693-c64e-4621-ae8b-34f324074fe4.png)

In all cases:

* these were NOT accounts they had access to
* these WERE accounts of other people that were using the same app (UI at `tenk-dao.github.io/neartrees/en` + contract at [neartreesseeds.tenk.near](https://explorer.mainnet.near.org/accounts/neartreesseeds.tenk.near)) at the same time
* these users were UNABLE to do anything with these accounts — they could click to try to mint, which would redirect them back to NEAR Wallet, at which point NEAR Wallet would tell them they weren't unauthorized to do anything as the erroneous account

Things we're not sure about:

* At first we thought all users who encountered this bug might be in the same geographic region (Russia), but that is not true.
* It seems like when the error would occur, it would happen in a consistent way for a given user. That is, `dannyggc` only ever saw `e33e`, but not any other incorrect accounts. `bitwine` only ever saw `smartovich`; `firstnft_mint` only ever saw `ilya228`. 
* We don't yet have any evidence that this happened for the opposite users. As far as we currently know, `e33e` never saw `dannyggc`; `smartovich` never saw `bitwine`; `ilya228` never saw `firstnft_mint`. Furthermore, there's no evidence that these "opposite" accounts ever saw ANY incorrect accounts. In fact, it seems that everything worked fine for them. Click the links to NEAR Explorer above, and you'll see that they were all able to successfully mint their NearTrees Seed NFTs. This implies they were able to use the website without encountering any issues.

Other TenK-launched NFT projects have used similar URLs (https://tenk-dao.github.io/monkedemonz/en/, https://tenk-dao.github.io/im-question-mark/en/) with no issue. The only issue, which you'd expect, is that if you sign into one of these apps, you'll be signed into the others, because localStorage is scoped by domain (`tenk-dao.github.io`), not path (`/neartrees`, `/monkedemonz`, `/im-question-mark`). It **might** be relevant that the NearTrees launch attracted much more rapid traffic than the others, partly because it was a free mint.

These other projects also used similar codebases and dependencies. The frontend is always based on [TENK-DAO/frontend-starter](https://github.com/TENK-DAO/frontend-starter), which [uses](https://github.com/TENK-DAO/frontend-starter/blob/f06ceb594b330651be8392c30d315ffa67c3a78d/package.json#L15) a [lightly-customized branch of `near-api-js`](https://github.com/AhaLabs/near-api-js/tree/1.0.1). This NAJ branch does not change any of the core login logic.

On a call with `dannyggc.near`, @willemneal and I observed observed him sign in. It worked some of the times he tried. And sometimes when he would try, he would end up back at the NearTrees site still signed-out (inspecting localStorage showed pending keys, as seen in the first screenshot above). And one time while we watched, we did indeed get to see the bug in action: he clicked Login with NEAR, got routed to NEAR Wallet, picked `dannyggc.near` (it was the only option), and then landed back at the app at an incorrect URL (a probably-unrelated bug with near-api-js + Chrome caused the URL params to stick around rather than clearing, so he could copy-paste):

> ```https://tenk-dao.github.io/neartrees/en?account_id=e33ecff38be0f68fbe28b59da9c4fef31691e49806804cfddd235c268dc73081&public_key=ed25519%3AAojNGU8hCEg8jTUNh1Jj5x6p8X7vZEm7WHwk1NPT42ZX&all_keys=ed25519%3A6ML2vEJgKrZ9sSeoKEcZ1eWvjhnJfxa9wqQuAiZWFaik```

Note that this incorrect URL **IS** internally-consistent! If you use `near-cli` to inspect keys, you'll see that the `Aoj...` public key in the URL above goes with `e33e`, not `dannyggc`:

```bash
NEAR_ENV=mainnet near keys dannyggc.near | grep Aoj # nothing here
NEAR_ENV=mainnet near keys e33ecff38be0f68fbe28b59da9c4fef31691e49806804cfddd235c268dc73081 | grep Aoj # found it!
```

### Access Keys add correctly, though.

You can see that [dannyggc](https://explorer.mainnet.near.org/accounts/dannyggc.near) and [firstnft_mint](https://explorer.mainnet.near.org/accounts/firstnft_mint.near) both successfully added lots of access keys for `neartreesseeds.tenk.near`. Not sure what was going on with [bitwine.near](https://explorer.mainnet.near.org/accounts/bitwine.near), but lots of other users in the NearTrees Discord who encountered the bug also showed screenshots of their NEAR Wallet showing correctly-added access keys.

## Where's the bug happen, then?

Possible explanations:

1. NEAR Wallet, having correctly added the key on line 207 of [allowLogin](https://github.com/near/near-wallet/blob/fa7a7f6898805b11ec6b00a1520d0e284f88fc04/packages/frontend/src/redux/actions/account.js#L198-L225), then somehow constructs a return URL with bad params on lines 209-219. We really can't fathom the mechanism by which this code might grab some other account, which has recently logged into the same contract, and return its ID and pubKey by mistake.

2. NEAR Wallet returns the user to the page with correct params, and then when the page loads its JS and initializes `near-api-js`, `near-api-js` somehow makes RPC queries to the contract, finds other accounts that recently logged in, and _replaces the correct URL params_ with the incorrect-but-internally-consistent ones. We again can't conceive of any mechanism that would cause this behavior, nor does it even seem possible to make [such RPC requests](https://docs.near.org/docs/api/rpc/contracts).

3. _[warning: tin hat conspiracies ahead]_ NEAR Wallet redirects to the correct URL, but when the user's browser tries to fetch the content for this URL, their request is intercepted. By... malware? A VPN with some strange caching behavior? The Russian Iron Curtain firewall?? This man-in-the-middle snoops on their request, decides it looks ok, but has a misconfigured cache and accidentally mucks up their request, handing them a version with someone else's URL params. (Even if something like this is actually happening, it really doesn't seem like an intentional attack, but feels more like erratic caching issues.)

We honestly have no other leads right now, and none of these explanations feels satisfying, _especially_ since not all the people who encountered this bug are in Russia.

## Steps to reproduce

hahahahahaha

**Comment by chadoh** [comment]
@MaximusHaximus I met with @Patrick1904 and @willemneal last Friday to investigate this issue, and @Patrick1904 recommended making this issue so that you could help troubleshoot. Any idea of where to look next?

**Comment by Shane-Neeley** [comment]
The team said a potential issue could be in github pages hosting, and they've switched to recommending CloudFlare hosting. I don't see that mentioned here. Is there any more guidance on that? We're not minting until a couple months so we're just watching this issue. Thanks.

**Comment by Patrick1904** [comment]
@chadoh I'm closing this as I think you figured out there was an issue with github pages hosting and unrelated to the wallet? Please re-open the issue if I'm wrong.
