### ISSUE TITLE
How to run the frontend application

### ISSUE THREAD

**Issue by cpestano2099** [near/near-wallet#2696]
Hi, I'm just new here. I'm trying to run the front end application. I have a question, is the browser page supposed to be empty? I used a virtual box and linux OS since the app only seems to run on a linux environment.  Could it be because it could not load the source files? 

1. Installed a Oracle VM Virtual Box
2. Download ubuntu linux OS.
3. Install nodejs
4. install yarn
5. run app using yarn && yarn start

![image](https://user-images.githubusercontent.com/101170735/170046062-eb6938a5-0e64-407a-8cd0-394edc0bc20e.png)
![image](https://user-images.githubusercontent.com/101170735/170046109-b3987308-087a-4bad-b59f-f87f055881c9.png)

**Comment by andy-haynes** [comment]
Hey @cpestano2099 I think the issue here is that the `NEAR_WALLET_ENV` variable is not set. Can you please try running step #5 as `yarn && NEAR_WALLET_ENV=testnet yarn start` instead please?

I'll update the documentation to make the run command more clear.

**Comment by andy-haynes** [comment]
Documentation updated in #2713
