### ISSUE TITLE
requestSignIn method returns a strange callback URL

### ISSUE THREAD

**Issue by brefchan** [near/near-wallet#2704]
**Problem**
When I used the requestSignIn method, it was weird to call back the URL if the success_url format was passed in hash mode

**Expected Behavior**
When the url of the incoming method is"https://localhost:8888/#/success",I want to get callback url is "https://localhost:8888/#/success?accountId....."
but I got "https://localhost:8888/?accountId...../#/success" or "https://localhost:8888/#/?accountId....."
In the first case, I pass in an ascii encoded URL，the other,I pass in an origin URL.

**Steps to reproduce**

1. first case，I pass in "https://wallet.testnet.near.org/login/?referrer=genesis.brefdao.testnet&contract_id=genesis.brefdao.testnet&success_url=https://localhost:8888/#/success&failure_url=https://localhost:8888/#/fail&app_url=https://localhost:8888/#/success&public_key=ed25519:HrP5qENGKjb19BZ3NddXZp6y1dmJ7AvtYWu9h4uPCF3Z"
2. second case, I pass in "https://wallet.testnet.near.org/login/?referrer=dao&contract_id=genesis.brefdao.testnet&success_url=http%3A%2F%2Flocalhost%3A8888%2F%23%2Fsuccess&failure_url=http%3A%2F%2Flocalhost%3A8888%2F%23%2Ffail&app_url=http%3A%2F%2Flocalhost%3A8888%2F%23%2F%3A%2F%2F&public_key=ed25519%3AHDYhHtbhMF3MuihpGYCyAvEukXuuGaJPxFk4JeenVsih"

**Comment by hcho112** [comment]
Hey @brefchan, 
I got it working by adding `s` next to `success_url` on second your case. Can you try as well? 
if you are running local wallet instance at port 8888:
[link](https://wallet.testnet.near.org/login/?referrer=dao&contract_id=genesis.brefdao.testnet&success_url=https%3A%2F%2Flocalhost%3A8888%2F%23%2Fsuccess&failure_url=https%3A%2F%2Flocalhost%3A8888%2F%23%2Ffail&app_url=https%3A%2F%2Flocalhost%3A8888%2F%23%2F%3A%2F%2F&public_key=ed25519%3AHDYhHtbhMF3MuihpGYCyAvEukXuuGaJPxFk4JeenVsih)
