### ISSUE TITLE
Problem when we are not able to load account data

### ISSUE THREAD

**Issue by marcinbodnar** [near/near-wallet#2719]
When the user has an active account, and for any reason, we cannot load the account data, weird things start to happen. First thing is that the balance is showing `0` instead of the loader. Additionally, if the user changes the route, the balance is loaded, but the USD value is not showing. Also, the account page looks like for zero balance account.

**Comment by Patrick1904** [comment]
@marcinbodnar do you happen to have steps to reproduce the above behavior?

**Comment by marcinbodnar** [comment]
You can just throw an error in `loadAccount` method.
