### ISSUE TITLE
Newly created account on testnet cannot be imported into wallet again

### ISSUE THREAD

**Issue by think-in-universe** [near/near-wallet#2729]
**Problem**
The newly created account on testnet cannot be imported into wallet again in another browser session.

When try to import the new account with seed phrase, the below error were met. 

<img width="506" alt="image" src="https://user-images.githubusercontent.com/46699230/172428885-9dd76496-b1d5-4ab0-a306-035a5ebf6bcb.png">

**Expected Behavior**
The newly created account on testnet wallet, should be able to be imported in another browser session / device

**Steps to reproduce**

1. Create a NEAR testnet account via NEAR Wallet: https://wallet.testnet.near.org, and save the seed phrase
2. Open a new NEAR testnet Wallet session in an incognito window. Recover the account with the saved seed phrase: https://wallet.testnet.near.org/recover-seed-phrase
3. The "No accounts were found for the seed phrase" error popup when recovering the account

**Comment by andy-haynes** [comment]
@think-in-universe It's working fine for me and I don't see any errors being returned from the indexer over the last 12 hours in testnet. Is it still happening for you?

Next time you see this and are able to reproduce it consistently, please include the network response data from your browser's development console. The response from our service may contain more details we can use to determine the issue.

**Comment by andy-haynes** [comment]
Using the public key from the attached screenshot I was able to verify that the key does exist in testnet by querying the indexer directly. In this case I think it was likely an intermittent issue with the testnet indexer that has since been resolved. Feel free to re-open if the issue starts happening again.

**Comment by think-in-universe** [comment]
@andy-haynes  thanks. 

yeah. I think it's temporary issue. now it's working.
