### ISSUE TITLE
Bumping Linkdrop Attached GAS

### ISSUE THREAD

**Issue by BenKurrek** [near/near-wallet#2755]
I'm currently working on the [linkdrop proxy](https://github.com/near-examples/linkdrop-proxy) contract which allows for NFTs, FTs, and arbitrary function calls to be executed upon claiming a linkdrop. Currently, 100 TGas is being attached to the `claim` and `create_account_and_claim` functions which has made it extremely tight when writing the logic and creating interesting onboarding experiences for users.

Can we bump this number to 150 or 200 TGas? What are people's thoughts on this?

**Comment by judith-Near** [comment]
I think this should be fine, if a user attaches more gas than the gas used then the system sends a refund -- you can see this in the refund receipt in the transaction execution plan. We still shouldn't go too high on the gas, because it might not be refunded the exact amount back, but 150 or 200 TGas should be fine.

**Comment by BenKurrek** [comment]
Awesome should I throw up a PR or is that something y'all handle?

**Comment by BenKurrek** [comment]
bumping gas is not needed and should not be done. Everything right now works with 100 TGas. If we bump the gas, the access key allowance for all keys will go up significantly which means higher upfront costs for users.

In the far far future, however, if we want to add much more complicated scenarios like transferring many different FTs and NFTs in the same key use, we could allow the Gas attached to be embedded into the linkdrop itself so it’s like /linkdrop/contract/secreteKey#gas=GAS_AMOUNT and this gas param would be attached. That way for specific drops that need more Gas, they can specify it and it doesn’t harm everybody else’s upfront costs

I was unaware of the access key pessimistic allowance calculation before this PR was created
