### ISSUE TITLE
Collectibles Tab Crashing

### ISSUE THREAD

**Issue by BenKurrek** [near/near-wallet#2762]
**Problem**
When I navigate to my collectibles tab, I get a blank screen and when opening the console, it looks like a crash. My account ID is `benjiman.testnet` 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/57506486/174611509-e1438bd9-b73d-444b-9dac-1f4be0d3f336.png">

**Comment by judith-Near** [comment]
addressed by [PR](https://github.com/near/near-wallet/pull/2764)
