### ISSUE TITLE
Wallet always returns errorCode=userRejected regardless of transaction outcome...

### ISSUE THREAD

**Issue by june07** [near/near-wallet#2823]
**Problem**

Wallet always returns errorCode=userRejected regardless of transaction outcome...

Is this the problem?  Specifically https://github.com/near/near-wallet/blob/3544aab589850097640cd3861687431076995e66/packages/frontend/src/routes/SignWrapper.js#L109

https://github.com/near/near-wallet/blob/3544aab589850097640cd3861687431076995e66/packages/frontend/src/routes/SignWrapper.js#L109-L115

**Expected Behavior**

Non rejected transactions shouldn't have this error attached.

**Steps to reproduce**

1. Use the wallet.
2.  A quick search for "userRejected" on discord shows tons of wallet urls with the same "errorCode=userRejected" error string in the wallet url.

**Comment by Patrick1904** [comment]
Thank you for reporting this bug @june07 - a fix is being added here: https://github.com/near/near-wallet/pull/2824
