### ISSUE TITLE
Is near wallet local down?

### ISSUE THREAD

**Issue by siddharth-teli** [near/near-wallet#2833]
**Problem**
I am running near wallet locally, connected to testnet config. After account creation, near balance in dollar is blank, I can't send near token.
![Screenshot from 2022-07-21 21-29-37](https://user-images.githubusercontent.com/107669916/180261742-9009759a-4028-4eee-bf01-06366a7d6be9.png)

**Expected Behavior**
Balance should not be blank. I should be allowed to send near.

**Steps to reproduce**

1. Clone near waller repo & checkout latest tag.
2. Create .env file set NEAR_WALLET_ENV=testnet

**Comment by roshaans** [comment]
I would double check the RPC endpoint to see if it was experiencing any disruption or downtime.
