### ISSUE TITLE
Cannot transfer NEAR on testnet. Continue button remains disabled after entering valid recipient

### ISSUE THREAD

**Issue by mpeterdev** [near/near-wallet#2848]
**Problem**
`Continue` button is not enabled after entering valid recipient address when trying to transfer NEAR on testnet wallet

Reproduced on Brave and Firefox Developer Edition

**Expected Behavior**
Button should be enabled when `Send to` field is validated

**Steps to reproduce**

1. Open testnet wallet
2. Click `Send` button
3. Enter 1 NEAR as amount
4. Click `Continue`
5. Enter valid testnet address in `Send to` field
6. `Continue` button remains disabled

**Comment by mpeterdev** [comment]
![Screen Shot 2022-07-26 at 11 45 04 AM](https://user-images.githubusercontent.com/24904709/181092601-87e921cb-60ae-48c7-be30-ed475e76b907.png)

**Comment by esaminu** [comment]
Thanks for reporting @mpeterdev ! We reverted these changes yesterday in #2850 while the team works on a fix 😃
