### ISSUE TITLE
Transaction failed 

### ISSUE THREAD

**Issue by srinivasan-nodeworks** [near/near-wallet#2878]
Hi team,
I try to Transfer 255USDC from my Mainnet near wallet **1ff536295550bbf8a0cc3ccfe660d919ccaf29b62d004adc6013383b4b14ed33** to  this Mainnet Near wallet  **730047a68211b10d914056a256dadcdfb0ca640ae834cade07e592db8a173dbb**
 it shows the transaction is failed, but those USDC gone from my account and receiver also doesn't receive those USDC.  so kindly help me to sort out this problem, and bring me back those USDC, I attached the screenshot of the transaction and the transaction link.
                                   thank you.

https://explorer.mainnet.near.org/transactions/2veAnsjGia9RLVnJBYHucLvbNBTaWdUsEitLEdCTCzmW
 
![Screenshot from 2022-08-09 12-03-45](https://user-images.githubusercontent.com/89574213/184064964-9d7889aa-d477-4a42-b719-f81cd8c15359.png)
![Screenshot from 2022-08-10 15-32-47](https://user-images.githubusercontent.com/89574213/184064991-f84f3cc6-a304-441a-a4f3-26c5667bf679.png)

**Comment by roshaans** [comment]
@srinivasan-nodeworks were you able to resolve this issue?

**Comment by srinivasan-nodeworks** [comment]
still the issue doesn't solve.

**Comment by roshaans** [comment]
Hello @srinivasan-nodeworks, I did some digging into your mainnet account: **1ff5362...3b4b14ed33**

There does not seem to be any USDC transfers into this account. Where did you send these funds to this account from? They may still be sitting there. 

You can view your **txs** through this link: 
https://nearblocks.io/address/1ff536295550bbf8a0cc3ccfe660d919ccaf29b62d004adc6013383b4b14ed33#transaction

**Comment by srinivasan-nodeworks** [comment]
You can view this transaction https://nearblocks.io/txns/2veAnsjGia9RLVnJBYHucLvbNBTaWdUsEitLEdCTCzmW#
i already explain my situation here https://github.com/near/near-wallet/issues/2878#issue-1335460783
sorry for the late reply

**Comment by srinivasan-nodeworks** [comment]
r u there @roshaans

**Comment by roshaans** [comment]
Hey @srinivasan-nodeworks, i'll get back to you with a detailed answer by tonight or early morning tomorrow. Apologies for the delay

**Comment by roshaans** [comment]
Hello @srinivasan-nodeworks, I had a colleague of mine look through the problem as well. They also think that you account **1ff536295550bbf8a0cc3ccfe660d919ccaf29b62d004adc6013383b4b14ed33** did not have any USDC to begin with. The transactions you are seeing are failing because of the error message that your recipient address is not a registered account, which might have been true, but it is also the case that you did not have any USDC in your account, which is why nothing got returned back to you. I hope this makes sense. I would advise to go into the Near Discord channel.

**Comment by srinivasan-nodeworks** [comment]
thank you for the response @roshaans 
i create the account and then it shows to register account, in that time i receive the USDC before registration, that's the main problem
