### ISSUE TITLE
Gracefully handle email/phone recovery setup failure

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#338]
## Story

As a user, if I encounter persistent errors during email/phone recovery setup, I want to setup recovery at a later time so I can continue using the wallet.

## Acceptance Criteria

- [ ] On email/phone failure, user is presented "Setup Later" option
- [ ] Selecting "Setup Later" redirects the user to original destination

**Comment by Patrick1904** [comment]
Multiple failed attempts may trigger a modal w/ 'setup later' option

**Comment by vgrichina** [comment]
Yeah, we also need something on wallet home page to re-engage people who didn't setup any recovery method successfully.

This would help mitigate impact of issues like  https://github.com/nearprotocol/near-wallet/issues/421

This one could have been avoided by us, but often there can be deliverability issues outside of our control – so good to have solution which mitigates it.

**Comment by corwinharrell** [comment]
What are some examples of errors which may occur during  recovery setup?

**Comment by corwinharrell** [comment]
Do we have any insight into the frequency with which this has occurred?

**Comment by kcole16** [comment]
> Do we have any insight into the frequency with which this has occurred?

@corwinharrell Here is an example: https://github.com/nearprotocol/near-wallet/issues/421

Hard to say re: frequency. Generally this will be due to Twilio (SMS) or Sendgrid (Email) issues. Can likely address this with "Setup Later" #415

**Comment by Patrick1904** [comment]
Closing as issue is outdated
