### ISSUE TITLE
Landing page for the Wallet

### ISSUE THREAD

**Issue by Patrick1904** [near/near-wallet#426]
### Overview
Initially, all NEAR Wallet accounts will be created through Linkdrop. Any direct visitors to the Wallet without an account should be redirected to a landing page (instead of `/create`), which will explain where to obtain a link (and offer login/recovery options for existing users).

### Copy Snippets
- Currently, the Wallet is in private beta. If you'd like to participate, please contact us on Discord.
- NEAR is here.
- Securely store your NEAR tokens and compatible assets with the NEAR Wallet.
- If you already have an account, please select from the following
  - Sign-in with Ledger
  - Recover Account
- “Sign up below for early access”

### Acceptance Criteria
- [ ] Users without an account are redirected to the landing page
- [ ] Ledger and recovery links are visible to the user
- [ ] Users can enter their email to sign up for the mailing list (see embed snippet)

**Mailchimp Embed Snippet**
```
<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://nearprotocol.us14.list-manage.com/subscribe/post?u=faedf5dec8739fb92e05b4131&amp;id=4470dc6b88" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address </label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_faedf5dec8739fb92e05b4131_4470dc6b88" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
```

**Comment by Patrick1904** [comment]
@kcole16 @vgrichina @corwinharrell

**Comment by corwinharrell** [comment]
@Patrick1904 assuming this would be lower priority than the majority of other tasks that are in the backlog for the wallet?

**Comment by corwinharrell** [comment]
@Patrick1904 do you see this being a page that is presented to users without an account before the "Create Account" page?

**Comment by Patrick1904** [comment]
We could enhance our current 'create account' page or a separate page. I feel like something is missing if the wallet only has a minimal login page without more information. [Coinbase](https://wallet.coinbase.com/) is pretty extensive. It's something we'll need to do before launch.

**Comment by Patrick1904** [comment]
> We could enhance our current 'create account' page or a separate page. I feel like something is missing if the wallet only has a minimal login page without more information. [Coinbase](https://wallet.coinbase.com/) is pretty extensive. It's something we'll need to do before launch.

We could enhance our current 'create account' page or a separate page. I feel like something is missing if the wallet only has a minimal login page without more information. [Coinbase](https://wallet.coinbase.com/) is pretty extensive. It's something we'll need to do before launch.

**Comment by Patrick1904** [comment]
@corwinharrell I think the 'create account' page is good for new users (not logged in) coming from an app to sign a transaction. But users coming from direct traffic to the wallet or from search engines may benefit from some more information?

**Comment by corwinharrell** [comment]
@Patrick1904 yeah +1 to this I think it would be good to put something simple together. @jakestutzman is in the midst of exploring some brand evolution stuff so the design might could even be informed by that but in the meantime I'd be happy to create a wireframe so we can think about content. This is low on the list of priorities IMO but I'm sure we're all on the same page there and I've assigned myself to this so it appears in my ZenHub and doesn't get forgotten

**Comment by kcole16** [comment]
@corwinharrell This is another one we're adding to the queue (though currently lowest priority of the pre-token sale items).

### Details
Users will need a Linkdrop link to create an account, and we want to use this page to explain that and advertise ways to get a link.

e.g. token sale, Flux, airdrops, etc

**Comment by corwinharrell** [comment]
![NEAR Wallet Landing](https://user-images.githubusercontent.com/5934188/88069213-2c031880-cb3f-11ea-8f14-f0cc018a0e49.jpg)

@kcole16 @Patrick1904 This is how the basic landing page has shaped up. Need a little bit of direction around how exactly we want to frame the content around LinkDrop as a prerequisite. The CTAs right now are just based off of the issue description that Patrick provided early on.

**Comment by corwinharrell** [comment]
@jakestutzman Feel free to provide any feedback on the design (not much here since we're keeping it simple for the initial launch) Gonna provide an alternate version using Inter across the board once we nail down the copy around linkdrop, etc... You can see how that looks here: https://www.figma.com/file/PqdzVjhKTJqGuokDjykMUv/Wallet-Landing-Page?node-id=0%3A1

**Comment by corwinharrell** [comment]
A few variations:

<img width="1015" alt="Screen Shot 2020-07-21 at 12 04 47 PM" src="https://user-images.githubusercontent.com/5934188/88079245-6f638400-cb4b-11ea-856a-1874b3c9aec1.png">

**Comment by kcole16** [comment]
@Patrick1904 Added the Mailchimp embed form above, which we _might_ be able to convert to jsx and style. If not, can use the API.

**Comment by Patrick1904** [comment]
@corwinharrell @kcole16 LGTM. Some thoughts/questions:

1. Blue banner text will be two lines on mobile. Short text version ok?
2. Are we not stacking mail input and cta on mobile? That's fine but there won't be much space for email on older/smaller phones
3. Are we adding the near.org footer? It seems suboptimal as the navigation links aren't shown on mobile. We'll have to re-create it in wallet (not salvageable).
4. I agree with Jakes slack comment that black newsletter background makes the most sense.

**Comment by kcole16** [comment]
1. Maybe "NEAR Wallet is in Private Beta. Sign up below for access" if that's short enough. Or even just "NEAR Wallet is in Private Beta"
2. Makes sense to me to stack, but up to @corwinharrell 
3. I think we should stick with the current Wallet footer
4. Black works for me

**Comment by corwinharrell** [comment]
Alright so here's the last iteration based on everyone's feedback. @Patrick1904 one thing to note is that this version uses the Inter typeface that we've anticipated switching to for some time. @jakestutzman and I were exploring its use here. Since it's crunch time before launch, my gut tells me that implementing this in addition to making the switch to Inter as the primary wallet UI typeface is going to be too much to try and squeeze in before launch. If this is the case, we can stick to using our existing fonts for now, and worry about making that switch later. I'll let you make that call since you'd be making those changes.

<img width="1373" alt="Screen Shot 2020-07-23 at 11 29 22 AM" src="https://user-images.githubusercontent.com/5934188/88306177-681db100-ccd8-11ea-83d6-7676794f4ece.png">

**Comment by corwinharrell** [comment]
I will provide a replacement screenshot for use in the iPhone mockup shortly.
