### ISSUE TITLE
Require email/phone verification during recovery setup

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#450]
## Overview
Requiring verification of the email account or phone number used for recovery will ensure the user has entered it correctly, and that they actually have access to the email/phone. 

Additionally, we've received feedback from users the current flow feels unusual.

## Proposed User Flow
1. User enters email/phone, selects "Verify" button
    - User is redirected to `/verify`
2. User receives message with a confirmation code
3. User enters code, selects "Confirm" button
    - Option to "Setup Seed Phrase" if they cannot confirm

**Comment by kcole16** [comment]
@Patrick1904 @corwinharrell @vgrichina Thoughts?

We'd discussed only requiring this if the user sets up email/phone recovery post-creation, but have received some feedback the flow feels strange without it.

**Comment by corwinharrell** [comment]
I'm all for this. Would improve security and ensure that users are not setting up accounts with incorrect recovery methods.

**Comment by corwinharrell** [comment]
@Patrick1904 @kcole16 the only real design change needed here is the addition of an input for a confirmation code on the confirmation screen, correct? (In addition to the various states that would accompany it)

**Comment by corwinharrell** [comment]
Also, why does this need to be code and not a magic link? Isn't it easier to just click a link in an email or confirmation message which then auto-confirms the address/phone #?

**Comment by Patrick1904** [comment]
We're pretty much done implementing MVP for this and it involves an input to enter the security code that we sent to your email/phone. 

We currently cannot offer a link option because if you enter the wrong email, the person who owns that email can click the link and then _automatically get a magic link sent to them_.

We'll get a testing env setup soon and can make any adjustments to the design then.

**Comment by corwinharrell** [comment]
Any context as to why this was closed? @vgrichina @kcole16

**Comment by Patrick1904** [comment]
> Any context as to why this was closed? @vgrichina @kcole16

MVP was merged https://github.com/near/near-wallet/pull/559
