### ISSUE TITLE
Fungible Token Support

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#456]
### Overview 
Fungible token (FT) support in the wallet is required by several of our app developers (Flux, Stardust, Upshot, etc), and is necessary for proper ETH Bridge support (handling wrapped ETH and ERC20 tokens). 

At a minimum, we need to display the balances of a subset of tokens that meet the FT standard.

[FT Standard NEP](https://github.com/nearprotocol/NEPs/pull/21)
[FT Implementation](https://github.com/nearprotocol/near-sdk-rs/tree/master/examples/fungible-token)

### Stories
As a user, I want to view the token balances of my account, so I can understand my current asset position.

As a user, I want to directly view and confirm transactions that involve my tokens, so I can prevent misuse. 

As a user, I want to send and receive tokens from the Wallet, so I can pay for items with tokens.

**Comment by Patrick1904** [comment]
Closing as issue is outdated
