### ISSUE TITLE
Display exact token balances

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#473]
### Overview
As mentioned in #449, users of the wallet do not have an intuitive way to view their entire token balance. 

We currently handle this in Explorer by displaying the exact balance in yoctoN in a tooltip, but this approach has limitations (and is currently quite difficult to understand).

### Goals
- Keep the balance readable by default (`10.54 N` rather than `10.539823823 N`)
- Provide a view of the full balance (via tooltip, CTA, etc)
- Communicate the utility of small balances (`<0.00001 N` can be used for small number of TXs)

**Comment by Patrick1904** [comment]
Closing as issue is outdated
