### ISSUE TITLE
LocalStorage cleared after 7 days on WebKit-based browsers

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#479]
### Overview
Starting in [iOS 13.4 and Safari 13.1](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/), LocalStorage will be cleared after 7 days of no user interaction on a site. This will affect a significant percentage of Wallet users.

> Now ITP has aligned the remaining script-writable storage forms with the existing client-side cookie restriction, deleting all of a website’s script-writable storage after seven days of Safari use without user interaction on the site. These are the script-writable storage forms affected (excluding some legacy website data types): 

> Indexed DB, LocalStorage, Media keys, SessionStorage, Service Worker registrations

Apps installed to the home screen will be exempt from this, though the specifics are unclear (given that these apps still run in Safari). 

> Web applications added to the home screen are not part of Safari and thus have their own counter of days of use. Their days of use will match actual use of the web application which resets the timer. We do not expect the first-party in such a web application to have its website data deleted.

We should develop a solution to persist these keys beyond the 7 day inactivity period.

**Comment by kcole16** [comment]
My thoughts on this:

**Short term**
- Enforce account recovery setup on every account (email/phone/seed phrase)
   - Verify user access to the email address or phone number they enter
   - Send the account creation transaction post-recovery setup, including the recovery key in the TX (as opposed to sending the creation TX first, then another TX adding the recovery key)
- Warn iOS/Safari users they will need to recover accounts after 7 days of inactivity
- Give option to "Install to Homescreen" to prevent this

**Mid term**
- Evaluate the following options
   - Native app for key management
   - [Audius-style](https://github.com/AudiusProject/hedgehog) password-based key management (combine user-entered password + server-side entropy to generate key)
   - Use a [Torus](tor.us) or [Authereum](authereum.org) OAuth-style login

**Comment by vgrichina** [comment]
Long term we have to implement "Sign in with Apple", as this is requirement for all apps which do provide sign-in though third-parties.

**Comment by vgrichina** [comment]
> Audius-style password-based key management (combine user-entered password + server-side entropy to generate key)

We also can also try to rely on password management provided by iOS (i.e. give users instructions on how to generate password using iOS Keychain). This likely is good enough as the only source of entropy (done completely client-side).

**Comment by jimmy3dita** [comment]
We may solve with a different approach, i.e. Torus login
