### ISSUE TITLE
Display locked token balance

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#481]
### Overview
Users of the wallet will often not have full control over their NEAR tokens. There are four main reasons for this, the first two of which are covered by this issue.
- Vesting
  - Several community members (NEAR team, contributors) have tokens that vest over time, and will be unlocked linearly, block by block
- State stake (Minimum Balance)
   - There is a minimum required balance ([NEP #40](https://github.com/nearprotocol/NEPs/issues/40)) for all accounts. This can only be transferred by deleting the account
- Staking
- Delegating

### Story

As a user, I want to view both my active and locked (vesting, state staked, etc) token balances, so I can understand the quantity of tokens that are fully usable and transferrable.

As a user, I want to be prevented from attempting a transaction that will go over my available balance, so my transaction doesn't fail.

### Acceptance Criteria

- [x] Total NEAR balance (available+locked) is visible
- [x] Available NEAR balance is visible (total - locked)
- [x] Locked NEAR balance is visible, and broken down into
   - [x] Staked
   - [x] Minimum Balance (`storage_used` * `cost_per_byte`)
- [x] Difference between locked and available is explained
- [x] User is prevented from submitting TX to `Send Money` over their available balance
- [x] Available balance is viewable on `Send Money` page, with explanation
- [x] User is prevented from submitting TX `Login` or `Sign` over their available balance
- [x] Available balance is viewable on `Login` and `Sign` page, with explanation
- [x] Minimum balance is explained
- [x] Mobile ok
- [x] Tested

**Comment by kcole16** [comment]
@frol Will we be able to get a locked balance breakdown from this RPC endpoint? https://docs.nearprotocol.com/docs/interaction/rpc#accountaccount_id

**Comment by kcole16** [comment]
Rephrasing: Which of the "locked" balance types (staked, vesting, state stake) will be included in the `locked` parameter returned from the `account` RPC endpoint?

**Comment by frol** [comment]
Locked balance includes validator stake. Vesting is going to be implemented on the level of the contracts, so I assume it will be treated as a token transfer (@evgenykuzyakov is this accurate?). I am not sure where the state stake fit (@ilblackdragon can you help here?).

**Comment by bowenwang1996** [comment]
Lockup will have to be separately considered because it requires interaction with the contract deployed on the account. To support that, we need a way to tell whether the account has a lockup contract deployed.
