### ISSUE TITLE
Handle RPC timeout during TX confirmation

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#498]
### Overview

If a transaction takes too long to confirm and RPC times out, the user should be informed about the TX's status until it is finalized. One way to do this is to send the user to a "Timed Out" page, which gives the user the option to view the TX in Explorer.

**Note**: We do not currently have a good way of pending TXs in Explorer, and might need to handle this on the Wallet side for the time being.

### Story

As a user, I want to know the most recent status of my transaction until it is finalized (success or failure), so I can decide if I need to resend it or not.

**Comment by kcole16** [comment]
@frol Do we have a practical way of displaying "Pending" TXs in Explorer? Or should we expect to handle this on the Wallet side?

**Comment by frol** [comment]
To begin with, there is no way to fetch pending TXs via RPC... I think this particular case should be handled on the Wallet side by polling `tx` endpoint and displaying "Pending". However, we need to have some way of displaying pending transactions on Explorer as well, but I will need to learn more about the transaction lifetime inside nearcore to even know if this is possible (I had this conversation before and I am under impression that it is not that easy if possible to do reliably)

**Comment by marcinbodnar** [comment]
@kcole16 Is there a way to reproduce the timeout situation?

**Comment by bowenwang1996** [comment]
It is difficult to do on a live network. To consistently reproduce it I believe some local network is needed.

**Comment by kcole16** [comment]
Closing in favor of #623, which is more comprehensive
