### ISSUE TITLE
Setup bug reporting software (BugSnag, Sentry)

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#506]
### Overview
Using bug tracking/log reporting services such as BugSnag/Sentry will help us catch production issues quickly, and provide user logs and context to help debug.

### Acceptance Criteria
- [x] Logs HTTP errors
- [x] Logs client-side errors (JS, React, etc)
- [x] Does not log the following data
  - [ ] Account name
  - [ ] Email
  - [ ] Phone
  - [x] Seed phrase

**Comment by vgrichina** [comment]
This is not done, checklist not complete. Still need to filter data out client side (seed phrase in url gets logged).
