### ISSUE TITLE
URLs with account names + suffixes lead to 404

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#531]
**Problem**
All URLs that include an account name with a suffix (e.g. https://wallet.nearprotocol.com/profile/kendall.test) resolve to 404. It appears this is an issue with. including `.` in the URL.

**Expected Behavior**
URLs should correctly resolve.

**Steps to reproduce**

1. View https://wallet.nearprotocol.com/profile/emailagain to see expected behavior
2. View https://wallet.nearprotocol.com/profile/emailagain.test to see bug

**Comment by kcole16** [comment]
Comments from @vgrichina 
> I've noticed it before and AFAIK it's caused by how URL rewrites work on Render. We can workaround by running own HTTP server vs relying on whatever they provide for free, but they also promised to fix it (just will take some time).

**Comment by marcinbodnar** [comment]
@vgrichina so there is nothing we can do at this moment?
