### ISSUE TITLE
Designs for recovery email

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#560]
### Overview
Our current recovery email is only text, and looks a bit basic/MVP. 

### Acceptance Criteria
- [ ] "Recover Account" is a button, rather than a link
- [ ] NEAR logo is present

### Email Copy
```
Hi <account_id>,

This email contains your NEAR Wallet account recovery link.

Keep this email safe, and DO NOT SHARE IT! We cannot resend this email.

Click below to recover your account.

<Recover Account>
```

### Audius Example
<img width="936" alt="Screen Shot 2020-05-05 at 3 00 02 PM" src="https://user-images.githubusercontent.com/5624527/81120501-b3969f00-8ee1-11ea-88ae-f055f574a778.png">

**Comment by corwinharrell** [comment]
Figma file for new email designs: https://www.figma.com/file/rUZj2V20yoVNw6xZifLlw4/560-Recovery-Email?node-id=116%3A70

And here's a preview:

<img width="1072" alt="Screen Shot 2020-08-05 at 12 21 46 PM" src="https://user-images.githubusercontent.com/5934188/89438183-7f1bc480-d716-11ea-8d1e-84368e398bca.png">

**Comment by picturepan2** [comment]
@corwinharrell @Patrick1904 Hi again, can you export images (logo, background, icon images) to here?

**Comment by Patrick1904** [comment]
[assets.zip](https://github.com/near/near-wallet/files/5042870/assets.zip)

@picturepan2 please see attached assets
