### ISSUE TITLE
Extract reusable components to avoid copy-pasting styles, etc

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#57]
**Buttons - contain all buttons with various types:**

- [x] Create Account - form button

- [x] Recover Account - form button

- [x] Recover Account - skip this step

- [x] Set Recovery Info - form button

- [x] Authorized Apps empty list

- [x] Dashboard - Send Money

- [x] Dashboard - View All

- [x] Login - Allow

- [x] Login - Deny

- [x] Send Money - Cancel Transfer

- [x] Send Money - form button

- [x] Send Money - Confirm & Send

- [x] Send Money - Go back

- [ ] Main Menu - Create Account on mobile and desktop

**Page Container - contain the top and bottom part of the page container:**

- [x] Authorized Apps

- [x] Contacts

- [x] Dashboard

- [x] Profile

- [x] Send Money

**AccountId Input - form input for accountId, with account availability check and validation:**

- [x] Create Account

- [x] Recover Account

- [x] Send Money

**Amount Input - form input for a token amount, with amount validation:**

- [x] Send Money

**Account Form Container - contain the top and bottom part of the account form container:**

- [x] Create Account

- [x] Recover Account

- [x] Set Recovery 

**Account Form Section - contain left and right section of form container:**

- [x] Create Account

- [x] Recover Account

- [x] Set Recovery 

**Pagination Sub Box - contain a box that appears on list element click:**

- [x] Contacts

- [x] Authorized Apps

**Account Image - round image in various sizes and default icon:**

- [x] Dashboard

- [x] Authorized Apps - list

- [x] Authorized Apps - sub box

- [x] Contacts list

- [x] Contacts sub box

- [x] Send Money

- [x] Login

- [x] Profile

- [x] Main menu

**Comment by marcinbodnar** [comment]
Closing, this was handled a long time ago.
