### ISSUE TITLE
Testnet recovery email gives link to wallet.nearprotocol.com

### ISSUE THREAD

**Issue by mikedotexe** [near/near-wallet#571]
**Problem**
When a user follows the link to recover an account, they need to arrive at the proper environment.
wallet.testnet.near.org, for instance. Currently after creating an account on testnet, I get a recovery link to wallet.nearprotocol.com.

**Steps to reproduce**

1. Create account on https://wallet.testnet.near.org/ or https://wallet.testnet.nearprotocol.com/
2. Hover over the link in the email that's sent for the recovery option

**Comment by vgrichina** [comment]
This is fixed, all recovery links go to wallet.testnet.near.org
