### ISSUE TITLE
Betanet and devnet wallets display "Testnet" in the <title>

### ISSUE THREAD

**Issue by frol** [near/near-wallet#575]
**Expected Behavior**

`<title>` tag should state relevant "betanet" / "devnet" / "testnet" chain name.

**Steps to reproduce**

1. Open any non-testnet Wallet page: https://wallet.devnet.nearprotocol.com/
2. Notice that the tab is named "NEAR TestNet Wallet"

**Comment by vgrichina** [comment]
@frol this is fixed, it says stuff like "Test-only Wallet  (rpc.devnet.near.org)"
