### ISSUE TITLE
Consolidate request status / error handling

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#58]
We still have some components using `errorMessage` / `successMessage` flags to manage errors.

I suggest we move to more flexible architecture: https://github.com/nearprotocol/near-wallet/wiki/High-level-app-architecture#async-request-dataflow-overview
This would allow handling different error reasons, etc. It also allows automatically handling errors for promises dispatched in Redux.

**Comment by jimmy3dita** [comment]
fixed by https://github.com/near/near-wallet/issues/58
