### ISSUE TITLE
Login with Ledger

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#589]
### Stories

As a user with a Ledger-only account, I want to login with my Ledger and view my account, so I can view my balances, history, and manage my account.

As a user with a Ledger-only account, I want to connect my Ledger to sign transactions, so I can use Wallet features and easily interact with apps.

As a user with multiple accounts using the same Ledger, I want to load all of my accounts when I login with Ledger, so I can choose to use any of them.

### Acceptance Criteria

- [ ] User can "Login with Ledger"
  - [ ] All accounts with the Ledger public key are recovered (whether one or multiple)
- [ ] User can view account without Ledger connected after login
- [ ] Mobile ok
- [ ] Tested

### Login Flow
1. User selects "Login with Ledger" on /create
2. Prompted to "Connect your Ledger and open the NEAR app"
  a. If successful, user is redirected to Dashboard (/)
  b. If unsuccessful, user sees "Connection failed. Please reconnect your Ledger and try again"

### Design
https://www.figma.com/file/BhrKSEYsyegyZ0jKsFJ3QR/NEAR-Wallet?node-id=439%3A4892

### Loading accounts
Use this Explorer API call to lookup all accounts by public key: https://gist.github.com/kcole16/c3b088e85d42c0aa6e7612aa66d17f5b

**Comment by kcole16** [comment]
@corwinharrell @Patrick1904 Thoughts on using a modal for the "Sign with Ledger" communication, rather than redirecting them to a page for the signing flow?

**Comment by Patrick1904** [comment]
> @corwinharrell @Patrick1904 Thoughts on using a modal for the "Sign with Ledger" communication, rather than redirecting them to a page for the signing flow?

Could do a modal for quick implementation but an inline Ledger element confirming that the user is in a 'Ledger-only mode' and saying 'Have your Ledger ready to sign' would be slightly better UX IMO. More consistent signing UX = better.

**Comment by corwinharrell** [comment]
- [ ] Design Complete: https://www.figma.com/file/BhrKSEYsyegyZ0jKsFJ3QR/NEAR-Wallet?node-id=439%3A4892
