### ISSUE TITLE
Banner on betanet shows nearprotocol.com

### ISSUE THREAD

**Issue by mikedotexe** [near/near-wallet#592]
**Problem**
Banner shows the old URL on betanet:
<img width="664" alt="Screenshot 2020-05-19 17 18 50" src="https://user-images.githubusercontent.com/1042667/82391307-d9e62f80-99f5-11ea-96e5-e64fb772b713.png">

**Expected Behavior**
All links go to near.org

**Steps to reproduce**

1. Head to https://wallet.betanet.near.org/create/
2. See banner

I know `near-shell` has changed the RPC URLs so I believe this is a mistake.

**Comment by vgrichina** [comment]
remove `good first issue` as this is config issue, has to be fixed internally

**Comment by kcole16** [comment]
Fixed
