### ISSUE TITLE
Account Recover: Link Expired

### ISSUE THREAD

**Issue by only25x** [near/near-wallet#593]
**Problem**
On betanet, I am following the recovery link in email and getting the following message from 
https://wallet.betanet.near.org/

"Link Expired
Please check your email or phone for the most recent message. Links in all earlier messages are invalid."

I also tried to follow https://wallet.betanet.near.org/recover-seed-phrase
using the account name and seed phrases separated by spaces, and got the same message.

**Steps to reproduce**
I have used the same recovery link in the past to login and it has always worked. Not sure what happened now or how to reproduce it. But wanted to report it in case other people are seeing it too.

**Comment by only25x** [comment]
Turns out the domain changed from near.org to nearprotocol.com. That seemed to fix it for me.

**Comment by mattlockyer** [comment]
Yes we have migrated domains. Not a common occurrence. The links however have expired.
