### ISSUE TITLE
RPCs block wallet UI from loading

### ISSUE THREAD

**Issue by marcinbodnar** [near/near-wallet#597]
**Problem**
Wallet is waiting for RPCs to load UI. If there is a delay from RPCs user is not able to see UI.

**Expected Behavior**
If there is a delay from PCs, user should be able to see Wallet UI with some main loader.
Nice to have would be if Wallet would detect if there is RPC delay and display proper information to the user.

**Comment by marcinbodnar** [comment]
@corwinharrell 
Could you please propose the loader or some alternative solution. 

The thing is that if this situation happens, we will not be able to show any data (user account will not be loaded yet), so ideally if user will be able to see that Wallet is loaded, but also some indicator/information that something is happening in background and user needs to wait.

Maybe we should show an empty top bar (without options), footer, and some information in the middle?

**Comment by corwinharrell** [comment]
Sounds good @marcinbodnar have added this to my list 👍

**Comment by jimmy3dita** [comment]
Being fixed by #1665
