### ISSUE TITLE
Can't create one letter prefix account

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-wallet#612]
**Problem**
The wallet UI fails to create 1 letter prefix on betanet. E.g. `f.betanet`. It's a valid account ID name. 

**Expected Behavior**
You should be able to create `f.betanet`

Correct Regex is `/^(([a-z\d]+[-_])*[a-z\d]+\.)*([a-z\d]+[-_])*[a-z\d]+$/`

**Steps to reproduce**

1. Go to https://wallet.betanet.near.org/create/ 
2. Try to create `f.betanet`

**Comment by kcole16** [comment]
This is intended behavior. I thought names needed to be 2-64 characters?

**Comment by evgenykuzyakov** [comment]
But the name `f.betanet` is longer than 2 characters, so it's legit. While simple `f` will not be a legal account ID
