### ISSUE TITLE
Handle TX timeout errors

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#623]
### Overview

Users occasionally encounter RPC `Timeout` errors when sending a TX, and currently we treat this as a failure. Oftentimes, these TXs actually succeed, which can cause the user to unintentionally send a duplicate TX. 

We should handle this situation similarly to in #443, where we attempt to retrieve the TX status until it is final (success or failure) using `EXPERIMENTAL_check_tx`

### Acceptance Criteria

- [ ] When encountering a `Timeout`, the TX status is polled until a final status is received
   - [ ] Send NEAR (/send)
   - [ ] Sign TX (/sign)
   - [ ] Login/create access key (/login)
   - [ ] Remove access key (/authorized-apps)
   - [ ] Add recovery option (/profile)
   - [ ] Remove recovery option (/profile)
- [ ] Tested

**Comment by bowenwang1996** [comment]
@kcole16 you can check whether a transaction is still valid through the `EXPERIMENTAL_check_tx` rpc before pulling its status.

**Comment by jimmy3dita** [comment]
@vgrichina and @MaximusHaximus to test if this is still present, and close or spawn a new issue to address this one
