### ISSUE TITLE
Sign TX with 2FA

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#631]
### Overview
TXs require 2-of-3 multi-sig

1 key in localStorage
1 key in recovery
1 key on our server

### Stories
As a user with a 2FA configured account, I want to view and confirm TXs on my mobile device, so I can safely transact without fully trusting the wallet client.

### Acceptance Criteria
- [ ] After initiating any TX, user receives a message with TX details and unique code
  - [ ] Recipient account name
  - [ ] Action (functionCall, transfer, etc)
  - [ ] functionCall name (if applicable)
  - [ ] NEAR deposit amount (if applicable)
- [ ] User must enter unique code from message to finish the transaction
- [ ] User receives instructions for completing the 2FA 
- [ ] Mobile ok
- [ ] Tested

### Flow
1. User initiates a TX, signs with key in localStorage
2. Server sends an SMS to the user with TX details, code to enter
3. User enters the code into the UI
4. Server signs and sends TX

### UI Design
https://www.figma.com/file/n4hWCPeRFAznf5ioxUPcZZ/631-Sign-Transaction-w-2FA?node-id=1%3A13

**Comment by mattlockyer** [comment]
@Patrick1904 @vgrichina here is an example that works for a testnet account if you deploy the multisig contract to that account and add some limited access keys.

VERY early precursor and I don't expect you to run it, just have a look at the code and what's involved with this flow from a functional perspective. Everything is in `utils/wallet.js` here: https://github.com/near/near-wallet/blob/819786c6bdf41d4c53a9cd8c37268552b370db9d/src/utils/wallet.js#L127

You are able to:
1. add_request (key 1 client)
2. confirm (key 1 client)
3. confirm (key 2 backend, currently simulated on the client)

Excuse my language in the comment, but the timeouts are not fun when you're trying to chain 3 txs on the client side...

**Comment by corwinharrell** [comment]
New [2FA modal UI](https://www.figma.com/file/n4hWCPeRFAznf5ioxUPcZZ/631-Sign-Transaction-w-2FA?node-id=1%3A13) for signing transactions with 2FA:

<img width="999" alt="Screen Shot 2020-06-29 at 1 41 44 AM" src="https://user-images.githubusercontent.com/5934188/85976983-b5dd1d00-b9a9-11ea-8b68-61626d45ff4f.png">
