### ISSUE TITLE
Auto-scroll pages to top on load

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#633]
### Overview
On mobile, it is easy to get into a state where pages are loaded in the middle of the page, forcing the user to scroll up to understand what is happening.

Ideally, the user should be reset to the top of each page (with the exception of using the back button).

### Acceptance Criteria
- [ ] All pages scroll to the top on page load

**Comment by corwinharrell** [comment]
@kcole16 Can you attach some example urls so we can reproduce?

**Comment by kcole16** [comment]
Happens on all pages on mobile.

Try opening `/profile`, scrolling to the recovery options, then selecting "Seed Phrase".

**Comment by Patrick1904** [comment]
Discussed this with @vgrichina last week. Makes sense to me.

**Comment by corwinharrell** [comment]
@kcole16 @Patrick1904 oh yeah for sure. Should scroll-to-top on page load. That's funny behavior it's exhibiting right now. How did this happen in the first place? Just curious.

**Comment by Patrick1904** [comment]
@corwinharrell scroll-to-top is not default in react router but there are [configuration options](https://reacttraining.com/react-router/web/guides/scroll-restoration) that we'll use

**Comment by corwinharrell** [comment]
@Patrick1904 gotcha I didn't realize that react-router behaved that way 👍

**Comment by Patrick1904** [comment]
Fixed here https://github.com/near/near-wallet/pull/647
