### ISSUE TITLE
"Connect Ledger" button fails silently and produces JS console error

### ISSUE THREAD

**Issue by eriktrautman** [near/near-wallet#637]
**Problem**
Clicking "Connect Ledger" fails silently for both old and new wallet accounts.

*NOTE*: This is a wallet.nearprotocol.com problem so it's possible the real solution should be "don't let people use this site"
**UPDATE:** It occurs regardless of whether it's the nearprotocol or wallet.testnet.near.org/full-access-keys site.

**Expected Behavior**
Either an actual human-readable UI error or a happy path to connect the ledger device.

**Steps to reproduce**

1. wallet.nearprototocl.com > create new account or still fails with an existing account
2. Go to /full-access-keys
3. Click "Connect Ledger".  Wait 30 seconds or so for something to happen until Console produces the error message: 
![image](https://user-images.githubusercontent.com/2977438/83685334-5d2e8600-a59d-11ea-9d00-f36cc98657f6.png)

**Comment by kcole16** [comment]
Ledger support isn't finished yet (targeting end of this week), and unfortunately we had to expose it in the unfinished state for the Ledger app store review. cc @vgrichina

**Comment by kcole16** [comment]
Fixed by new Ledger flow
