### ISSUE TITLE
Remove "Full Access Keys" from dashboard

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#638]
### Overview
This page is pretty dangerous for end users (sometimes even devs). We should remove the section from the dashboard, and consider killing the route entirely for now.

https://wallet.testnet.near.org/full-access-keys

cc @vgrichina

**Comment by Patrick1904** [comment]
@vgrichina are you ok with this?

@kcole16 are we removing the 'Full Access Keys' link from the nav too? Seems to make sense. Should the route still stay active?

**Comment by vgrichina** [comment]
I think we should do https://app.zenhub.com/workspaces/app-layer-5e2b7ac4f336abcdc02917e8/issues/near/near-wallet/640 instead

**Comment by kcole16** [comment]
This page is really only useful for devs, and dangerous for end users. At the very least, we should hide it from most users, behind an advanced tab or something similar, and heavily warn against deleting the localstorage key. 

Additionally, it is a bit of an increase in v0 release scope. If we think it is worth doing with that considered, then I’m open to it.

**Comment by vgrichina** [comment]
@kcole16 these aren't really increasing scope much as we already have all necessary data in wallet and don't need any new UI, just some adjustments in how data is filtered / safety checks on removal:

- [ ] Filter out keys which are represented in other UI (recovery methods, Ledger)
- [ ] Make it clear which key is this wallet's local storage (if any), so you don't delete it accidentally.

> At the very least, we should hide it from most users, behind an advanced tab or something similar

I agree 100% we should remove these from home page.

**Comment by kcole16** [comment]
Fair point. 

@corwinharrell @Patrick1904 Thoughts on moving the link to `/full-access-keys` to an "Advanced" section on the Profile?

**Comment by Patrick1904** [comment]
Sounds good to me. @corwinharrell let me know if you have a design in mind seems it could be a pretty simple ui?

> Filter out keys which are represented in other UI (recovery methods, Ledger)

@vgrichina what do you think about still showing all keys but label accordingly? That way you feel more in control over access keys. If it's an advanced feature

**Comment by vgrichina** [comment]
Seems like "Full Access Keys" still there, so re-opening. 

> what do you think about still showing all keys but label accordingly? That way you feel more in control over access keys.

I think we should split keys as following:

- Apps (app access keys, should also start showing metadata on when / where it was added / last used).
- Devices (keys which have metadata on which computer / phone / hardware wallet they are added)
- Recovery (keys with recovery methods, implemented now basically)
- Other (all keys which don't fit into these categories, with low-level info). Normal users shouldn't deal with them. Generally we should suggest users to remove these unless they know what they are doing.

**Comment by kcole16** [comment]
@vgrichina They were removed from the dashboard on mainnet only. Still appear to be removed to me?

We have this issue for improving the FAK page: https://github.com/near/near-wallet/issues/640
