### ISSUE TITLE
Privacy Policy and Terms of Service links don't work

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#639]
**Problem**

Privacy Policy and Terms of Service links don't work (user just redirected to home page).

**Expected Behavior**

Privacy Policy and Terms of Service links open pages with relevant info which matches our actual policy and explains in plain language privacy implications (like all transactions being available publicly on chain).

**Steps to reproduce**

1. Go to https://wallet.testnet.near.org
2. Try pressing Privacy Policy or Terms of Service links

**Comment by vgrichina** [comment]
@kcole16 looks like we need this for mainnet launch as well

**Comment by vgrichina** [comment]
@kcole16 do we have text for privacy policy / terms of service?

**Comment by kcole16** [comment]
We can link to the near.org privacy policy: https://www.iubenda.com/privacy-policy/44958041?ifr=true&height=775&newmarkup=no

And working with Julie to get a Wallet-specific ToS

**Comment by vgrichina** [comment]
We need to make sure update e-mail templates as well https://github.com/near/near-contract-helper/pull/210/files

Also note that near.org Privacy Policy doesn't cover most important issue – that everything you do on NEAR blockchain is completely public info to anyone (like Twitter).

**Comment by Patrick1904** [comment]
ToS shipped in https://github.com/near/near-wallet/pull/1649
