### ISSUE TITLE
Recovery Methods Don't Work

### ISSUE THREAD

**Issue by armyids** [near/near-wallet#644]
After login to my betanet account, I tried to add recovery methods (from email address, phone number, until seed phrase). All of them didn't work. 

![1](https://user-images.githubusercontent.com/27644083/82579302-cbe00c80-9bb7-11ea-9927-73fe35793f34.png)

Sending but after I check to inbox mail, there is nothing:

![2](https://user-images.githubusercontent.com/27644083/82579431-ffbb3200-9bb7-11ea-9f62-1c8b541cb9a0.png)
PS: I used disposal email just for checking.

And the second one was using phone recovery, it also didn't work. Even I tried with various number.

Last one, tried using 12 words of phrase:

![3](https://user-images.githubusercontent.com/27644083/82579754-71937b80-9bb8-11ea-86eb-cfcfb83432e0.png)

![4](https://user-images.githubusercontent.com/27644083/82579766-78ba8980-9bb8-11ea-9c87-b526a580a3bc.png)

**Comment by kcole16** [comment]
Closing until we can reproduce
