### ISSUE TITLE
Account with Ledger can not remove other keys

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#651]
**Problem**
Deleting key from an account in the Wallet that was previously authorized with Ledger key doesn't show any error and doesn't delete key.

**Expected Behavior**
Key gets deleted

**Steps to reproduce**

1. Account: marbletest.testnet
2. Open full access keys
3. Select non ledger key and try to deactivate it
4. Observe error in console without anything showing in the UI:
```Error in background action: Error: Can not sign transaction for account, no matching key pair found.```

**Comment by kcole16** [comment]
This will be addressed in this PR: https://github.com/near/near-wallet/pull/645. We'll either be removing the Full Access Keys page entirely or restructuring it: #640.

**Comment by Patrick1904** [comment]
This `signatureFor` issue is being fixed here https://github.com/near/near-wallet/pull/594/commits/b0ed701ba0853d084b1bc436b09f91c92ecb5fc2

**Comment by vgrichina** [comment]
I believe underlying issue is fixed with https://github.com/near/near-ledger-app/commit/bcce2a67ca5c0d3e8bc8afa9cf53910f5ac80e12
