### ISSUE TITLE
Unable to recover wallet on mobile browser

### ISSUE THREAD

**Issue by frol** [near/near-wallet#652]
@htafolla commented on [Mon Jun 08 2020](https://github.com/near/near-explorer/issues/325)

When recovery your wallet on a mobile browser it gives the error: Please match the requested format

The error refers to the seed phrase. I have made sure that there were no spaces before or after the phrase and I have tried Brave, Chrome and Kiwi.

**Comment by kcole16** [comment]
Fixed
