### ISSUE TITLE
Unable to recover wallet on mobile browser

### ISSUE THREAD

**Issue by htafolla** [near/near-wallet#653]
When recovery your wallet on a mobile browser it gives the error: Please match the requested format

The error refers to the seed phrase. I have made sure that there were no spaces before or after the phrase and I have tried Brave, Chrome and Kiwi.

**Comment by kcole16** [comment]
We've had this happen to several users (including myself and Patrick), though we've had trouble reproducing it. I was able to reliably fix this when it occurred for me by removing the HTML regex check.  

I think this is worth doing for now, as this is a critical issue (or at least will feel that way for anyone encountering it). Thoughts? @vgrichina @marcinbodnar @Patrick1904

**Comment by Patrick1904** [comment]
I have not been able to figure out why this happens. Agree that removing regex is best for now since it's a critical issue. I've submitted a PR [here (654)](https://github.com/near/near-wallet/pull/654)

**Comment by kcole16** [comment]
Hi @htafolla, can you please retry seed phrase recovery? We pushed a potential fix.

**Comment by htafolla** [comment]
I needed to clear my cache, but it worked!
