### ISSUE TITLE
Hide/disable "Send" in Mainnet Wallet

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#655]
### Overview
Users will be unable to transfer tokens in the Mainnet wallet until Phase 2. To avoid confusion, we should disable the `/send-money` and `/receive-money` and remove those options from the navbar.

### Acceptance Criteria
- [ ] Navigating to `/send-money` and `/receive-money` redirect users to the dashboard
- [ ] The navbar only includes "Summary"
- [ ] The `/send-money` and `/receive-money` routes and navbar options are still available on Testnet, Betanet, and Devnet

**Comment by Patrick1904** [comment]
@kcole16 @vgrichina can I implement this? Thought there were concerns since we're going to do some internal mainnet testing?

**Comment by kcole16** [comment]
I don’t think we’re planning to have anyone sending NEAR, but worth waiting for @ilblackdragon to confirm
