### ISSUE TITLE
It's hard to understand what is going on when you mistype e-mail

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#667]
**Problem**

When you mistype e-mail when setting up recovery it's hard to understand what is going on. E.g. if you type comma instead of dot – the form won't let you proceed without any error message, but also it's hard to see what's wrong.

**Expected Behavior**

We display friendly message to user explaining what's wrong.

**Steps to reproduce**

1. Try setting up e-mail as recovery method.
2. Type comma instead of dot
3. Try to proceed

**Comment by Patrick1904** [comment]
Closing as issue is outdated
