### ISSUE TITLE
Include owned Lockup accounts in balance breakdown

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#670]
### Overview

All NEAR Wallet users will have tokens in a lockup contract prior to Phase 2. We should include these tokens in Total Balance, and display the lockup amount as a line item on `/profile`.

The [lockup contract](https://github.com/near/core-contracts/tree/master/lockup) will deployed with a predictable account name (e.g. `users_account_name.lockup.near`), and we can query that account to get the balance.

### Acceptance Criteria

If a user's account owns a lockup account/contract
- [ ] Lockup account's total balance is included in Total Balance
- [ ] Lockup account's total balance is displayed on `/profile` as "Lockup Balance"
- [ ] Lockup account's delegated balance is displayed on `/profile` as "Delegated Balance"
- [ ] Mobile ok
- [ ] Tested

**Comment by vgrichina** [comment]
> e.g. `users_account_name.lockup`

it's going to be `lockup.users_account_name` given how our subaccounts work

**Comment by kcole16** [comment]
> it's going to be lockup.users_account_name given how our subaccounts work

Right, I was operating under the assumption we would deploy the contracts manually, as opposed to during the linkdrop and account creation process (which allows for subaccounts)

**Comment by vgrichina** [comment]
@kcole16 prototyped a little bit here:
https://github.com/near/near-wallet/pull/735 (tested only on betanet with hardcoded account name, will fix once testnet is ok)

However looks like we have far more balances to deal with:

```rs
/// The amount of tokens that were deposited to the staking pool.
/// NOTE: The actual balance can be larger than this known deposit balance due to staking
/// rewards acquired on the staking pool.
/// To refresh the amount the owner can call `refresh_staking_pool_balance`.
pub fn get_known_deposited_balance(&self) -> WrappedBalance;

/// The amount of tokens that are not going to be vested, because the vesting schedule was
/// terminated earlier.
pub fn get_terminated_unvested_balance(&self) -> WrappedBalance;

/// The amount of tokens missing from the account balance that are required to cover
/// the unvested balance from the early-terminated vesting schedule.
pub fn get_terminated_unvested_balance_deficit(&self) -> WrappedBalance;

/// Get the amount of tokens that are locked in this account due to lockup or vesting.
pub fn get_locked_amount(&self) -> WrappedBalance;

/// Get the amount of tokens that are already vested, but still locked due to lockup.
pub fn get_locked_vested_amount(&self) -> WrappedBalance;

/// Get the amount of tokens that are locked in this account due to vesting.
pub fn get_unvested_amount(&self) -> WrappedBalance;

/// The balance of the account owner. It includes vested and extra tokens that may have been
/// deposited to this account.
/// NOTE: Some of this tokens may be deposited to the staking pool.
/// This method also doesn't account for tokens locked for the contract storage.
pub fn get_owners_balance(&self) -> WrappedBalance;

/// The amount of tokens the owner can transfer now from the account.
pub fn get_liquid_owners_balance(&self) -> WrappedBalance;
```

Wonder which ones you think we should include in breakdown + what do we include in total balance? Like e.g. should unvested tokens be part of total balance?

**Comment by vgrichina** [comment]
@evgenykuzyakov is there any reason why every balance is returned as a separate view call? Seems like there is more sense to return contact status with single JSON object with all fields (saves significantly on number of RPC requests and so latency).

**Comment by evgenykuzyakov** [comment]
View calls are free right now, so it doesn't matter the way contract is written. From node perspective it's probably cheaper to do one more expensive call than multiple cheap ones, but if RPCs are parallelized towards different nodes, then you get the answer faster with parallel RPCs.

Still it's better to aggregate it into a single view call to avoid race conditions, but it will increase the size of the contract to have a separate serializable JSON structure for the output.

**Comment by vgrichina** [comment]
> View calls are free

Network queries aren't free though. I guess if RPC can handle multiple requests in parallel then it's not a big issue as long as  endpoint supports HTTP2.

**Comment by vgrichina** [comment]
> Wonder which ones you think we should include in breakdown + what do we include in total balance? Like e.g. should unvested tokens be part of total balance?

from Kendall:

> Locked = total lockup balance - unvested balance - liquid owners balance
> Unvested = unvested balance
> Unlocked (can be withdrawn) = liquid owners balance

**Comment by vgrichina** [comment]
@evgenykuzyakov a second thought on this is – we don't really need actual JSON serde to implement this. Like you can just format a string substituting values into corresponding places.

**Comment by evgenykuzyakov** [comment]
@vgrichina Right. But it's a hack, and the increased size is not a big concern.
