### ISSUE TITLE
"Sending..." button gets stuck on error when disabling recovery method

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#672]
**Problem**

"Sending..." gets stuck on error when disabling recovery method

**Expected Behavior**

"Sending..."  returns to normal state and some info about error is displayed.

**Steps to reproduce**

1. Go to Profile
2. Try disabling one of the recovery methods.
3. Try to confirm disabling it (assuming wallet.js throws error like e.g. backend timeout)

**Comment by Patrick1904** [comment]
Will be fixed [here](https://github.com/near/near-wallet/pull/645/commits/dc1c59e3e91cc11b3917b38c79981586ecd2ce4c)

**Comment by vgrichina** [comment]
@Patrick1904 I've cherry-picked here https://github.com/near/near-wallet/commit/4aa59804965242fc89b54ee3e6b2ef7dcaecafe7

Not sure why you did include it into Ledger PR? Seems pretty independent and already could be released. It helps to keep PRs smaller to make review/merging easier. Ledger PR probably going to stay open for a while before integration works well.

**Comment by Patrick1904** [comment]
> @Patrick1904 I've cherry-picked here [4aa5980](https://github.com/near/near-wallet/commit/4aa59804965242fc89b54ee3e6b2ef7dcaecafe7)
> 
> Not sure why include this fix into Ledger PR? Seems pretty independent and already could be released.
> 
> It helps to keep PRs smaller to make review/merging easier. Ledger PR probably going to stay open for a while before integration works well.

@vgrichina that's true, my bad. I handled this yesterday while '[making recovery methods appear in fixed order](https://github.com/near/near-wallet/pull/681)'. Will have the PR ready for review today by EOD.

**Comment by Patrick1904** [comment]
Fixed in https://github.com/near/near-wallet/pull/681. Closing.
