### ISSUE TITLE
Filter out LAK that reference the user's account in Authorized Apps

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#679]
### Overview
Most users will be using limited access keys scoped to the multi-sig contract deployed on their own account, and these keys are currently showing up in "Authorized Apps". This is quite confusing to the user, as it show's their own account as an "Authorized App". 

We should filter these out (e.g. `user.testnet` should not show up in "Authorized Apps" if the selected account is also `user.testnet`

### Acceptance Criteria
- [ ] `/authorized-apps` does not show any keys that are scoped to the user's own account 
- [ ]  The dashboard does not show these keys

**Comment by kcole16** [comment]
@marcinbodnar I thought this was completed (my fault), but seems to still be happening?

Can we prioritize this for this week?

**Comment by marcinbodnar** [comment]
@kcole16 sure thing
