### ISSUE TITLE
Clear Context on NEAR wallet

### ISSUE THREAD

**Issue by crasskitty** [near/near-wallet#680]
As a developer using the NEAR create-near-app,
I want clear context and information for what I am doing in the wallet: 	

- Explain what the wallet is
- Explain what testnet is	
~~- Explain why it needs access to the React App Template~~ (Striked through after discussing with Kendall and realizing the privacy/security concerns of this feature. Moving this acceptance criteria - moved to https://github.com/near/devx/issues/215)
- Explain what Mainnet is

So that I know what I am doing.

**Comment by vgrichina** [comment]
Note that the wallet flow you end up with in create-near-app is what app users would see as well, not just developers.

**Comment by kcole16** [comment]
> Explain what the wallet is

Agree this is needed on wallet itself.

> Explain what testnet is
> Explain what Mainnet is

These should be explained in a developer context, which is difficult to do in the Wallet (as it's targeted at end users as opposed to solely devs). 

I expect most users will only ever encounter Mainnet, so I believe the concept is less important to explicitly explain. We've instead chosen to very explicitly call out Testnet as "not real", and make it clear to the user they are on the "valueless" network.
 
> Explain why it needs access to the React App Template

This is also very context specific, and should generally be explained by the app requesting permission, as we can only infer very explicit details about what happening (e.g. account name, action types, name of functions, etc).

**Comment by ashleynear** [comment]
These should be explained in a developer context, which is difficult to do in the Wallet (as it's targeted at end users as opposed to solely devs).

I expect most users will only ever encounter Mainnet, so I believe the concept is less important to explicitly explain. We've instead chosen to very explicitly call out Testnet as "not real", and make it clear to the user they are on the "valueless" network.

> > Explain what the wallet is
> 
> Agree this is needed on wallet itself.
> 
> > Explain what testnet is
> > Explain what Mainnet is
> 
> These should be explained in a developer context, which is difficult to do in the Wallet (as it's targeted at end users as opposed to solely devs).
>
> I expect most users will only ever encounter Mainnet, so I believe the concept is less important to explicitly explain. We've instead chosen to very explicitly call out Testnet as "not real", and make it clear to the user they are on the "valueless" network.

For this, since most users will ever see the mainnet version, is it possible to explain these concepts on JUST the testnet version of the wallet?
> 
> > Explain why it needs access to the React App Template
>
> This is also very context specific, and should generally be explained by the app requesting permission, as we can only infer very explicit details about what happening (e.g. account name, action types, name of functions, etc).

For this, could we add the context to the App Requesting?

**Comment by jimmy3dita** [comment]
Closed by https://github.com/near/devx/issues/215
