### ISSUE TITLE
Support recovery of multiple accounts with the same seed phrase

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#683]
**Problem**

Multiple accounts can reuse same public key (and so seed phrase). Currently only one of the will be recovered.

**Expected Behavior**

All of the accounts are recovered, but only last one selected.

**Steps to reproduce**

1. Setup account with seed phrase recovery.
2. Add same full access key as used for seed phrase to another account (can be done using `near repl`).
3. Try recovering account using seed phrase.

**Comment by vgrichina** [comment]
Note that this is not completely theoretical problem, as I think it may happen if somebody used Ledger before for multiple accounts and then wants to recover with the same seed phrase.

**Comment by marcinbodnar** [comment]
@vgrichina OK, got it.

**Comment by kcole16** [comment]
@vgrichina Completely re: Ledger and the need to support that, cc @Patrick1904, but that shouldn't affect seed phrase recovery?
