### ISSUE TITLE
Detecting and switching languages

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#704]
### Overview
We have translations ready for the wallet in Mandarin (and several other languages), and should make it easy for users to switch from English to these languages.

The language switcher is the most important addition, and detecting the browser default language is useful as well (though not likely to cover most cases).

### Stories

As a user, I want to view the Wallet in my browser-defaulted language, so I do not have to manually switch the language.

As a user, I want to manually switch the Wallet language to another supported language, so I can use products in multiple languages.

### Acceptance Criteria

- [x] Users can view and select from all supported languages in the
  - [x] Navbar (Desktop)
  - [x] Menu (Mobile)
- [x] Users can select a supported language, and the Wallet will reload with all copy in that language
- [ ] If Wallet supports a user's browser-defaulted language, this should be the initially selected and loaded language
- [ ] Mobile ok
- [ ] Tested

### Designs
cc @corwinharrell 
<img width="1253" alt="85975288-a9ef5c00-b9a5-11ea-8d70-2364d258827b" src="https://user-images.githubusercontent.com/5624527/86050396-a640f100-ba08-11ea-9adb-705e5284e142.png">

**Comment by vgrichina** [comment]
Merged https://github.com/near/near-wallet/pull/582 /cc @Patrick1904 

Now we just need to adjust UI a little to match what designed by @corwinharrell. 
Note that I noticed also that when I select language other than English on mobile – viewport size seems to increase to be a bit wider than screen. This also needs to be adjusted (might be fixed as side effect of applying design though).

**Comment by vgrichina** [comment]
Looks like also language change doesn't persist for now

**Comment by picturepan2** [comment]
@vgrichina I have done the feature of saving languageCode to localStorage and persist language choice in local. Creating a PR soon.

**Comment by Patrick1904** [comment]
@picturepan2 would also be great if we can add English as fallback in case of missing translation: [`onMissingTranslation`](https://ryandrewjohnson.github.io/react-localize-redux-docs/#handle-missing-translations). Currently the Ledger module on `/profile` is showing the default `Missing translationId` since it's not translated yet. I tested `onMissingTranslation` locally and it works fine.

**Comment by picturepan2** [comment]
One problem I have is importing needed translations dynamically when switching. It flashes long translation strings sometimes which is not good for UX.

**Comment by Patrick1904** [comment]
> One problem I have is importing needed translations dynamically when switching. It flashes long translation strings sometimes which is not good for UX.

Can we wait until it has finished loading before switching the language on the UI? If so, we could add some loading indicator to avoid an in-between state. I guess the files aren't that big right now, but as the app grows and we add more languages, dynamic loading will be a must-have.

**Comment by picturepan2** [comment]
@Patrick1904 Here is my plan and I will do it in order. What do you think?

- [ ] 1) UI first with accessibility.
- [ ] 2) Load translation files dynamically.
- [ ] 3) Auto detect user's browser language.

**Comment by Patrick1904** [comment]
> @Patrick1904 Here is my plan and I will do it in order. What do you think?
> 
> 
> 
> - [ ] 1) UI first with accessibility.
> 
> - [ ] 2) Load translation files dynamically.
> 
> - [ ] 3) Auto detect user's browser language.

Looks great @picturepan2

**Comment by picturepan2** [comment]
@Patrick1904 Parcel doesn't support [Dynamic Imports with variables](https://github.com/parcel-bundler/parcel/issues/4413) which should be supported to enable loading translation files dynamically. One solution is switching to Webpack.

**Comment by picturepan2** [comment]
@Patrick1904 I created a PR #724 for some new features and design. Please review. (It seems I have no permission to assign it to you.)

**Comment by Patrick1904** [comment]
> @Patrick1904 Parcel doesn't support [Dynamic Imports with variables](https://github.com/parcel-bundler/parcel/issues/4413) which should be supported to enable loading translation files dynamically. One solution is switching to Webpack.

@vgrichina do you have any thoughts on this?

**Comment by picturepan2** [comment]
@vgrichina BTW, I can't assign reviewer or anyone in the PR in this repo. Could you take some time to see if there is any setting or role for me to easier contribute to NEAR products? Thank you.

**Comment by think-in-universe** [comment]
Hey guys @picturepan2 @Patrick1904, are we able to automatically detect the browser language now? 

It seems still not working when I tested today.

**Comment by Patrick1904** [comment]
> Hey guys @picturepan2 @Patrick1904, are we able to automatically detect the browser language now?
> 
> It seems still not working when I tested today.

@think-in-universe we haven't added support for this yet. @picturepan2 do you have any bandwidth to add support for auto switching?

**Comment by think-in-universe** [comment]
@Patrick1904 @picturepan2 I implemented one way to detect the browser language in https://github.com/near/near-wallet/pull/1884  please have a look when you get time
