### ISSUE TITLE
Unable to login via near shell + /create is wiping out account information from local storage

### ISSUE THREAD

**Issue by AnaisUrlichs** [near/near-wallet#720]
**Problem**
When I run `near login` in the terminal it redirects me to the Browser, I provide all the information to grant full access to near shell. However, once I hit confirm it either throws an error in the browser or it redirects me back to the terminal but then throws an error.

The error in the browsers
![walleterror](https://user-images.githubusercontent.com/33576047/86822136-84d8a880-c08b-11ea-9f73-07a42a149a72.jpg)

The error in the console 
![testnet7](https://user-images.githubusercontent.com/33576047/86822184-93bf5b00-c08b-11ea-8cce-983500eb5d7d.PNG)

This error happened every time I tried to login (using Chrome and then Firefox, each on Ubuntu and Windows).

Separately, I have encountered an error that basically wipes out all the information on the wallet in local storage -- this happens upon opening `/create` near wallet in the browser. However, this error was more like a "by-chance" thing rather than an every-time default behavior.

It would then show the following error (I think that was the error in that case)
![testnet5](https://user-images.githubusercontent.com/33576047/86822417-e6007c00-c08b-11ea-9811-a65a751eb033.PNG)

In this case, we were trying to log in through `near login` in the terminal but then it would wipe out the keys that were previously used in the browser. This behaviour only happened on Windows but on two different machines.

**Expected Behavior**
Happy log-in path (like usual)

**Steps to reproduce**
Well, this is a bit complicated -- `near login` in the terminal and see what happens.

**Comment by kcole16** [comment]
@AnaisUrlichs Did we ever get a reliable reproduction of this?

**Comment by AnaisUrlichs** [comment]
@kcole16 we sadly did not and it also stopped happening -- so I guess you can close this issue. It was right at the time when we had the timeout issues :)
