### ISSUE TITLE
Make sure that Referrer only used as secondary signal for request source in /login and /sign endpoints

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#732]
**Problem**

Referrer not always reliable as suggested by @abacabadabacaba:
- Many websites allow users to post arbitrary link, and these links usually don't block the referrer. This is generally not considered a security issue, unless the page's URL is secret.
- Likewise, many websites have redirectors that can redirect to an arbitrary URL. This is also not considered to be problematic by itself, even by Google.
- Referrer may be blocked in some browsers.

**Proposed Solution**

Callback URL should be used as primary source of truth (especially after https://github.com/near/near-wallet/issues/726 lands). However if Referrer is set and isn't matching callback URL – we should report it as might be a sign of something sketchy going on.

**Comment by kcole16** [comment]
@vgrichina This is a dupe of #726. Adding your additional context to that issue.
