### ISSUE TITLE
Allow users to claim linkdrops in existing account

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#742]
### Overview
Currently, we force users to create an account to claim a linkdrop. We can also allow them to claim the linkdrop NEAR into an existing account.

### Acceptance Criteria
If the user has an existing account
- [ ] While viewing `/create` with a valid PK from a linkdrop, the user is asked "Would you like to accept the funds into your account: <account>?"
  - [ ] If yes, `/claim` is called on linkdrop, and the user is redirected to the dashboard
  - [ ] If no, the user can proceed to create a new account

**Comment by corwinharrell** [comment]
Addressed in https://github.com/near/near-wallet/issues/1467
