### ISSUE TITLE
"Log out" of the application from within the application

### ISSUE THREAD

**Issue by eriktrautman** [near/near-wallet#75]
## Story

As a user who has a NEAR wallet and has previously used it to log in to a third-party app and is now currently using that third-party app, I want to be able to de-authorize (log out from) that application so it no longer is using my information. 

See NOTES below for important discussion about specific states and intent of this.

## Acceptance Criteria TODO

- [ ] AC1
- [ ] AC2
- [ ] Mobile ok
- [ ] Tested

## Assets

- Mockup: TODO after states are specifically figured out.

### Re: Intent

The idea of this is to provide a standard interface and UI pattern for apps which are authorized by the NEAR wallet to interact with those permissions. We'll use this in our sample apps and let developers adopt that pattern too.

### Re: States 

We still do get into the question of what "log out" means because in this case, de-authorizing the app means the app can't actually access any of your account even when you disappear. So it's closer to "delete my account on this app" than "log out from this app".

It's not exactly the same as "delete my account" because the app could still keep all your information waiting for you when you re-link your account.

So for clarity it's actually important to highlight always the difference between the states and it actually brings up the idea of "application-specific logins".

1. "Log out of application" (For example, if you are lending your computer to your kid and don't want your trading app open but do want a game open): Just removes that browser's login session from the application but keeps everything else behind the scenes.

2. "de-link/de-authorize application" (you want to remove that application's access to your account on ALL browser sessions now and forever): Revokes any access the application has to your NEAR account and logs you out of your current browser session with that application.

3. "delete account on application" (You want to remove the app's access AND don't ever intend to return to it): This does same as de-link/de-authorize but also explicitly asks the application to remove your account state (otherwise they may keep your account state around and expect you to re-link it).

**Comment by Patrick1904** [comment]
Closing as issue is outdated
