### ISSUE TITLE
2FA Message Text Improvements

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#751]
### Overview
Adding extra descriptions to our 2FA messages

### Acceptance Criteria
- [ ] Users receive the base 2FA message and the appropriate action description for each 2FA method
  - [ ] Email
  - [ ] Phone
- [ ] Users receive the appropriate action description for
  - [ ] Transfer
  - [ ] FunctionCall
  - [ ] Stake
  - [ ] AddKey (forContract)
  - [ ] DeleteKey
- [ ] Users receive the appropriate message when trying to add a new full access key

**Base Message (for non FAK actions)**
```
NEAR Wallet security code: <securityCode>

Important: By entering this code, you are authorizing the following transaction:

<Action Description>
```

**Action Descriptions**

 FunctionCall: ```Calling method: ${methodName} with ${args} in contract: @${receiverId}```

 Transfer: ```Transferring ${deposit} NEAR to @${receiverId}```

 Stake: ```Staking ${stake}```

 AddKey (LAK): ```Adding access key for contract: @${permissionReceiverId}```

 DeleteKey: ```Deleting key ${publicKey}```

**Message for FAK action**
```
NEAR Wallet message

WARNING: Entering the code below will authorize full access to your NEAR account. If you did not initiate this action, please do not continue. 

This should only be done if you are adding a new seed phrase to your account. In all other cases, this is very dangerous.

If you'd like to proceed, enter this security code: <securityCode>
```

**Comment by mattlockyer** [comment]
Still working on formatting for HTML but this should be fine for now. @kcole16 thoughts?

![image](https://user-images.githubusercontent.com/321340/88841900-787bd300-d193-11ea-94e4-fe56cd35dd0a.png)

![image](https://user-images.githubusercontent.com/321340/88841918-803b7780-d193-11ea-8c5a-b1128314b5ad.png)

![image](https://user-images.githubusercontent.com/321340/88841981-9e08dc80-d193-11ea-947c-e392b74245eb.png)

**Comment by corwinharrell** [comment]
Being addressed in https://github.com/near/near-wallet/issues/1630
