### ISSUE TITLE
Delegate v1

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#753]
### Overview
To keep the v1 delegation flow simple, we can use a similar flow to `/send-money`. 

The validator whitelist can send users to `/staking/stake/<validator_name>/`, and we'll prepopulate the validator.

We should also display the users current delegated balance, the validator(s) they've delegated to, and their unclaimed rewards on `/staking`.

### Acceptance Criteria
On `/staking/stake`
- [ ] If there is no validator name in the `/staking/stake` URL, the user can enter the validator name
- [ ] A link with the validator name in it `/staking/stake/<validator_name>` prepopulates the validator name
- [ ] Users can enter the relevant details to initiate a delegation TX to the chosen validator
  - [ ] Amount of NEAR to delegate
- [ ] User sees available balance they can delegate with
  - [ ] "Available Balance" = available balance + lockup balance
- [ ] User cannot delegate more than "Available Balance"
- [ ] User can successfully delegate with NEAR in lockup contract

On `/staking`
- [ ] Users can view their total delegated balance
- [ ] Users can view their unclaimed rewards
- [ ] Users can view each validator they've delegated to
  - [ ] Validator name
  - [ ] Amount delegated
  - [ ] Unclaimed rewards

### Design Deliverables
**UI Design:** https://www.figma.com/file/oy0wBFxW5H8nTFZtFaMZpK/753-Delegate-v1?node-id=1162%3A795

**Interactive Prototype:** https://www.figma.com/proto/oy0wBFxW5H8nTFZtFaMZpK/753-Delegate-v1?node-id=1162%3A795&scaling=scale-down

**Comment by kcole16** [comment]
For v1, I think the two actions for users should be just "delegate" and "undelegate". "Delegate" should call both `deposit` and `stake` on the staking pool contract. “Undelegate” should call “unstake” and “withdraw”.

Should we allow users to specify the amount to undelegate in v1? Or just undelegate all?

Also, should we allow users to delegate to more than one validator in v1?

cc @mattlockyer @vgrichina @Patrick1904 @corwinharrell @jimmy3dita

**Comment by kcole16** [comment]
@jimmy3dita Do you think we can get Figment/Hubble to maintain which validators support delegation, and link to the appropriate delegation page for each of them?

**Comment by jimmy3dita** [comment]
> For v1, I think the two actions for users should be just "delegate" and "undelegate". "Delegate" should call both `deposit` and `stake` on the staking pool contract. “Undelegate” should call “unstake” and “withdraw”.

Be careful that `unstake` and `withdraw` cannot happen at the same time, there's a three epoch-long lock period for the funds. So a user that unstaked funds will have to wait until he can withdraw the funds.

> Should we allow users to specify the amount to undelegate in v1? Or just undelegate all?

The protocol automatically re-stakes all the funds, so it could be possible that users would like to withdraw only the rewards without "killing" their favorite validator. I suppose that we have to leave them free to set the amount (even in chunks of 0.1 Near or similar).

> Also, should we allow users to delegate to more than one validator in v1?

Depends on the amounts we plan to store in the wallet. Whales might be interested to use more than one validator - but at that point they might use a different tool such as near-shell.

> @jimmy3dita Do you think we can get Figment/Hubble to maintain which validators support delegation, and link to the appropriate delegation page for each of them?

for an updated list (maintained by validators themselves) we can use this section of the Stake Wars repo: https://github.com/nearprotocol/stakewars/blob/master/VALIDATORS.md#testnet-validators

**Comment by kcole16** [comment]
> Be careful that unstake and withdraw cannot happen at the same time, there's a three epoch-long lock period for the funds. So a user that unstaked funds will have to wait until he can withdraw the funds.

Good point. Breaking out the "Undelegate" functionality into a separate issue, as there is a bit more complexity than I realized: https://github.com/near/near-wallet/issues/755

**Comment by corwinharrell** [comment]
Wanted to share the WIP UI for Delegation. In an attempt to design/build this in an iterative fashion, the UI and prototype currently focus on the primary `stake` flow. The following is missing at the time of this post but is soon to follow:

- Total delegated balance
- Unclaimed rewards

Some things to note:

1. This UI leverages the current "Send" flow, but with a facelift. We have the option of using the updated version, which would result in an update to `Send` as well, or we can fall back on the current send flow and use it unchanged. The core elements between them are consistent, there are simply some improvements I made to the form.

2. As mentioned above, there will be some changes happening to the validator list and `li` design to include some additional metadata. Just wanted to mention this so we can anticipate those things changing to reflect things link rewards and additional actions. Right now they just contain the bare-minimum to facilitate the primary flow.

Please leave feedback and comments in Figma regarding any specific UI decisions or language used. cc @jimmy3dita 

Figma Doc: https://www.figma.com/file/q4OnMvaPpwowEZ9kCSOk2w/753-Delegate-v1?node-id=1101%3A1153

Interactive Prototype: https://www.figma.com/proto/q4OnMvaPpwowEZ9kCSOk2w/753-Delegate-v1?node-id=1101%3A1153&scaling=scale-down

**Comment by corwinharrell** [comment]
As we discussed at the end of last week, I'm going to scope the UI down for each individual issue within the delegation epic, so that we can build this out in an iterative fashion. I'll be moving the resources provided in my last comment to #722, where a "complete" version of the UI will live, representative of the Epic in its final state.

The following UI is limited to this issue, and only allows the user to enter a known validator, and stake with that validator:

https://www.figma.com/file/oy0wBFxW5H8nTFZtFaMZpK/753-Delegate-v1?node-id=1162%3A795

**Comment by corwinharrell** [comment]
@kcole16 With the re-introduction of the stripped down validator profile where the user will manage their stake and rewards, I'm wandering if we want to create an additional issue for "Manage my stake" that includes:

1. View my amount that is pending release from my validator
2. View my list of validators with unclaimed rewards
3. View my list of validators with funds available for withdrawal
4. Claim rewards from a validator
3. Withdraw my funds from a validator/delegation contract

Maybe it makes sense to roll these up into #755? Thoughts @mattlockyer @Patrick1904?

The way I'm thinking about the iterations of this project are as follows, which is slightly different than how the Epic is split up right now:

1. Stake with Known Validator
2. Find a validator (whitelist)
3. Manage my stake (unstake, claim rewards, withdraw balance)

**Comment by Patrick1904** [comment]
@kcole16 @corwinharrell can you please provide copy/explanations for the following staking concepts:
1. Total amount staked
2. Unclaimed rewards
3. Available for withdrawal
4. Pending release
5. Staking fee

<img width="372" alt="Screen Shot 2020-09-25 at 10 25 13 AM" src="https://user-images.githubusercontent.com/24921205/94297482-6b702b80-ff19-11ea-8280-4596da29c41c.png">

**Comment by bowenwang1996** [comment]
> Staking fee

This name feels a bit confusing to me. People could interpret it as the transaction fee associated with sending the staking transaction.

**Comment by kcole16** [comment]
@bowenwang1996 How about "Validator Fee"?

**Comment by bowenwang1996** [comment]
Yeah that sounds better

**Comment by Patrick1904** [comment]
@kcole16 @bowenwang1996 updating the copy to 'Validator Fee'.

**Comment by kcole16** [comment]
@Patrick1904 

Total amount staked
- NEAR tokens currently staked with validators. These tokens are accumulating rewards. To access these tokens, you must first unstake and then withdraw them.

Unclaimed rewards
- Rewards that have been earned, but not withdrawn. Unclaimed rewards are automatically restaked, which means your "Total Amount Staked" automatically increases over time, and your rewards are [compounding](https://www.investopedia.com/terms/c/compoundinterest.asp).

Available for withdrawal
- These tokens have been unstaked, and are ready to be withdrawn. 

Pending release
- These tokens have been unstaked, but are not yet ready to withdraw. Tokens are ready to withdraw 36 hours after unstaking.

Validator fee
- This is the fee paid to the validator to stake on your behalf. This fee is only charged on your rewards.
