### ISSUE TITLE
devnet has been deprecated. It needs to be removed from the code

### ISSUE THREAD

**Issue by janedegtiareva** [near/near-wallet#754]

**Comment by kcole16** [comment]
I don't think devnet is specified anywhere in the code. cc @vgrichina

**Comment by vgrichina** [comment]
@kcole16 I think we have usage of "devnet" in README and copy:

```
README.md
1:# NEAR DevNet Wallet

src/translations/zh-hans.global.json
328:        "text": "这是开发者的预览版钱包，仅限用于 NEAR 协议 DevNet。了解更多："

src/translations/ru.global.json
302:        "text": "Это предварительный кошелек разработчиков. Он должен использоваться только для NEAR Protocol DevNet. Узнайте больше на сайте "

src/translations/en.global.json
333:        "text": "This is a developers&apos; preview Wallet. It should be used for NEAR Protocol DevNet only. Learn more at "

```

that is not really referring to the `devnet` environment, but I think good idea to fix copy to make less confusing. May you help with that?

**Comment by kcole16** [comment]
READMe will fix. It doesn't look like we're actually displaying the other copy anywhere (since refactoring the `/create` page).
