### ISSUE TITLE
Display list of white-listed validators

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#764]
### Overview
As part of Delegation v1, we should display a list of white-listed validators for users to delegate to. These validators will have used the staking pool factory contract, and the list can be queried from the [whitelist contract](https://github.com/near/core-contracts/tree/master/whitelist) (cc @evgenykuzyakov @ilblackdragon if that's true).

### Acceptance Criteria
On `/staking`
- [x] All whitelisted validator staking pool contracts are listed
  - [x] Validator account ID
  - [x] Fee (`reward_fee_fraction`)
  - [ ] Total Stake
- [x] Selecting "Staking" next to a validator name redirects user to `/staking/stake/<validator_id>` see #753 

cc @mattlockyer @Patrick1904

**Comment by kcole16** [comment]
@jimmy3dita @evgenykuzyakov How easy is it to calculate the total stake of a validator?

**Comment by vgrichina** [comment]
@kcole16 looks like there is already live staking dashboard here https://staking.dokia.cloud/staking/near/validators

**Comment by bowenwang1996** [comment]
@kcole16 you can get it from validator rpc endpoint https://docs.near.org/docs/api/rpc#validators

**Comment by mattlockyer** [comment]
https://github.com/near/near-wallet/blob/cf9b41c250064cee922d2cd4133af80ecc55a03a/src/utils/staking.js#L37-L59

Here's an example of getting all validators and then calling RPC on each to get fee. Returns list of all validators with name, fee and contract instance for subsequent method calls.
