### ISSUE TITLE
Change default access key allowance to 0.25 N

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#775]
### Overview
Ahead of the gas price change to 100M yoctoNEAR, the default access key allowance needs to be changed to 0.25N.

@vgrichina Should we make this an env variable?

**Comment by vgrichina** [comment]
It is already env variable (`REACT_APP_ACCESS_KEY_FUNDING_AMOUNT`).

Updated here:
https://github.com/near/render-ops/commit/76bcb32c5b2b32f2ec564ffdb61d340579428ef9
https://github.com/nearprotocol/render-prod-ops/commit/bd377528c1a893ed8fa518d81a373325591213d1
