### ISSUE TITLE
If a functional call with token transfer attached fails, wallet UI erroneously reports success

### ISSUE THREAD

**Issue by janedegtiareva** [near/near-wallet#786]
**Problem**
If a functional call with token transfer attached fails, wallet UI erroneously reports success

**Expected Behavior**
The UI should wait for the status of function call and report error

**Steps to reproduce**
1.  make a function call with an attached deposit 
2.  set up the call so that it fails (e.g. insufficient balance in a FT transfer)
3.  wallet UI reports success
4.  Observe that explorer shows that transaction failed.

**Comment by thisisjoshford** [comment]
[screen cap](https://drive.google.com/file/d/1CuKfewfb1is1cfkHk-zfWZRL2VBeypHO/view?usp=sharing) of an example

[failed transaction](https://explorer.testnet.near.org/transactions/8UoZxTeR4Ngz9H6zckEoKozMaapfMrKtv2ZYB1eS7zL1) details in explorer

**Comment by kcole16** [comment]
@marcinbodnar Can you take a look at this?

**Comment by marcinbodnar** [comment]
@janedegtiareva @thisisjoshford I'm not sure how to reproduce this bug - if I choose too big donation Wallet will display `Insufficient Funds` and not allow to proceed.

**Comment by vgrichina** [comment]
@marcinbodnar I've been able to repro by making smart contract fail on purpose. Check out https://gitpod.io/#snapshot/5bcbfec4-8edb-4908-8cc8-41b1d276a081

When you try posting message with word "FAIL" – contract execution would fail, but we will still show success in the wallet.
