### ISSUE TITLE
Sign in with Ledger returns success when 0 accounts recovered

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#791]
**Problem**

<img width="1155" alt="Screen Shot 2020-08-07 at 6 45 42 PM" src="https://user-images.githubusercontent.com/126710/89699801-4af30000-d8de-11ea-93a4-790109cbc011.png">

**Expected Behavior**

Should explain to user that no accounts were found.

**Steps to reproduce**

1. Set Ledger to unique seed phrase or use a different network where you didn't create accounts with it yet.
2. Try "Sign in with Ledger"

**Comment by kcole16** [comment]
Updating this to P0 as it is now affecting all Ledger accounts on testnet on mainnet cc @vgrichina @marcinbodnar

**Comment by vgrichina** [comment]
Fixed in https://github.com/near/near-wallet/pull/804
