### ISSUE TITLE
Linkdrop doesn't work with non default account

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#793]
**Problem**
Linkdrop account is deployed on ww.illia.
Opening a link https://wallet.testnet.near.org/create/ww.illia/<key> doesn't show the ww.illia account as base account name.
Also when trying to create account with `testnet` it doesn't actually work because it does try to use linkdrop to create it.

**Expected Behavior**
It shows `ww.illia` as base account name.

**Steps to reproduce**

1. Create a linkdrop with not "testnet" account
2. Open it in the wallet
3. Observe failure of creating account

**Comment by kcole16** [comment]
Covered by #746, will add details to that one from here
