### ISSUE TITLE
bug: Blank page and error when clicking on an access key

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-wallet#809]
**Problem**

I go to https://wallet.testnet.near.org/authorized-apps and see 3 access keys (under `@meta` account):
<img width="1388" alt="Screen Shot 2020-08-12 at 3 30 18 PM" src="https://user-images.githubusercontent.com/470453/90074795-ca9f1700-dcb0-11ea-89f2-cebe7ccab4a7.png">

Then clicking on the 3rd key with no allowance and directed to itself, I get blank screen:
<img width="1387" alt="Screen Shot 2020-08-12 at 3 28 24 PM" src="https://user-images.githubusercontent.com/470453/90074838-dee31400-dcb0-11ea-8892-e7ff3139d713.png">

Clicking back doesn't help, because the previous page is blank as well after this.

**Expected Behavior**
No blank screen or errors

**Steps to reproduce**

Explained in the problem

**Comment by Patrick1904** [comment]
Closing as issue is outdated
