### ISSUE TITLE
Creating a new account should be completed by the active account

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#823]
### Overview
Currently, our accounts model is designed to work with either a linkdrop or a faucet. This works for the initial account, but does not work if the user wants to create additional accounts. Users should be able to pay for the TX to create a new account with their currently active account

### Acceptance Criteria
- [ ] User can create new accounts if their active account has an "Available Balance" of > 5 NEAR
- [ ] The user can choose the amount of NEAR to fund the new account with
- [ ] The new account is created in a batch TX signed by the user's active account

**Comment by vgrichina** [comment]
I think we also need to make sure there is enough context in UI (e.g. right now it's not clear when you are creating from linkdrop, I think here might be similar problem).

**Comment by vgrichina** [comment]
Linking PR in progress from @Patrick1904:
https://github.com/near/near-wallet/pull/1424

**Comment by MaximusHaximus** [comment]
@Patrick1904 @vgrichina @corwinharrell Could any of you folks take a look at this and re-cap what is left to do to allow this to be landed?  I'm going to close the associated PR #1424 until we're ready to work on this again (obviously the code is still here and able to be resurrected if it's relevant, when we get to this task again)

**Comment by corwinharrell** [comment]
@MaximusHaximus @Patrick1904 Part of this is being addressed in #2050, but I will be revisiting this shortly to update it with anything that falls out of scope of the coin-op issue (eg allowing the active account to denote a deposit amount, which will require an additional screen, vs just defaulting to a minimum deposit)

**Comment by Patrick1904** [comment]
Closing as issue is outdated
