### ISSUE TITLE
Withdraw from Lockup

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#825]
### Overview
Starting with Phase 2, some users will have unlocked tokens. These tokens will still be in the lockup contract, and will need to be withdrawn by calling a function on the contract.

To make this process easier for users, we should automatically withdraw from the lockup contract when users are performing actions that require additional tokens, particularly on `/send-money` AND `/sign`. 

We should include the unlocked balance in user's "Available Balance" so they are aware they have access to these tokens.

### Acceptance Criteria

- [ ] Users can view their unlocked balance in `/profile`
- [ ] "Available Balance" includes the unlocked balance
  - [ ] `/profile` page
  - [ ] `/send-money`
  - [ ] `/sign`
- [ ] Users are able to transfer their entire "Available Balance"
- [ ] Users are able to attach their entire "Available Balance" to a function call on `/sign`
- [ ] If the user's `Locked` balance is 0, any transaction will remove all tokens from the lockup contract, and delete the lockup account
- [ ] Mobile ok
- [ ] Tested

### Notes
[Lockup contract](https://github.com/near/core-contracts/tree/master/lockup#transfers-methods
)

**Important**: Before initiating any withdrawals, must call `check_transfer_vote`  on the lockup contract (only needs to be called once).

There are two types of withdrawals, one when only some tokens are unlocked, and one when all tokens are unlocked.

**Partial unlock**
1. Call `transfer` with the amount to be transferred

**Comment by kcole16** [comment]
Setting as P2 for right now, but will be promoted to P1 as soon as Phase 1 is live (as timeline will shrink quickly).

Also thinking we may want to make this more obvious than just on `/profile`, perhaps with either a banner "You have unlocked tokens, click here to withdraw" or putting the button on the Dashboard.

Thoughts? @corwinharrell @Patrick1904

**Comment by vgrichina** [comment]
Should we just withdraw automatically whatever amount is currently withdrawable before making any transaction?

**Comment by kcole16** [comment]
I do like the idea of automatic withdrawals, though we should figure out what a worst case TX cost scenario is (if user ends up with dozens of withdrawals or more over a 2 year lockup)

**Comment by vgrichina** [comment]
> I do like the idea of automatic withdrawals, though we should figure out what a worst case TX cost scenario is (if user ends up with dozens of withdrawals or more over a 2 year lockup)

yeah, we need to have some threshold I think. So that we withdraw tokens in such cases:
1) unlocked amount is over threshold (say 10 NEAR) which make fee unnoticable
2) there is not enough tokens to complete transaction otherwise

**Comment by kcole16** [comment]
@vgrichina Updated to reflect the current plan to initiate a withdrawal to top up the user's account during transaction flows.

One challenge is that most users will need to explicitly approve the `transfer` function for each withdrawal, in addition to whatever action they are trying to complete, as nearly every user has either Ledger or 2FA enabled.

This is somewhat similar to the situation with staking requiring two transactions cc @mattlockyer, so we likely need to work out a flow for it sooner rather than later.

**Comment by vgrichina** [comment]
From @evgenykuzyakov:

I want to bring important thing. Once the phase 2 happens, the tokens will not automatically unlock on every lockup. Instead every lockup contract needs to check for transfers by calling `check_transfers_vote()` with `75Tgas` .
Only after this lockup contracts will be able to issue `transfer` transactions.

**Comment by evgenykuzyakov** [comment]
BTW, on testnet the vote for phase 2 already happened. So we can start testing it. If you use `vote.f863973.m0` for initializing lockup contracts.

**Comment by evgenykuzyakov** [comment]
See https://github.com/near/core-contracts/tree/master/scripts for help
And https://github.com/near/core-contracts/blob/master/scripts/deploy_lockup.sh to deploy lockup contracts. You'll need the following env vars:
```bash
export MASTER_ACCOUNT_ID=f863973.m0
export LOCKUP_MASTER_ACCOUNT_ID=<YOUR_ACCOUNT>
export NEAR_ENV=testnet
``` 

Then run the script
