### ISSUE TITLE
Managed to Brick New Account Using Ledger via Linkdrop

### ISSUE THREAD

**Issue by mattlockyer** [near/near-wallet#828]
**Problem**

I followed a linkdrop from Kendall with 40N, chose matt.near, connected ledger, installed NEAR app, opened NEAR app on ledger. When I pressed continue on wallet, it showed:
![image](https://user-images.githubusercontent.com/321340/90918837-3c0a5400-e39a-11ea-8581-8aa03b1479db.png)

Retries using seed phrase or otherwise gives me:
![image](https://user-images.githubusercontent.com/321340/90918790-2301a300-e39a-11ea-8e2b-d11bf500bcec.png)

**Expected Behavior**

I can set up my account. My account in not unrecoverable.

**Steps to reproduce**

1. Follow linkdrop
2. Read instructions
3. Connect Ledger
4. Unlock
5. Enable experimental features
6. Install NEAR app
7. Open NEAR app on device
8. Press continue on wallet
9. Fail

**Comment by kcole16** [comment]
@vgrichina Should we validate each account in the list on initial load? If an account in the list isn't valid, we can just drop it.
