### ISSUE TITLE
near login doesn't work for account id longer than 32 characters

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-wallet#833]
**Problem**
near login doesn't work for account id longer than 32 characters because the text box in wallet doesn't allow one to enter a string that is longer than 32 characters.

**Expected Behavior**
It should work.

**Steps to reproduce**

1. Create an account that is longer than 32 characters on testnet
2. Run `near login` locally and observe that you cannot enter the account id.

**Comment by kcole16** [comment]
@bowenwang1996 This is intended behavior.

Isn’t the account name maximum length 32 characters?

**Comment by crypto-guys** [comment]
This happened to me earlier today 

Steps to reproduce.
On betanet create an account with 33 characters in the name.
crypto-solutions-warchest.betanet  
run **near login** 
Open the provided link in browser.
The form will not display the name correctly.
![image](https://user-images.githubusercontent.com/50590698/90999013-16906c80-e58b-11ea-8287-94fee1f3eb18.png)

If I click allow I am asked to type the name to confirm.
The box will only accept 32 characters

**Comment by bowenwang1996** [comment]
@kcole16 that is not true. The maximum length is 64 characters.
