### ISSUE TITLE
Using or Removing react-modal from dependencies

### ISSUE THREAD

**Issue by kamescg** [near/near-wallet#854]
I noticed the module `react-modal` has been installed but is not being used in the application.

The `Modal` component is available in `components/common` and used in several components.

Moving forward are we expected to use `react-modal` or the custom Modal component?

If not intended for usage can we remove from dependencies to de-incentivize using two different Modal solutions?

**Comment by Patrick1904** [comment]
Yes please use the custom Modal component and yes we can remove `react-modal` if it's not being used.

**Comment by Patrick1904** [comment]
Closing as `react-modal` is no longer installed.
