### ISSUE TITLE
Illegal access violation error for redeployed contract

### ISSUE THREAD

**Issue by zavodil** [near/near-wallet#855]
**Steps to reproduce**
1. I made a [dapp](https://github.com/zavodil/memepool) with the web login
2. logged in with browser
3. called a function

4. redeployed smart contract on a different contract id and run on the same url

**Problem**
5. I called a function which needs wallet authorization and got an error in js console
`Uncaught (in promise) Error: Transaction nonce 47 must be larger than nonce of the used access key 47
    at Object.f [as parseRpcError] (rpc_errors.js:38)
    at d.sendJsonRpc (json-rpc-provider.js:147)`

and wallet error on UI:
`Transaction cancelled
Nothing has been transferred.`

**Expected Behavior**
- Output straight forward error about access key violation
- May be add to guidelines advice to check contract id

**Comment by kcole16** [comment]
@zavodil Have you noticed this issue recently?

**Comment by zavodil** [comment]
@kcole16 no but I didn't check logs, I just logout/login in this case now.

**Comment by jimmy3dita** [comment]
Will close this one by now
