### ISSUE TITLE
Adding e-mail recovery method with 2FA doesn't seem to work

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#903]
**Problem**

Check test-seed-phrase1.testnet account.

I've tried enabling e-mail recovery method, but it doesn't show up as enabled in Profile (even though I confirmed 2FA). 

Adding it seems like succeeded: https://explorer.testnet.near.org/transactions/ELgY9S2NJVCS61SeFvxzGRTXKqcQ9YEfJbnESbM8dv6U

**Expected Behavior**

E-mail recovery method should show up in Profile

**Steps to reproduce**

Note sure if this is reproducible but I did this:

1. Create account from linkdrop with seed phrase as recovery.
2. Had to configure 2FA (I chose e-mail) as linkdrop had enough tokens.
3. Tried to add e-mail recovery with the same e-mail

**Comment by mattlockyer** [comment]
@Patrick1904 any aggressive filters added to the recovery methods list lately?

Here's a screenshot post 2fa setup with email for an account created with email recovery.

![image](https://user-images.githubusercontent.com/321340/93164317-15f07f00-f6ce-11ea-90ed-06c6bb13df70.png)

**Comment by mattlockyer** [comment]
Looks like we're still returning 2 email recovery methods:

![image](https://user-images.githubusercontent.com/321340/93164465-6536af80-f6ce-11ea-8a26-8ad7ed7b13a8.png)

**Comment by Patrick1904** [comment]
https://github.com/near/near-wallet/blob/master/src/components/profile/Recovery/RecoveryContainer.js#L84

**Comment by mattlockyer** [comment]
The check shouldn't be for a full access key though. Since recovery keys for 2FA accounts will be switched from FAKs to LAKs.

I have a small fix coming soon.

**Comment by vgrichina** [comment]
Re-opening as still seems to happen for https://wallet.testnet.near.org/profile/test-seed-phrase1.testnet

**Comment by mattlockyer** [comment]
@Patrick1904 any more insight on this?

I can't reproduce the issue anymore and this is probably the first time I've ever worked with this component.

We only need to:
1. get all access keys
2. get all recovery methods
3. filter out recovery methods that do NOT have an access key for the account

Some extra component / render logic comes after this and I'm afraid if I try to fix this I'll break something else.

**Comment by vgrichina** [comment]
Seems like it has been some caching issue, works now
