### ISSUE TITLE
Handle seed phrase error when account is created

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#911]
### Overview
Users sometimes encounter an error when creating an account with a seed phrase via linkdrop, even though the transaction is succeeding. We should only show the user an error at this step if it is the actual account creation transaction that is failing, otherwise they will be mislead into thinking their account wasn't successfully created.

A simple solution is to retry the TX after the linkdrop claim TX, as this should eventually succeed. If it doesn't after ~5 retries, we should check if the account has been created, and if it has, log the user in.

https://github.com/near/near-wallet/pull/905#issuecomment-692793925

### Acceptance Criteria
When creating an account using linkdrop
- [ ] At the `/verify` step, users only encounter an error if the linkdrop claim step is failing
- [ ] If the second "addKey" TX fails, the TX is retried
- [ ] If the account is created successfully, the user is redirected to the `/profile` page

![Screen Shot 2020-09-15 at 1 16 51 PM](https://user-images.githubusercontent.com/5624527/93386370-755ca500-f81c-11ea-9eb8-58f32cbbd313.png)

**Comment by vgrichina** [comment]
@kcole16 @marcinbodnar  retries are already happening in near-api-js for about a minute or even more. 

We need to focus on recovery from failure when user lands on /profile, refreshes page, etc

**Comment by vgrichina** [comment]
> At the /verify step, users only encounter an error if the linkdrop claim step is failing

that's not true AFAIK. I think what is happening in many cases is that account creation succeeds but other steps fail (or are interrupted), e.g. marking given key as seed phrase on contract helper

**Comment by kcole16** [comment]
@vgrichina @Patrick1904 @mattlockyer Have you been able to reproduce these errors? I haven't, but the two common states I'm seeing are:
- Users encounter an error on the `/verify` step and never make it to `/profile`, and then think the linkdrop is toast
- Users make it to `/profile`, but do not have the correct seed phrase written down

And seems like the second case is essentially the first, but they selected "Start Over", and then were redirected from `/verify` to `/profile`?

**Comment by marcinbodnar** [comment]
@kcole16 
> Users encounter an error on the /verify step and never make it to /profile, and then think the linkdrop is toast

It might be because error occurs while creating an account or adding key

> Users make it to /profile, but do not have the correct seed phrase written down

In this case, the account was created, the key was added but the contract helper fails to add recovery method

**Comment by vgrichina** [comment]
@kcole16 @marcinbodnar I think we have to test with artificially introduced errors, e.g. like here https://github.com/near/near-wallet/pull/892

**Comment by mattlockyer** [comment]
@kcole16 I haven't been able to reproduce these since we switched to adding the seed phrase key in the linkdrop claim step.

But I think the error communicated by users is the issue when they don't get a valid RPC response from that, wallet tells them there's an error and they "Start Over". Which is why we killed start over so they don't throw out the first seed phrase...

It's like a timeout error on account creation, but we're not checking after we received RPC error if the account was created or not.

One solution out of this is to check if account exists after getting any RPC error during linkdrop claim / account creation and then if the account exists on chain, push to profile??? Thoughts?

**Comment by mattlockyer** [comment]
Accidental close

**Comment by marcinbodnar** [comment]
@mattlockyer @kcole16 @vgrichina 
> It's like a timeout error on account creation, but we're not checking after we received RPC error if the account was created or not.

I implemented a solution for that long time ago, but I can see now that it was removed - it was causing problems @vgrichina ?
https://github.com/near/near-wallet/commit/24f548fbae13457c187bf28120367f80c5cc47d3#diff-178a60e843b843091b6d2927f9c3ef22L343

**Comment by vgrichina** [comment]
@marcinbodnar we switched to saving account before attempting to create it online. There is no guarantee we will get explicit error (user might refresh the page, close browser, etc).

**Comment by vgrichina** [comment]
Note that we fixed issue with accounts being lost completely, I think main problem right now is that we end up in inconsistent state with no ability to re-setup seed phrase successfully + we have confusing feedback for user.

**Comment by kcole16** [comment]
@marcinbodnar Can we close this?

**Comment by marcinbodnar** [comment]
@kcole16 PR not merge yet, I linked this issue to PR
