### ISSUE TITLE
Support multiple HD paths for Ledger during login

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#926]
### Overview
Many users of the NEAR Ledger are likely to use HD paths that are different from the default path: `44'/397'/0'/0'/1'`

Currently, we assume all accounts use this HD path during recovery. 

We should allow users to choose a non-standard HD path, or even cycle through some number of paths (first 100?) and add accounts with those public keys to the list of accounts available to recover during `/sign-in-ledger`.

**Comment by kcole16** [comment]
cc @vgrichina @marcinbodnar @corwinharrell 

Potential low lift pass? 

![HD_path_mockup](https://user-images.githubusercontent.com/5624527/94091677-a9f8cf80-fdcd-11ea-8664-0954a37c84e6.png)

**Comment by Patrick1904** [comment]
Shipped in https://github.com/near/near-wallet/pull/1559
