### ISSUE TITLE
Allow sending to implicit accounts

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#931]
### Overview
Now that we have implicit accounts, we should allow users to send to accounts with exactly 64 characters, even if they don't exist on-chain. We should also explain the risk of doing so, and prompt the user to double check the address.

### Acceptance Criteria
- [ ] Users can send to accounts with exactly 64 characters that do not exist on-chain
- [ ] When sending to non-existent account, the user sees the below message

**Warning Message**
```
Warning: If this is an exchange account, or an account you control, please double check the account ID. If the account name is entered incorrectly, your funds will be lost forever.
```

**Comment by kcole16** [comment]
**Steps if Implicit Accounts Don't Exist**
1. Transfer 0.5 NEAR to the implicit account (to instantiate)
2. Transfer rest of desired amount to the implicit account

cc @vgrichina

**Comment by vgrichina** [comment]
@bowenwang1996 why is this transaction failing https://explorer.testnet.near.org/transactions/BuvCUudDgzJVPY5Pqh6cZRpUy3kMuPfZAAwYGGJgvWM5?

Are implicit accounts enabled on testnet?

**Comment by bowenwang1996** [comment]
@vgrichina testnet had some issue yesterday. It should be fine now
