### ISSUE TITLE
Refresh balance along with tx activity

### ISSUE THREAD

**Issue by jakestutzman** [near/near-wallet#937]
**Problem**
When staking via CLI, the 'activity' on the Dashboard updates with the new transaction automatically, but i have to refresh to see the new balance. 

**Expected Behavior**
If you're showing me my tx in real-time, my balance should update with it. (OR, require refresh for both - they should be consistent so the user isn't confused)

**Steps to reproduce**

1. With wallet open in browser, stake via CLI
2. Watch 'Activity' update... but balance stays the same

**Comment by jimmy3dita** [comment]
Will be fixed by #1643
