### ISSUE TITLE
Seed phrase recovery not available when there is existing account with seed phrase

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#947]
**Problem**

Looks like when you are creating account and you already have existing account active (with seed phrase recovery) – you cannot select seed phrase as recovery method.

<img width="962" alt="Screen Shot 2020-09-29 at 1 48 18 PM" src="https://user-images.githubusercontent.com/126710/94614508-215db180-025b-11eb-9f8c-f7197e36458a.png">

**Expected Behavior**

You still can select seed phrase, active account shouldn't impact setting up new account.

**Steps to reproduce**

1. Switch to account which uses seed phrase recovery.
2. Try creating new account with seed phrase recovery.

**Comment by kcole16** [comment]
@vgrichina This must have started with a recent change, as I always create new accounts with seed phrase when testing
