### ISSUE TITLE
Support implicit account recovery from seed phrase

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#950]
### Overview
We have quite a few users that either directly created an implicit account from a seed phrase in the CLI, or used Trust Wallet to generate one. We should support recovering an account into the Wallet by entering the seed phrase for these accounts.

**Note:**
The scope of this issue only includes implicit accounts that already exist on-chain, as there are a few changes needed to support accounts that have not yet been instantiated (and thus have zero balance).

### Acceptance Criteria
- [ ] Account is loaded correctly when entering the seed phrase for an existing implicit account on `/recover-seed-phrase`
   - [x] Works with CLI generated accounts
   - [ ] Works with Trust Wallet generated accounts

**Comment by vgrichina** [comment]
> The scope of this issue only includes implicit accounts that already exist on-chain, as there are a few changes needed to support accounts that have not yet been instantiated (and thus have zero balance).

After thinking about it – I think we shouldn't directly support accounts which haven't been created yet. As literally every seed phrase has such account (before it's been claimed and keys replaced), so in normal seed phrase recovery flow it's going to be a distraction. 

Makes sense to support these as part of exchange integration flows.
