### ISSUE TITLE
You can "successfully" recover 0 accounts

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#951]
**Problem**

You can "successfully" recover 0 accounts.

<img width="1166" alt="Screen Shot 2020-09-30 at 3 18 37 PM" src="https://user-images.githubusercontent.com/126710/94745856-61429880-0330-11eb-9172-4ce55b0cc5bf.png">

**Expected Behavior**

Error is displayed to user.

**Steps to reproduce**

Try to recover using any bogus seed phrase not matching any accounts.

**Comment by marcinbodnar** [comment]
@vgrichina I'm sure I was fixing it before, not sure why this check was removed, probably by mistake. I will add it again.

**Comment by vgrichina** [comment]
Maybe accidentally caused by some other change, thanks for looking!
