### ISSUE TITLE
Viewing stake positions from base accounts (not lockups)

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#954]
### Overview
Staking v1 only supports staking through lockups. The first component of this is allowing users to view their stake positions, as we have several users that have used Dokia to stake through their base account and are confused that this isn't reflected in the wallet.

### Acceptance Criteria
- [ ] Users can view all of their stake positions from their base account

@mattlockyer's  proposed solution:
- Toggle switch on the staking page where user can choose between viewing/changing staking for the current account vs. lockup for that account.
- Still show how much there is in the lockup i.e. total balance around the toggle. When selected it updates the UI totals reflecting either the account or the lockup.

**Comment by corwinharrell** [comment]
Here is the design for the new staking source component addition:

https://www.figma.com/file/ftGWoPAFwrbrMQit5xy486/954-Select-Staking-Source?node-id=1%3A131

<img width="1041" alt="Screen Shot 2020-10-16 at 4 17 02 PM" src="https://user-images.githubusercontent.com/5934188/96304976-13ce5880-0fcb-11eb-82e0-a56730ca4351.png">

As mentioned in slack, if the user does not have a lockup, the component should be hidden.

@Patrick1904 You'll also notice that I'm requesting some small changes to the design of the staking dashboard metrics as well. For mobile, let's go ahead and make them 100% width without any vertical space in-between. This is in preparation for some upcoming design changes to wallet.

**Comment by Patrick1904** [comment]
@corwinharrell looks good to me. Should we still show the available balance to stake somewhere on the main dashboard? Is the number in the dropdown total available to stake? If so, user won't be able to see that here unless they have a lockup account.

**Comment by corwinharrell** [comment]
@Patrick1904 yes, the number in the dropdown is the available balance. If they don't have a lockup, wouldn't the available balance be the same as what we display in `/profile`?

**Comment by Patrick1904** [comment]
> @Patrick1904 yes, the number in the dropdown is the available balance. If they don't have a lockup, wouldn't the available balance be the same as what we display in `/profile`?

Yes in case of no-lockup, they'd have to navigate to profile to see it. Personally I find value in being able to view available balance on this page too

**Comment by corwinharrell** [comment]
@Patrick1904 in that case, why don't we leave the component in, but "disable" it, where it's disabled state just has the arrow set to `display: none;`?

**Comment by Patrick1904** [comment]
> @Patrick1904 in that case, why don't we leave the component in, but "disable" it, where its disabled state just has the arrow set to `display: none;`?

That works great!
