### ISSUE TITLE
Add warning on /login for Lockup accounts

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#981]
### Overview
Adding a limited access key to lockup contracts does allow the app to transfer tokens. The current warning is insufficient for the severity of this permission. We should display the same warning as adding a full access key (e.g. when using `near login`).

### Acceptance Criteria
- [ ] When the account being authorized is the user's lockup account, they receive the same warning as `near login`
- [ ] User must enter their account name to complete the transaction

### Notes
The user's lockup account schema is found here: https://github.com/near/near-wallet/blob/master/src/utils/wallet.js#L601

**Comment by kcole16** [comment]
@marcinbodnar How are we determining when to show the more aggressive page for `/login`? e.g. the one we show when adding a full access key e.g. `near login`

**Comment by marcinbodnar** [comment]
@kcole16 at this moment the more aggressive page is shown if there is a `contract_id` param in the URL.
